export const BRAND_COLORS = {
  SAGE_GREEN: '#7A8E78',
  DEEP_GRAPHITE: '#1F2428',
  SOFT_GOLD: '#B39A63',
  STEEL: '#A7B1B7',
  BONE_WHITE: '#F3F1EC',
  WARM_WHITE: '#F7F5F0',
  ECO_TINT: '#EEF0EC',
  LIGHT_BROWN: '#F5E6D0',
  PAPER_WHITE: '#FDFAF6',
} as const

export const PAGE_HERO_GRADIENT = `linear-gradient(160deg, ${BRAND_COLORS.WARM_WHITE} 0%, ${BRAND_COLORS.BONE_WHITE} 60%, ${BRAND_COLORS.ECO_TINT} 100%)`

export const RECIPE_BOOK_FONT = '"Porte Bon Heur", cursive'
