import type { NutritionProfile } from '@/types'

export const NUTRITION_PINK_OYSTER_MUSHROOM: NutritionProfile = {
  product: 'Fresh Pink Oyster Mushroom',
  referenceProfile: 'Raw pink oyster mushroom / Pleurotus djamor',
  servingReference: 'Per 100 g raw product',
  dataSource: 'USDA FoodData Central / Analytical data for Pleurotus spp.',
  note: 'These are reference values for fresh pink oyster mushroom. Final Prozekt-1 pack label values should be confirmed through product lab testing before printing on packaging.',
  nutrients: [
    { label: 'Energy', value: '43 kcal' },
    { label: 'Water', value: '88.8 g' },
    { label: 'Carbohydrates', value: '6.5 g' },
    { label: 'Total sugars', value: '1.11 g' },
    { label: 'Added sugar', value: '0 g' },
    { label: 'Dietary fibre', value: '2.3 g' },
    { label: 'Protein', value: '3.31 g' },
    { label: 'Total fat', value: '0.41 g' },
    { label: 'Saturated fat', value: '0.06 g' },
    { label: 'Trans fat', value: '0 g' },
    { label: 'Cholesterol', value: '0 mg' },
    { label: 'Sodium', value: '18 mg' },
    { label: 'Salt equivalent', value: '~0.045 g' },
  ],
  vitamins: [
    { label: 'Vitamin B1 / Thiamin', value: '0.13 mg' },
    { label: 'Vitamin B2 / Riboflavin', value: '0.35 mg' },
    { label: 'Vitamin B3 / Niacin', value: '4.96 mg' },
    { label: 'Vitamin B5 / Pantothenic acid', value: '1.29 mg' },
    { label: 'Vitamin B6', value: '0.11 mg' },
    { label: 'Vitamin B9 / Folate', value: '38 mcg' },
    { label: 'Vitamin C', value: '2 mg' },
    { label: 'Vitamin D', value: '0.7 mcg' },
    { label: 'Choline', value: '48.70 mg' },
    { label: 'Vitamin A', value: '2 mcg RAE' },
    { label: 'Beta-carotene', value: '29 mcg' },
  ],
  minerals: [
    { label: 'Calcium', value: '3 mg' },
    { label: 'Iron', value: '1.33 mg' },
    { label: 'Magnesium', value: '18 mg' },
    { label: 'Phosphorus', value: '120 mg' },
    { label: 'Potassium', value: '420 mg' },
    { label: 'Sodium', value: '18 mg' },
    { label: 'Zinc', value: '0.77 mg' },
    { label: 'Copper', value: '0.24 mg' },
    { label: 'Manganese', value: '0.11 mg' },
    { label: 'Selenium', value: '2.60 mcg' },
  ],
}

export const NUTRITION_OYSTER_MUSHROOM_MATVARETABELLEN: NutritionProfile = {
  product: 'Fresh Oyster Mushroom',
  referenceProfile: 'Raw oyster mushroom / Pleurotus spp.',
  servingReference: 'Per 100 g raw product',
  dataSource: 'Norwegian Food Composition Table / Matvaretabellen',
  note: 'These are reference values for raw oyster mushroom. Final Prozekt-1 pack label values should be confirmed through product lab testing before printing on packaging.',
  nutrients: [
    { label: 'Energy', value: '27 kcal' },
    { label: 'Water', value: '93.0 g' },
    { label: 'Carbohydrates', value: '2.6 g' },
    { label: 'Total sugars', value: '2.6 g' },
    { label: 'Added sugar', value: '0 g' },
    { label: 'Dietary fibre', value: '2.0 g' },
    { label: 'Protein', value: '2.0 g' },
    { label: 'Total fat', value: '0.4 g' },
    { label: 'Saturated fat', value: '0.1 g' },
    { label: 'Trans fat', value: '0 g' },
    { label: 'Cholesterol', value: '0 mg' },
    { label: 'Sodium', value: '18 mg' },
    { label: 'Salt equivalent', value: '0 g' },
  ],
  vitamins: [
    { label: 'Vitamin A', value: '2 RAE' },
    { label: 'Beta-carotene', value: '29 mcg' },
    { label: 'Vitamin B1 / Thiamin', value: '0.07 mg' },
    { label: 'Vitamin B2 / Riboflavin', value: '0.20 mg' },
    { label: 'Vitamin B3 / Niacin', value: '5.2 mg' },
    { label: 'Vitamin B6', value: '0.11 mg' },
    { label: 'Vitamin B9 / Folate', value: '51 mcg' },
    { label: 'Vitamin B12', value: '0 mcg' },
    { label: 'Vitamin C', value: '2 mg' },
    { label: 'Vitamin D', value: '0 mcg' },
    { label: 'Vitamin E', value: '0 mg' },
  ],
  minerals: [
    { label: 'Calcium', value: '0 mg' },
    { label: 'Sodium', value: '18 mg' },
    { label: 'Potassium', value: '298 mg' },
    { label: 'Magnesium', value: '16 mg' },
    { label: 'Phosphorus', value: '110 mg' },
    { label: 'Iron', value: '0.4 mg' },
    { label: 'Zinc', value: '0.7 mg' },
    { label: 'Selenium', value: '1 mcg' },
    { label: 'Copper', value: '0.24 mg' },
  ],
}

export const NUTRITION_OYSTER_MUSHROOM_USDA: NutritionProfile = {
  product: 'Fresh White Oyster Mushroom',
  referenceProfile: 'Raw oyster mushroom / Pleurotus spp.',
  servingReference: 'Per 100 g raw product',
  dataSource: 'USDA FoodData Central / Foundation Foods — FDC reference: 168580, "Mushrooms, oyster, raw"',
  note: 'These are reference values for raw oyster mushroom. Final Prozekt-1 pack label values should be confirmed through product lab testing before printing on packaging.',
  nutrients: [
    { label: 'Energy', value: '33 kcal' },
    { label: 'Water', value: '89.20 g' },
    { label: 'Carbohydrates', value: '6.09 g' },
    { label: 'Total sugars', value: '1.11 g' },
    { label: 'Dietary fibre', value: '2.30 g' },
    { label: 'Protein', value: '3.31 g' },
    { label: 'Total fat', value: '0.41 g' },
    { label: 'Saturated fat', value: '0.06 g' },
    { label: 'Cholesterol', value: '0 mg' },
    { label: 'Sodium', value: '18 mg' },
  ],
  vitamins: [
    { label: 'Vitamin A', value: '2 mcg RAE' },
    { label: 'Beta-carotene', value: '29 mcg' },
    { label: 'Vitamin B1 / Thiamin', value: '0.13 mg' },
    { label: 'Vitamin B2 / Riboflavin', value: '0.35 mg' },
    { label: 'Vitamin B3 / Niacin', value: '4.96 mg' },
    { label: 'Vitamin B5 / Pantothenic acid', value: '1.29 mg' },
    { label: 'Vitamin B6', value: '0.11 mg' },
    { label: 'Vitamin B9 / Folate', value: '38 mcg' },
    { label: 'Vitamin D', value: '0.70 mcg' },
    { label: 'Choline', value: '48.70 mg' },
  ],
  minerals: [
    { label: 'Calcium', value: '3 mg' },
    { label: 'Iron', value: '1.33 mg' },
    { label: 'Magnesium', value: '18 mg' },
    { label: 'Phosphorus', value: '120 mg' },
    { label: 'Potassium', value: '420 mg' },
    { label: 'Sodium', value: '18 mg' },
    { label: 'Zinc', value: '0.77 mg' },
    { label: 'Copper', value: '0.24 mg' },
    { label: 'Manganese', value: '0.11 mg' },
    { label: 'Selenium', value: '2.60 mcg' },
  ],
}

export const NUTRITION_BUTTON_MUSHROOM_MATVARETABELLEN: NutritionProfile = {
  product: 'Fresh Button Mushroom',
  referenceProfile: 'Raw common mushroom / Agaricus bisporus',
  servingReference: 'Per 100 g raw product',
  dataSource: 'Matvaretabellen food-composition table',
  note: 'These are reference values for raw button/common mushroom. Final Prozekt-1 pack label values should be confirmed through product lab testing before printing on packaging.',
  nutrients: [
    { label: 'Energy', value: '17 kcal' },
    { label: 'Water', value: '94.0 g' },
    { label: 'Carbohydrates', value: '0.1 g' },
    { label: 'Total sugars', value: '0.1 g' },
    { label: 'Added sugar', value: '0 g' },
    { label: 'Dietary fibre', value: '4.0 g' },
    { label: 'Protein', value: '2.3 g' },
    { label: 'Total fat', value: '0.1 g' },
    { label: 'Saturated fat', value: '0 g' },
    { label: 'Trans fat', value: '0 g' },
    { label: 'Cholesterol', value: '0 mg' },
    { label: 'Sodium', value: '4 mg' },
    { label: 'Salt equivalent', value: '0 g' },
  ],
  vitamins: [
    { label: 'Vitamin A', value: '0 RAE' },
    { label: 'Beta-carotene', value: '0 mcg' },
    { label: 'Vitamin B1 / Thiamin', value: '0 mg' },
    { label: 'Vitamin B2 / Riboflavin', value: '0.35 mg' },
    { label: 'Vitamin B3 / Niacin', value: '3.0 mg' },
    { label: 'Vitamin B6', value: '0.07 mg' },
    { label: 'Vitamin B9 / Folate', value: '23 mcg' },
    { label: 'Vitamin B12', value: '0 mcg' },
    { label: 'Vitamin C', value: '0 mg' },
    { label: 'Vitamin D', value: '0 mcg' },
    { label: 'Vitamin E', value: '0 mg' },
  ],
  minerals: [
    { label: 'Calcium', value: '3 mg' },
    { label: 'Sodium', value: '4 mg' },
    { label: 'Potassium', value: '349 mg' },
    { label: 'Magnesium', value: '9 mg' },
    { label: 'Phosphorus', value: '85 mg' },
    { label: 'Iron', value: '0.2 mg' },
    { label: 'Zinc', value: '0.4 mg' },
    { label: 'Selenium', value: '17 mcg' },
    { label: 'Copper', value: '0.2 mg' },
    { label: 'Iodine', value: '0 mcg' },
  ],
}

export const NUTRITION_BUTTON_MUSHROOM_USDA: NutritionProfile = {
  product: 'Fresh Button Mushroom',
  referenceProfile: 'Raw white button mushroom / Agaricus bisporus',
  servingReference: 'Per 100 g raw product',
  dataSource: 'USDA FoodData Central / SR Legacy food-composition data',
  note: 'These are reference values for raw white button mushroom. Final Prozekt-1 pack label values should be confirmed through product lab testing before printing on packaging.',
  nutrients: [
    { label: 'Energy', value: '22 kcal' },
    { label: 'Water', value: '92.45 g' },
    { label: 'Carbohydrates', value: '3.26 g' },
    { label: 'Total sugars', value: '1.98 g' },
    { label: 'Added sugar', value: '0 g' },
    { label: 'Dietary fibre', value: '1.0 g' },
    { label: 'Protein', value: '3.09 g' },
    { label: 'Total fat', value: '0.34 g' },
    { label: 'Saturated fat', value: '0.05 g' },
    { label: 'Trans fat', value: '0 g' },
    { label: 'Cholesterol', value: '0 mg' },
    { label: 'Sodium', value: '5 mg' },
    { label: 'Salt equivalent', value: '~0.01 g' },
  ],
  vitamins: [
    { label: 'Vitamin B1 / Thiamin', value: '0.081 mg' },
    { label: 'Vitamin B2 / Riboflavin', value: '0.402 mg' },
    { label: 'Vitamin B3 / Niacin', value: '3.607 mg' },
    { label: 'Vitamin B5 / Pantothenic acid', value: '1.497 mg' },
    { label: 'Vitamin B6', value: '0.104 mg' },
    { label: 'Vitamin B9 / Folate', value: '17 mcg' },
    { label: 'Vitamin C', value: '2.1 mg' },
    { label: 'Vitamin D', value: '0.2 mcg' },
    { label: 'Choline', value: '17.3 mg' },
  ],
  minerals: [
    { label: 'Calcium', value: '3 mg' },
    { label: 'Iron', value: '0.50 mg' },
    { label: 'Magnesium', value: '9 mg' },
    { label: 'Phosphorus', value: '86 mg' },
    { label: 'Potassium', value: '318 mg' },
    { label: 'Zinc', value: '0.52 mg' },
    { label: 'Copper', value: '0.318 mg' },
    { label: 'Selenium', value: '9.3 mcg' },
  ],
}

export const NUTRITION_BUTTON_MUSHROOM_USDA_FDC: NutritionProfile = {
  product: 'Fresh Button Mushroom',
  referenceProfile: 'Raw white button mushroom / Agaricus bisporus',
  servingReference: 'Per 100 g raw product',
  dataSource: 'USDA FoodData Central reference profile, FDC ID 1750347',
  note: 'These are reference values for raw white button mushroom. Final Prozekt-1 pack label values should be confirmed through product lab testing before printing on packaging.',
  nutrients: [
    { label: 'Energy', value: '31 kcal' },
    { label: 'Water', value: '91.83 g' },
    { label: 'Carbohydrates', value: '4.08 g' },
    { label: 'Total sugars', value: '0 g' },
    { label: 'Added sugar', value: '0 g' },
    { label: 'Dietary fibre', value: '0 g' },
    { label: 'Protein', value: '2.89 g' },
    { label: 'Total fat', value: '0.37 g' },
    { label: 'Saturated fat', value: '0 g' },
    { label: 'Trans fat', value: '0 g' },
    { label: 'Cholesterol', value: '0 mg' },
    { label: 'Sodium', value: '6.44 mg' },
  ],
  vitamins: [
    { label: 'Vitamin A', value: '0 mcg' },
    { label: 'Vitamin B1 / Thiamin', value: '0.07 mg' },
    { label: 'Vitamin B3 / Niacin', value: '3.88 mg' },
    { label: 'Vitamin B6', value: '0.08 mg' },
    { label: 'Vitamin B7 / Biotin', value: '9.07 mcg' },
    { label: 'Vitamin B9 / Folate', value: '34.76 mcg DFE' },
    { label: 'Vitamin C', value: '0 mg' },
    { label: 'Vitamin D', value: '0 mcg' },
  ],
  minerals: [
    { label: 'Calcium', value: '5.46 mg' },
    { label: 'Iron', value: '0.23 mg' },
    { label: 'Magnesium', value: '10.16 mg' },
    { label: 'Phosphorus', value: '93.05 mg' },
    { label: 'Potassium', value: '373 mg' },
    { label: 'Sodium', value: '6.44 mg' },
    { label: 'Zinc', value: '0.51 mg' },
    { label: 'Copper', value: '0.39 mg' },
    { label: 'Manganese', value: '0.05 mg' },
    { label: 'Selenium', value: '20.05 mcg' },
  ],
}

export const NUTRITION_SHIITAKE_MUSHROOM: NutritionProfile = {
  product: 'Fresh Shiitake Mushroom',
  referenceProfile: 'Raw shiitake mushroom / Lentinula edodes',
  servingReference: 'Per 100 g raw product',
  dataSource: 'Matvaretabellen food-composition table',
  note: 'These are reference values for raw shiitake mushroom. Final Prozekt-1 pack label values should be confirmed through product lab testing before printing on packaging.',
  nutrients: [
    { label: 'Energy', value: '27 kcal' },
    { label: 'Water', value: '92.0 g' },
    { label: 'Carbohydrates', value: '2.5 g' },
    { label: 'Total sugars', value: '2.5 g' },
    { label: 'Added sugar', value: '0 g' },
    { label: 'Dietary fibre', value: '3.0 g' },
    { label: 'Protein', value: '1.8 g' },
    { label: 'Total fat', value: '0.3 g' },
    { label: 'Saturated fat', value: '0 g' },
    { label: 'Trans fat', value: '0 g' },
    { label: 'Cholesterol', value: '0 mg' },
    { label: 'Sodium', value: '1 mg' },
    { label: 'Salt equivalent', value: '0 g' },
  ],
  vitamins: [
    { label: 'Vitamin A', value: '2 mcg RAE' },
    { label: 'Beta-carotene', value: '29 mcg' },
    { label: 'Vitamin B1 / Thiamin', value: '0.05 mg' },
    { label: 'Vitamin B2 / Riboflavin', value: '0.15 mg' },
    { label: 'Vitamin B3 / Niacin', value: '2.6 mg' },
    { label: 'Vitamin B6', value: '0.29 mg' },
    { label: 'Vitamin B9 / Folate', value: '25 mcg' },
    { label: 'Vitamin B12', value: '0 mcg' },
    { label: 'Vitamin C', value: '2 mg' },
    { label: 'Vitamin D', value: '0.1 mcg' },
    { label: 'Vitamin E', value: '0 mg' },
  ],
  minerals: [
    { label: 'Calcium', value: '0 mg' },
    { label: 'Sodium', value: '1 mg' },
    { label: 'Potassium', value: '224 mg' },
    { label: 'Magnesium', value: '13 mg' },
    { label: 'Phosphorus', value: '73 mg' },
    { label: 'Iron', value: '0.3 mg' },
    { label: 'Zinc', value: '0.8 mg' },
    { label: 'Selenium', value: '0 mcg' },
    { label: 'Copper', value: '0.14 mg' },
  ],
}

export const NUTRITION_LIONS_MANE_MUSHROOM: NutritionProfile = {
  product: "Fresh Lion's Mane Mushroom",
  referenceProfile: "Raw lion's mane mushroom",
  servingReference: 'Per 100 g raw product',
  dataSource: 'USDA FoodData Central reference data, FDC ID 1750344',
  note: "These are reference values for raw lion's mane mushroom. Final Prozekt-1 pack label values should be confirmed through product lab testing before printing on packaging.",
  nutrients: [
    { label: 'Energy', value: '43 kcal' },
    { label: 'Water', value: '88.6 g' },
    { label: 'Carbohydrates', value: '7.6 g' },
    { label: 'Protein', value: '2.5 g' },
    { label: 'Total fat', value: '0.26 g' },
    { label: 'Sodium', value: '0.34 mg' },
  ],
  vitamins: [
    { label: 'Vitamin B1 / Thiamin', value: '0.15 mg' },
    { label: 'Vitamin B3 / Niacin', value: '1.6 mg' },
    { label: 'Vitamin B6', value: '0.07 mg' },
    { label: 'Vitamin B9 / Folate', value: '29.6 mcg' },
    { label: 'Biotin', value: '16.9 mcg' },
  ],
  minerals: [
    { label: 'Calcium', value: '0 mg' },
    { label: 'Iron', value: '0.69 mg' },
    { label: 'Magnesium', value: '11.7 mg' },
    { label: 'Phosphorus', value: '94 mg' },
    { label: 'Potassium', value: '443 mg' },
    { label: 'Sodium', value: '0.34 mg' },
    { label: 'Zinc', value: '0.74 mg' },
    { label: 'Copper', value: '0.18 mg' },
    { label: 'Manganese', value: '0.18 mg' },
    { label: 'Selenium', value: '1.8 mcg' },
  ],
}
