import { MILKY_MUSHROOM_GHEE_ROAST_IMAGES, MILKY_MUSHROOM_MASALA_CURRY_IMAGES, PINK_OYSTER_65_IMAGES } from '@/assets/Recipe Book'
import type { RecipeData } from '@/types'
import {
  MUSHROOM_RECIPES,
  QUICK_SNACK_RECIPES,
  MICROGREEN_RECIPES,
  EVERYDAY_MEAL_RECIPES,
  HEALTHY_PLATE_RECIPES,
  READY_MEAL_BOX_RECIPES,
  CATERING_RECIPES,
} from './recipe-data'

const ORIGINAL_RECIPES: RecipeData[] = [
  {
    id: 'pink-oyster-65',
    title: 'Pink Oyster Mushroom 65',
    categoryIds: ['quick-snacks', 'mushroom-recipes'],
    primaryCategoryLabel: 'Quick Snacks',
    cookingTime: '25 minutes',
    serves: '2 people',
    thumbnailSrc: PINK_OYSTER_65_IMAGES.thumbnail,
    cards: [
      {
        id: 'nutrition',
        title: 'Goodness of Pink Oyster Mushroom',
        imageSrc: PINK_OYSTER_65_IMAGES.nutrition,
        imageAlt: 'Goodness of Pink Oyster Mushroom',
        contentType: 'nutrition',
        items: [
          'Naturally light and low in fat',
          'Provides plant-based protein',
          'Contains natural dietary fibre',
          'Has useful B vitamins like niacin, riboflavin, thiamin, and folate',
          'Contains minerals such as potassium, phosphorus, magnesium, zinc, and copper',
          'Adds body and bite to food without making the dish feel too heavy',
          'Works well in quick snacks because it cooks fast and absorbs flavour beautifully',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: PINK_OYSTER_65_IMAGES.ingredients,
        imageAlt: 'Ingredients for Pink Oyster Mushroom 65',
        contentType: 'ingredients',
        items: [
          '200 g pink oyster mushrooms',
          '2 tbsp corn flour',
          '2 tbsp rice flour',
          '1 tbsp curd',
          '1 tsp ginger-garlic paste',
          '1 tsp red chilli powder',
          '½ tsp garam masala',
          '¼ tsp turmeric',
          'Curry leaves',
          'Salt as needed',
          'Oil for frying',
          'Lemon and onion slices for serving',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: PINK_OYSTER_65_IMAGES.process,
        imageAlt: 'Making process of Pink Oyster Mushroom 65',
        contentType: 'steps',
        items: [
          'Clean the oyster mushrooms gently.',
          'Tear them into medium bite-sized pieces.',
          'Mix corn flour, rice flour, curd, ginger-garlic paste, chilli powder, turmeric, garam masala, and salt.',
          'Add the mushrooms and coat them lightly.',
          'Keep the coating thin, not like a thick bajji batter.',
          'Heat oil on medium-high flame.',
          'Fry the mushrooms until the outside turns crisp.',
          'Fry curry leaves separately and add them on top.',
          'Serve hot with lemon, onion slices, and chutney.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: PINK_OYSTER_65_IMAGES.howWeMakeIt,
        imageAlt: 'Pink Oyster Mushroom 65 served hot',
        contentType: 'narrative',
        narrative: [
          'When we make Oyster Mushroom 65, we treat the mushroom like the main ingredient, not something to hide inside masala. Pink oyster mushrooms are soft, thin, and delicate, so we usually tear them by hand instead of chopping them hard with a knife. Those uneven torn edges are useful — once they touch hot oil, they crisp up nicely while the inside stays soft.',
          'The coating is where the balance comes in. Corn flour gives the light crisp layer, rice flour adds that slightly rough crunch, and curd helps the masala hold on to the mushroom instead of slipping away into the oil. Ginger-garlic paste gives the base flavour, chilli powder brings the heat, turmeric gives colour, and garam masala adds that familiar starter-style aroma.',
          'We don\'t make this into a thick batter. That is important. If the coating becomes too heavy, the mushroom disappears and the dish starts tasting like fried flour. The idea is to let the mushroom stay visible, soft, and juicy inside, with only a thin spicy jacket outside.',
          'Once the oil is hot, the mushrooms go in carefully. Oyster mushrooms cook fast, so we fry them only until the outside turns crisp. A few fried curry leaves at the end bring that proper South Indian snack smell — the kind that makes people come into the kitchen asking, "What are you making?"',
          'Serve it hot with lemon, onion slices, and chutney. The first bite should be crisp, then spicy, then soft inside. It should feel like a proper evening snack, but still lighter than many regular fried starters.',
        ],
      },
    ],
  },
  {
    id: 'milky-mushroom-masala-curry',
    title: 'Milky Mushroom Masala Curry',
    categoryIds: ['mushroom-recipes', 'everyday-meals'],
    primaryCategoryLabel: 'Mushroom Recipes',
    cookingTime: '30 minutes',
    serves: '3 people',
    thumbnailSrc: MILKY_MUSHROOM_MASALA_CURRY_IMAGES.thumbnail,
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Milky Mushroom',
        imageSrc: MILKY_MUSHROOM_MASALA_CURRY_IMAGES.goodness,
        imageAlt: 'Milky Mushroom sketch',
        contentType: 'nutrition',
        items: [
          'Firm, meaty texture that holds well in curries',
          'Mild taste that absorbs onion-tomato masala beautifully',
          'Adds a satisfying bite without making the curry feel too heavy',
          'Suitable for home-style Indian gravies, fries, roasts, and kurmas',
          'Works well for people trying mushrooms for the first time because the flavour is gentle and familiar with Indian spices',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: MILKY_MUSHROOM_MASALA_CURRY_IMAGES.ingredients,
        imageAlt: 'Ingredients for Milky Mushroom Masala Curry',
        contentType: 'ingredients',
        items: [
          '250 g milky mushrooms',
          '2 medium onions, finely chopped',
          '2 medium tomatoes, finely chopped or pureed',
          '1 green chilli, slit',
          '1 tsp ginger-garlic paste',
          '½ tsp turmeric powder',
          '1 tsp red chilli powder',
          '1½ tsp coriander powder',
          '½ tsp cumin powder',
          '½ tsp garam masala',
          'Curry leaves or coriander leaves',
          'Salt as needed',
          '2 tbsp oil',
          '½ cup water, as needed',
          '1 tbsp curd or fresh cream, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: MILKY_MUSHROOM_MASALA_CURRY_IMAGES.process,
        imageAlt: 'Making Milky Mushroom Masala Curry',
        contentType: 'steps',
        items: [
          'Clean the milky mushrooms gently and trim the hard base if needed.',
          'Cut them into medium pieces.',
          'Heat oil in a pan.',
          'Add onions and green chilli.',
          'Fry until the onions turn soft and lightly golden.',
          'Add ginger-garlic paste and cook until the raw smell reduces.',
          'Add tomatoes, turmeric, chilli powder, coriander powder, cumin powder, and salt.',
          'Cook until the masala thickens and oil starts separating slightly.',
          'Add the milky mushrooms and mix well.',
          'Add a little water, cover, and cook until the mushrooms become tender.',
          'Simmer until the curry reaches a medium-thick consistency.',
          'Add garam masala near the end.',
          'Finish with coriander leaves, curry leaves, or a spoon of curd/cream if preferred.',
          'Serve hot with rice, chapati, dosa, parotta, or pulao.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: MILKY_MUSHROOM_MASALA_CURRY_IMAGES.howWeMakeIt,
        imageAlt: 'Milky Mushroom Masala Curry served hot',
        contentType: 'narrative',
        narrative: [
          'Milky Mushroom Masala Curry is the kind of dish that should feel familiar even to someone cooking mushrooms for the first time. It follows the comfort path of a proper home curry: onions slowly softening in oil, ginger-garlic losing its raw sharpness, tomatoes cooking down into a thick masala, and spices settling into the pan before the mushrooms go in.',
          'We keep the milky mushrooms in medium pieces because this curry needs bite. If they are chopped too small, they disappear into the gravy. If they are too large, the masala stays outside and the mushroom tastes plain inside. Medium pieces give the best balance — soft at the edges, firm in the centre, and nicely coated with the curry.',
          'The masala is the heart of this recipe. Onion gives body, tomato gives slight tang, coriander powder gives warmth, chilli gives heat, and cumin keeps the flavour grounded. We let this base cook properly before adding mushrooms, because raw tomato or half-cooked masala can make the curry taste sharp instead of rounded.',
          'Once the milky mushrooms go in, they release a little moisture and slowly take in the flavour. We add only a small amount of water because this curry should not become thin. The gravy should hold on to the mushrooms, coating them well, almost like every piece has been dressed in the masala.',
          'Garam masala goes near the end so the aroma stays fresh. A spoon of curd or cream can make the curry softer and richer, but it is not compulsory. The final dish should feel warm, homely, and satisfying — firm mushroom pieces sitting in a thick onion-tomato masala, ready for rice, chapati, dosa, or parotta.',
        ],
      },
    ],
  },
  {
    id: 'milky-mushroom-ghee-roast',
    title: 'Milky Mushroom Ghee Roast',
    categoryIds: ['mushroom-recipes', 'everyday-meals'],
    primaryCategoryLabel: 'Mushroom Recipes',
    cookingTime: '25–30 minutes',
    serves: '2–3 people',
    thumbnailSrc: MILKY_MUSHROOM_GHEE_ROAST_IMAGES.thumbnail,
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Milky Mushroom',
        imageSrc: MILKY_MUSHROOM_GHEE_ROAST_IMAGES.goodness,
        imageAlt: 'Milky Mushroom sketch',
        contentType: 'nutrition',
        items: [
          'Firm texture that works well for roasting',
          'Mild flavour that takes spice and ghee beautifully',
          'Gives a satisfying bite without feeling too soft or watery',
          'Holds shape better than many delicate mushrooms',
          'Suitable for dry-style Indian dishes, roasts, fries, and rich side dishes',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: MILKY_MUSHROOM_GHEE_ROAST_IMAGES.ingredients,
        imageAlt: 'Ingredients for Milky Mushroom Ghee Roast',
        contentType: 'ingredients',
        items: [
          '250 g milky mushrooms',
          '2 tbsp ghee',
          '1 medium onion, finely sliced',
          '1 tsp ginger-garlic paste',
          '½ tsp turmeric powder',
          '1 tsp red chilli powder',
          '1 tsp coriander powder',
          '½ tsp black pepper powder',
          '½ tsp garam masala',
          'Curry leaves',
          'Salt as needed',
          '1 tsp lemon juice',
          'Fresh coriander leaves, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: MILKY_MUSHROOM_GHEE_ROAST_IMAGES.process,
        imageAlt: 'Making Milky Mushroom Ghee Roast',
        contentType: 'steps',
        items: [
          'Clean the milky mushrooms gently and trim the hard base if needed.',
          'Cut them into medium pieces.',
          'Heat ghee in a thick pan.',
          'Add curry leaves and sliced onion.',
          'Fry until the onion turns soft and lightly golden.',
          'Add ginger-garlic paste and cook until the raw smell reduces.',
          'Add turmeric, chilli powder, coriander powder, pepper powder, and salt.',
          'Add the milky mushrooms and mix well.',
          'Cook on medium flame until the mushrooms release water.',
          'Continue roasting until the moisture reduces.',
          'Add garam masala near the end.',
          'Roast until the mushrooms look glossy and lightly browned at the edges.',
          'Finish with lemon juice and coriander leaves if preferred.',
          'Serve hot with rice, chapati, dosa, or as a side dish.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: MILKY_MUSHROOM_GHEE_ROAST_IMAGES.howWeMakeIt,
        imageAlt: 'Milky Mushroom Ghee Roast served hot',
        contentType: 'narrative',
        narrative: [
          'Milky Mushroom Ghee Roast is all about letting the mushroom and ghee do their work slowly. This is not a watery curry and not a rushed fry. It should feel roasted, warm, and rich, with the mushrooms coated in spice and ghee instead of floating in gravy.',
          'We keep the milky mushrooms in medium pieces because the dish needs texture. Milky mushroom has a firm bite, and that is what makes it good for a ghee roast. If the pieces are too small, they dry out quickly. If they are too big, the masala stays only on the outside. Medium pieces give that nice balance where the outside gets roasted and the inside stays soft.',
          'The ghee goes in first, followed by curry leaves and onion. This gives the base its smell — rich, slightly sweet, and familiar. Once the onion softens, ginger-garlic paste goes in and cooks down. We do not want raw garlic sitting on the mushroom, so we give it a little time before adding the spices.',
          'The spice mix is simple: chilli for heat, coriander for body, turmeric for colour, and pepper for warmth. When the mushrooms go in, they release moisture first. That is normal. The important part is to keep cooking until that water reduces. This is where the dish changes from "mushroom in masala" to "mushroom roast."',
          'Near the end, garam masala gives aroma, and the ghee starts coating the mushroom pieces properly. The edges should look slightly roasted, not burnt. A little lemon juice at the end cuts through the richness and makes the whole dish feel brighter.',
          'The final bite should be warm, spicy, buttery, and firm. It should feel like a proper side dish that can stand next to rice, dosa, chapati, or even a simple curd rice plate without needing anything else.',
        ],
      },
    ],
  },
]

export const RECIPES: RecipeData[] = [
  ...ORIGINAL_RECIPES,
  ...MUSHROOM_RECIPES,
  ...QUICK_SNACK_RECIPES,
  ...MICROGREEN_RECIPES,
  ...EVERYDAY_MEAL_RECIPES,
  ...HEALTHY_PLATE_RECIPES,
  ...READY_MEAL_BOX_RECIPES,
  ...CATERING_RECIPES,
]
