import { PINK_OYSTER_65_IMAGES } from '@/assets/Recipe Book'
import type { RecipeData } from '@/types'

export const RECIPES: RecipeData[] = [
  {
    id: 'pink-oyster-65',
    title: 'Pink Oyster Mushroom 65',
    categoryIds: ['quick-snacks', 'mushroom-recipes'],
    primaryCategoryLabel: 'Quick Snacks',
    cookingTime: '25 minutes',
    serves: '2 people',
    thumbnailSrc: PINK_OYSTER_65_IMAGES.thumbnail,
    cards: [
      {
        id: 'nutrition',
        title: 'Nutrition Benefits',
        imageSrc: PINK_OYSTER_65_IMAGES.nutrition,
        imageAlt: 'Nutrition benefits of Pink Oyster Mushroom',
        contentType: 'nutrition',
        items: [
          'Oyster mushrooms are naturally light and low in fat, making them easy to include in everyday meals.',
          'They provide dietary fibre, which helps make the dish feel more satisfying than a plain fried snack.',
          'They contain some plant-based protein and can be used as part of a balanced vegetarian meal.',
          'Oyster mushrooms contain naturally occurring mushroom fibres such as beta-glucans and chitin.',
          'They provide small but useful amounts of minerals and B vitamins, depending on freshness, growing conditions, and cooking method.',
          'Mushrooms are known food sources of ergothioneine, a naturally occurring antioxidant compound.',
          'Since this recipe is fried, the mushroom itself is nutritious, but the final dish depends on how much oil and coating is used.',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: PINK_OYSTER_65_IMAGES.ingredients,
        imageAlt: 'Ingredients for Pink Oyster Mushroom 65',
        contentType: 'ingredients',
        items: [
          '200 g pink oyster mushrooms',
          '2 tbsp corn flour',
          '2 tbsp rice flour',
          '1 tbsp curd',
          '1 tsp ginger-garlic paste',
          '1 tsp red chilli powder',
          '½ tsp garam masala',
          '¼ tsp turmeric',
          'Curry leaves',
          'Salt as needed',
          'Oil for frying',
          'Lemon and onion slices for serving',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: PINK_OYSTER_65_IMAGES.process,
        imageAlt: 'Making process of Pink Oyster Mushroom 65',
        contentType: 'steps',
        items: [
          'Clean the oyster mushrooms gently.',
          'Tear them into medium bite-sized pieces.',
          'Mix corn flour, rice flour, curd, ginger-garlic paste, chilli powder, turmeric, garam masala, and salt.',
          'Add the mushrooms and coat them lightly.',
          'Keep the coating thin, not like a thick bajji batter.',
          'Heat oil on medium-high flame.',
          'Fry the mushrooms until the outside turns crisp.',
          'Fry curry leaves separately and add them on top.',
          'Serve hot with lemon, onion slices, and chutney.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: PINK_OYSTER_65_IMAGES.howWeMakeIt,
        imageAlt: 'Pink Oyster Mushroom 65 served hot',
        contentType: 'narrative',
        narrative: [
          'When we make Oyster Mushroom 65, the first thing we care about is not breaking the mushroom too much. Oyster mushrooms are soft, thin, and delicate, so we usually tear them by hand instead of cutting them with pressure. That gives uneven edges, and those edges become crisp when they touch hot oil.',
          'The coating is kept simple. Corn flour gives that light crisp outer layer, while rice flour adds a slightly rough crunch. Curd helps the masala stick to the mushroom instead of falling off in the oil. Ginger-garlic paste gives the base flavour, chilli powder brings the heat, turmeric gives colour, and garam masala gives the familiar starter-style aroma.',
          'The mixture should not become a thick batter. It should only coat the mushrooms lightly. If the coating becomes too thick, the mushroom disappears inside the flour, and the dish starts feeling heavy. The best version should still taste like mushroom inside — crisp outside, soft inside.',
          'We fry them in hot oil until the outside turns crisp. Oyster mushrooms cook quickly, so they do not need too much time. At the end, we add fried curry leaves for that warm South Indian snack smell. Serve it hot with lemon, onion slices, and chutney. The first bite should feel crisp, then spicy, then soft and juicy inside.',
        ],
      },
    ],
  },
]
