import type { RecipeData } from '@/types'
import {
  NUTRITION_BUTTON_MUSHROOM_USDA,
  NUTRITION_OYSTER_MUSHROOM_USDA,
} from '@/constants/NUTRITION_PROFILES'

export const CATERING_RECIPES: RecipeData[] = [
  {
    id: 'milky-mushroom-miriyala-vepudu-tray',
    title: 'Milky Mushroom Miriyala Vepudu Tray',
    categoryIds: ['catering-restaurant', 'mushroom-recipes'],
    primaryCategoryLabel: 'Catering & Restaurant',
    cookingTime: '30 minutes (scales well for large batches)',
    serves: '6–8 people per tray',
    cards: [
      {
        id: 'goodness',
        title: 'Why this dish works for catering',
        contentType: 'nutrition',
        items: [
          'Milky Mushroom Miriyala Vepudu is a dry pepper fry that holds its texture and flavour for 2–3 hours in a tray, making it ideal for buffets and event service',
          'Dry preparations travel better than gravy dishes for catering because they do not spill or separate',
          'The bold pepper (miriyala) flavour makes it stand out at a buffet spread without needing heavy saucing',
          'Milky mushrooms are available in large quantities from Prozekt-1, making them a reliable catering ingredient',
          'This dish reheats well and can be made in large batches without losing quality',
          'It is a plant-based option that works as a strong standalone dish, not just as a side',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients (for 6–8 servings)',
        contentType: 'ingredients',
        items: [
          '600g Milky Mushrooms, cut into large pieces',
          '3 large onions, thinly sliced',
          '3 sprigs curry leaves',
          '6–8 dry red chillies',
          '2 tbsp black peppercorns, coarsely crushed',
          '1 tsp cumin seeds',
          '1 tbsp ginger-garlic paste',
          '1 tsp turmeric powder',
          '1 tsp red chilli powder',
          '3 tbsp oil',
          'Salt as needed',
          'Lemon juice to finish',
          'Fresh coriander for garnish',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        contentType: 'steps',
        items: [
          'Cut milky mushrooms into large, uniform pieces.',
          'Heat oil in a large, wide pan.',
          'Add cumin seeds, dry red chillies, and curry leaves.',
          'Add sliced onions and cook until golden brown and reduced in volume.',
          'Add ginger-garlic paste.',
          'Add turmeric, red chilli powder, and salt.',
          'Add milky mushroom pieces and toss well.',
          'Cook on high heat initially to sear and evaporate moisture.',
          'Reduce to medium and cook until mushrooms are dry and well-coated.',
          'Add coarsely crushed black pepper and toss through.',
          'Finish with lemon juice and coriander.',
          'Transfer to serving tray.',
          'For buffet: cover loosely with foil to retain some warmth without trapping steam.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It for Events',
        contentType: 'narrative',
        narrative: [
          'Milky Mushroom Miriyala Vepudu Tray is one of our most reliable catering preparations. The Telugu name Miriyala Vepudu means pepper fry — a dry, aromatic stir-fry that is deeply seasoned with black pepper.',
          'For catering quantities, we use wide, flat pans and cook in batches if needed. The key is high heat for the initial cook to drive out moisture quickly. Mushrooms cooked on low heat for too long become soft and lose the dry, slightly crispy edge that makes this dish distinctive.',
          'The onion base is cooked until deeply golden — almost at the point where it starts caramelising. This takes time but gives the masala its rich foundation.',
          'Black pepper is added near the end. When it goes in early, it loses its sharp character in the cooking. Added late, it retains its heat and aroma.',
          'In a tray format for events, this dish holds well for 2–3 hours under loose foil. It can be refreshed quickly with a few drops of lemon juice and a toss before serving.',
          'This is a flagship dish for mushroom-forward catering menus and works equally well as a main or a substantial side.',
        ],
      },
    ],
  },
  {
    id: 'milky-mushroom-karam-roast-tray',
    title: 'Milky Mushroom Karam Roast Tray',
    categoryIds: ['catering-restaurant', 'mushroom-recipes'],
    primaryCategoryLabel: 'Catering & Restaurant',
    cookingTime: '30 minutes (scales for large batches)',
    serves: '6–8 people per tray',
    cards: [
      {
        id: 'goodness',
        title: 'Why this dish works for catering',
        contentType: 'nutrition',
        items: [
          'Karam roast is a bold, spicy preparation that creates strong flavour impact at a buffet without needing gravy or sauce',
          'Milky mushrooms are firm enough to hold their shape through a high-heat roast process, making them suitable for a large tray preparation',
          'The karam (spice powder) coating dries on the mushroom surface, creating a slightly crust-like finish that stays appealing for longer',
          'This dish is vegetarian and plant-based, making it inclusive for mixed dietary groups at events',
          'The spice blend can be adjusted in intensity to suit the audience, from mildly spiced to very bold',
          'It pairs well with rice, biryani, roti, or as a standalone appetiser at events',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients (for 6–8 servings)',
        contentType: 'ingredients',
        items: [
          '600g Milky Mushrooms, cut into large pieces',
          '3 tbsp karam powder (Andhra-style spice mix) or red chilli-garlic powder blend',
          '2 large onions, thinly sliced',
          '1 tbsp ginger-garlic paste',
          '1 tsp turmeric powder',
          '½ tsp cumin powder',
          '1 tsp coriander powder',
          'Curry leaves, 2 sprigs',
          '4 dry red chillies',
          '3 tbsp oil',
          'Salt as needed',
          'Lemon juice to finish',
          'Fresh coriander for garnish',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        contentType: 'steps',
        items: [
          'Cut milky mushrooms into large, consistent pieces.',
          'Mix karam powder, turmeric, cumin, coriander, ginger-garlic paste, salt, and 1 tbsp oil.',
          'Toss the mushroom pieces in this dry marinade.',
          'Rest for 20–30 minutes if time allows.',
          'Heat remaining oil in a wide, flat pan on high heat.',
          'Add dry red chillies and curry leaves.',
          'Add marinated mushroom pieces in a single layer.',
          'Do not move them for 2–3 minutes to develop a crust.',
          'Flip and cook the other side.',
          'Add sliced onions and toss through at the end.',
          'Cook until onions are soft and mushrooms are well-roasted.',
          'Finish with lemon juice and coriander.',
          'Transfer to serving tray and keep covered loosely.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It for Events',
        contentType: 'narrative',
        narrative: [
          'Milky Mushroom Karam Roast is an Andhra-inspired preparation that uses karam powder as its main seasoning. Karam is a blend of red chilli, garlic, and roasted spices that gives Andhra cooking its distinctive bold heat.',
          'For catering, we marinate the mushrooms in the karam mix and a little oil before cooking. This marinade creates a dry coating that sticks to the mushroom surface and forms a flavour crust during the high-heat roasting.',
          'The roasting step is done on maximum heat in batches if the volume is very large. Each batch should be in a single layer in the pan. Stacking mushrooms prevents the crust from forming and causes steam-cooking instead of roasting.',
          'Onions are added near the end, not at the beginning. Onions cooked too early would become very soft and lose their texture. Added near the end, they remain soft but not mushy.',
          'For large events, we prepare and roast the mushrooms in batches, then combine everything in the serving tray and refresh briefly with heat before service.',
        ],
      },
    ],
  },
  {
    id: 'button-mushroom-cashew-masala-fry',
    title: 'Button Mushroom Cashew Masala Fry',
    categoryIds: ['catering-restaurant', 'mushroom-recipes'],
    primaryCategoryLabel: 'Catering & Restaurant',
    cookingTime: '30 minutes',
    serves: '6–8 people per tray',
    nutritionProfiles: [NUTRITION_BUTTON_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Why this dish works for catering',
        contentType: 'nutrition',
        items: [
          'Cashew and mushroom together bring a premium feel to the catering menu because both are considered high-quality ingredients',
          'Button mushrooms hold their compact shape in a masala fry, making each serving look generous and neat',
          'Cashews add richness and crunch that elevate a mushroom dish to restaurant or special event quality',
          'This preparation works well as a main dish for vegetarian guests at weddings, corporate events, and celebrations',
          'It can be served over rice, biryani, chapati, or as a standalone fry alongside a meal',
          'The masala is rich but dry, making it a good buffet preparation that does not spill or pool on the serving plate',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients (for 6–8 servings)',
        contentType: 'ingredients',
        items: [
          '500g Button Mushrooms, halved',
          '150g whole cashews',
          '3 large onions, finely chopped',
          '3 tomatoes, finely chopped or pureed',
          '1 tbsp ginger-garlic paste',
          '1½ tsp red chilli powder',
          '½ tsp turmeric powder',
          '1 tsp coriander powder',
          '½ tsp cumin powder',
          '1 tsp garam masala',
          '2 tbsp oil',
          'Salt as needed',
          'Fresh coriander for garnish',
          '1 tsp kasuri methi, crushed',
          '1 tbsp cream, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        contentType: 'steps',
        items: [
          'Lightly fry the cashews in a little oil until golden. Set aside.',
          'Heat remaining oil in a pan.',
          'Add onions and cook until golden brown.',
          'Add ginger-garlic paste.',
          'Add tomatoes and cook until the masala is dry and oil separates.',
          'Add turmeric, red chilli, coriander, cumin, and salt.',
          'Add button mushrooms and cook for 5–6 minutes.',
          'Add fried cashews and gently mix.',
          'Cook for 2–3 more minutes.',
          'Add garam masala and kasuri methi.',
          'Add cream if using.',
          'Garnish with coriander and serve.',
          'For catering, transfer to a wide serving tray and keep covered.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It for Events',
        contentType: 'narrative',
        narrative: [
          'Button Mushroom Cashew Masala Fry is designed for occasions when the vegetarian dish on the menu needs to feel as premium as the non-vegetarian options. Cashews elevate this dish both in taste and in perception.',
          'The cashews are fried separately first. This is important because cashews added directly to a wet masala will become soggy and lose their crunch. Separately fried cashews are added near the end and stay crispy.',
          'The onion-tomato masala is cooked down until completely dry and the oil separates. This long-cooked, concentrated masala is what gives the dish its depth. Rushing this step results in a raw, thin-tasting masala.',
          'Button mushrooms are compact and hold their shape well in a dry masala preparation, making each serving look generous on the plate.',
          'Kasuri methi at the end gives the dish that restaurant-finish aroma. A small amount of cream makes the masala slightly glossy and rich if a more indulgent version is needed.',
        ],
      },
    ],
  },
  {
    id: 'mushroom-peanut-karam-fry',
    title: 'Mushroom Peanut Karam Fry',
    categoryIds: ['catering-restaurant', 'mushroom-recipes'],
    primaryCategoryLabel: 'Catering & Restaurant',
    cookingTime: '25 minutes',
    serves: '6–8 people per tray',
    cards: [
      {
        id: 'goodness',
        title: 'Why this dish works for catering',
        contentType: 'nutrition',
        items: [
          'Peanut karam fry is bold, fragrant, and practical — it scales easily and holds well in a buffet tray',
          'Roasted peanuts add crunch and a nutty warmth that balances the spicy karam coating on the mushroom',
          'This preparation suits Telugu-style catering menus and works beautifully as a rice side or biryani accompaniment',
          'Both mushroom and peanut are cost-effective catering ingredients that deliver strong flavour impact',
          'The dry fry format means no gravy to manage, no risk of spilling, and easy serving at events',
          'It suits a wide range of audiences, including people who want bold South Indian flavours',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients (for 6–8 servings)',
        contentType: 'ingredients',
        items: [
          '500g Milky or Button Mushrooms, cut into large pieces',
          '100g roasted peanuts',
          '2 large onions, thinly sliced',
          '2 tbsp karam powder or red chilli-garlic blend',
          '1 tbsp ginger-garlic paste',
          '1 tsp turmeric powder',
          '½ tsp cumin seeds',
          '2 sprigs curry leaves',
          '4 dry red chillies',
          '3 tbsp oil',
          'Salt as needed',
          'Lemon juice to finish',
          'Fresh coriander for garnish',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        contentType: 'steps',
        items: [
          'Cut mushrooms into large, consistent pieces.',
          'Heat oil in a wide pan on high heat.',
          'Add cumin seeds, dry red chillies, and curry leaves.',
          'Add onions and cook until golden.',
          'Add ginger-garlic paste and turmeric.',
          'Add mushrooms and cook on high heat until moisture evaporates.',
          'Add karam powder and salt.',
          'Toss well and cook until the mushrooms are dry and coated.',
          'Add roasted peanuts and toss through.',
          'Finish with lemon juice and coriander.',
          'Transfer to serving tray.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It for Events',
        contentType: 'narrative',
        narrative: [
          'Mushroom Peanut Karam Fry is a catering dish built for Telugu and Andhra-style event menus. It is bold, practical, and popular.',
          'The peanuts go in near the end — not at the beginning. They should stay crunchy on the serving tray. If added too early, they absorb moisture from the mushrooms and become soft.',
          'High heat is essential. Mushrooms cooked on low heat in a catering context release water and simmer rather than fry. In large batches, we work in sections, cooking the mushrooms on high heat in a large flat pan or a tawa.',
          'Karam powder intensity can be adjusted based on the audience. For a mild crowd, we reduce the karam and increase the cumin and coriander. For a heat-loving audience, we keep the original bold proportion.',
          'This dish pairs naturally with plain rice, biryani, or chapati and is suitable as both a main dish and a side in a larger catering spread.',
        ],
      },
    ],
  },
  {
    id: 'mushroom-65-live-counter',
    title: 'Mushroom 65 Live Counter',
    categoryIds: ['catering-restaurant', 'mushroom-recipes', 'quick-snacks'],
    primaryCategoryLabel: 'Catering & Restaurant',
    cookingTime: '25 minutes per batch',
    serves: 'Live counter for 30–50 people',
    nutritionProfiles: [NUTRITION_OYSTER_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Why this works as a live counter',
        contentType: 'nutrition',
        items: [
          'Mushroom 65 is best served immediately from the fryer — a live counter ensures the highest quality because guests get freshly fried mushroom every time',
          'Oyster or milky mushrooms used for a 65 hold their structure well during deep frying even in large batches',
          'The live counter format creates theatre at events — the sizzle, the aroma, and the sight of fresh frying attracts attention and creates anticipation',
          'Mushroom 65 is a crowd favourite that works for all age groups, making it a safe and popular choice for large events',
          'The recipe is simple to scale and the ingredients are straightforward to prep in advance before live service',
          'A live counter presentation signals freshness and quality, which elevates the event food experience',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients (base prep for live counter)',
        contentType: 'ingredients',
        items: [
          '1–2 kg Oyster or Milky Mushrooms, torn or cut into serving-sized pieces',
          'Marinade: thick curd, cornflour, rice flour, red chilli powder, kashmiri chilli, garam masala, cumin powder, ginger-garlic paste, lemon juice, salt',
          'Oil for deep frying',
          'Live garnish: curry leaves, slit green chillies (fried fresh per batch)',
          'Lemon wedges for serving',
          'Green chutney for serving',
          'Paper cones or small plates for serving',
          'Chaat masala for finishing',
        ],
      },
      {
        id: 'process',
        title: 'Counter Setup & Process',
        contentType: 'steps',
        items: [
          'Pre-marinate mushrooms in bulk 1–2 hours before service.',
          'Set up a deep fryer or large kadai with oil to correct temperature (175–180°C).',
          'Keep marinated mushrooms in a covered tray at the counter.',
          'Fry in small batches (enough for 4–6 servings) every few minutes.',
          'Add curry leaves and green chillies to oil for each batch.',
          'Drain and sprinkle chaat masala immediately.',
          'Serve in paper cones with lemon and chutney.',
          'Maintain oil temperature between batches.',
          'Replace oil when it darkens or develops an off smell.',
          'Keep the counter station clean and refill mushroom tray as needed.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Run It at Events',
        contentType: 'narrative',
        narrative: [
          'Mushroom 65 Live Counter is one of the most engaging event food stations we can set up. Guests see the mushrooms frying, smell the curry leaves and chilli sizzling, and get a fresh portion in their hand within seconds. This is the experience that makes a live counter different from a buffet tray.',
          'The mushrooms are pre-marinated before the event, so the counter team only needs to fry during service. This pre-prep step means the counter can run smoothly without any seasoning or mixing happening live.',
          'We fry in small batches deliberately. Small batches keep the oil temperature stable and ensure each portion is uniformly golden. Large batches can drop the oil temperature and result in greasy, unevenly cooked mushrooms.',
          'Curry leaves and green chillies are dropped into the oil fresh for every few batches. They add their aroma to the oil and garnish the mushroom naturally.',
          'Paper cones are the serving format of choice for live counters — they are hygienic, easy to hold, and look attractive.',
          'For events of 50–100 people, we recommend 1–1.5 kg of mushrooms per hour of service, with enough oil and a reliable fryer that can maintain temperature.',
        ],
      },
    ],
  },
  {
    id: 'milky-mushroom-pakoda-platter',
    title: 'Milky Mushroom Pakoda Platter',
    categoryIds: ['catering-restaurant', 'mushroom-recipes', 'quick-snacks'],
    primaryCategoryLabel: 'Catering & Restaurant',
    cookingTime: '35 minutes per batch',
    serves: '20–25 servings per platter',
    cards: [
      {
        id: 'goodness',
        title: 'Why this works as a catering platter',
        contentType: 'nutrition',
        items: [
          'Milky mushroom pakoda in large platters is a crowd-pleasing starter that works for all event types',
          'The firm texture of milky mushroom means pakodas hold their shape on a large serving platter without crumbling or becoming soft too quickly',
          'Pakoda can be made slightly ahead of service and reheated briefly in the oven to restore crispness',
          'This is a vegetarian starter that appeals equally to vegetarian and non-vegetarian guests',
          'Milky mushroom pakoda can be made in large quantities efficiently and consistently',
          'The serving platter format is visually generous and suits the Indian banquet tradition of abundant starters',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients (for 20–25 servings)',
        contentType: 'ingredients',
        items: [
          '1 kg Milky Mushrooms, sliced or torn into large pieces',
          '2 cups besan (gram flour)',
          '4 tbsp rice flour',
          '2 tsp red chilli powder',
          '1 tsp turmeric powder',
          '1 tsp cumin seeds',
          '1 tsp black pepper powder',
          '1 tsp garam masala',
          '2 tbsp hot oil (for batter)',
          'Salt as needed',
          'Water as needed for thick batter',
          'Oil for deep frying',
          'Curry leaves for frying',
          'Slit green chillies for frying',
          'Chaat masala for finishing',
          'Green chutney and tamarind chutney for serving',
          'Onion rings and lemon wedges for plating',
        ],
      },
      {
        id: 'process',
        title: 'Process for Catering Quantities',
        contentType: 'steps',
        items: [
          'Prepare a large batch of besan batter with all spices.',
          'Add 2 tbsp hot oil to the batter for crispness.',
          'Pat mushroom pieces dry in batches.',
          'Dip in batter and fry in large oil batches at 175°C.',
          'Fry until golden brown and drain in batches.',
          'For catering pre-prep: fry at 80% crispness, drain, and store on trays.',
          'Re-fry or oven-crisp at 200°C for 5 minutes just before plating.',
          'Add fresh curry leaves and green chillies to the final batch.',
          'Plate on large serving platters generously.',
          'Sprinkle chaat masala over the platter.',
          'Add onion rings, lemon wedges, and chutney accompaniments.',
          'Serve immediately.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It for Events',
        contentType: 'narrative',
        narrative: [
          'Milky Mushroom Pakoda Platter is a catering staple. When served on a large brass or stainless steel platter with onion rings, lemon wedges, and chutneys, it looks generous and traditional — the way a good Indian banquet starter should look.',
          'For events, we use a two-stage frying approach. The first fry (at 80% crispness) happens in the kitchen 30–60 minutes before service. The second quick fry or oven re-crisp happens right before the platters go out. This method ensures crispy pakoda at serving time without continuous live frying during the event.',
          'The batter consistency is the most important variable at scale. Too thick and the batter-to-mushroom ratio becomes heavy. Too thin and the coating slides off during frying. We use a batter that coats the mushroom fully but still lets you see the shape of the mushroom underneath.',
          'Hot oil (2 tbsp) added to the batter before dipping helps the pakoda stay crispy for longer, even on a platter.',
          'For events of 100 people, we plan 1 kg of mushrooms per 20–25 servings, with 2–3 chutney choices and a bed of fresh onion rings under the pakodas on the platter.',
        ],
      },
    ],
  },
  {
    id: 'mushroom-cutlet-party-platter',
    title: 'Mushroom Cutlet Party Platter',
    categoryIds: ['catering-restaurant', 'mushroom-recipes', 'quick-snacks'],
    primaryCategoryLabel: 'Catering & Restaurant',
    cookingTime: '45 minutes per batch',
    serves: '20–25 cutlets per batch',
    nutritionProfiles: [NUTRITION_OYSTER_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Why this works as a catering platter',
        contentType: 'nutrition',
        items: [
          'Mushroom cutlets are one of the most universally liked starters — children, adults, vegetarians, and non-vegetarians all enjoy them',
          'Cutlets can be made fully in advance and shallow-fried in batches close to serving time',
          'Their uniform shape makes platter presentation clean and professional',
          'Oyster mushroom cutlets have a satisfying bite and a flavour that feels meaty and complete',
          'Cutlets stay appealing on a platter for 30–40 minutes, longer than many other fried starters',
          'They pair with multiple chutney options and are easy to pick up and eat at standing events',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients (for 20–25 cutlets)',
        contentType: 'ingredients',
        items: [
          '500g Oyster Mushrooms, finely chopped or shredded',
          '4 medium potatoes, boiled and mashed',
          '2 onions, finely chopped',
          '2 green chillies, finely chopped',
          '1 tbsp ginger-garlic paste',
          '1½ tsp red chilli powder',
          '1 tsp cumin powder',
          '1 tsp garam masala',
          '1 tsp coriander powder',
          'Salt as needed',
          '4 tbsp cornflour',
          'Breadcrumbs for coating',
          'Oil for shallow frying',
          'Fresh coriander leaves',
          'Chaat masala for finishing',
          'Green chutney and ketchup for serving',
        ],
      },
      {
        id: 'process',
        title: 'Process for Catering Quantities',
        contentType: 'steps',
        items: [
          'Shred or finely chop the oyster mushrooms.',
          'Cook mushrooms in a dry pan until all moisture is gone.',
          'Add oil, onions, and ginger-garlic paste.',
          'Cook until onions are soft.',
          'Add all spices and cook until completely dry.',
          'Combine with mashed potato, cornflour, and coriander.',
          'Mix well and shape into uniform oval or round cutlets.',
          'Coat all cutlets in breadcrumbs.',
          'For pre-prep: refrigerate shaped cutlets on trays for up to 4 hours.',
          'Shallow fry in batches close to serving time.',
          'Drain and finish with chaat masala.',
          'Arrange on large serving platter with chutney and garnish.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It for Events',
        contentType: 'narrative',
        narrative: [
          'Mushroom Cutlet Party Platter is one of the most practical catering preparations in our collection. The cutlets can be shaped and refrigerated hours before an event, then shallow-fried to order. This advance preparation is what makes them viable for large events without requiring a large kitchen team to be active throughout service.',
          'The most important rule in a large cutlet batch is making sure the filling is completely dry. Even a small amount of residual moisture in the mushroom-potato mix will cause the cutlets to crack during frying. We cook the mushroom filling thoroughly until it forms a dry, slightly sticky mass before combining with potato.',
          'Uniform shaping matters for a platter. We use a small ring mould or a spoon-and-hand method to shape each cutlet to approximately the same size. Uniform cutlets look professional on a platter and fry at the same rate.',
          'For events of 50 guests, we plan 2–3 cutlets per person, meaning 100–150 cutlets in total. At that scale, we divide the prep into 4–5 batches and fry in rotation close to service time.',
          'The platter is finished with fresh coriander, chaat masala, and two chutney options. A clean, neatly arranged platter with visible colour from the chutneys and garnish signals quality and care.',
        ],
      },
    ],
  },
]
