import type { RecipeData } from '@/types'
import {
  NUTRITION_BUTTON_MUSHROOM_USDA,
  NUTRITION_OYSTER_MUSHROOM_USDA,
} from '@/constants/NUTRITION_PROFILES'

export const EVERYDAY_MEAL_RECIPES: RecipeData[] = [
  {
    id: 'milky-mushroom-pulao',
    title: 'Milky Mushroom Pulao',
    categoryIds: ['everyday-meals', 'mushroom-recipes'],
    primaryCategoryLabel: 'Everyday Meals',
    cookingTime: '30 minutes',
    serves: '3–4 people',
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Milky Mushroom in this recipe',
        contentType: 'nutrition',
        items: [
          'Milky mushrooms have a firm texture that holds its shape during rice cooking, so they don\'t disappear into the dish',
          'Their mild flavour absorbs the spice and rice aromas well, giving each bite a satisfying mushroom taste',
          'They bring a natural umami depth to the pulao without needing meat stock or heavy masala',
          'Milky mushrooms cook at about the same pace as rice when added at the right time, making timing straightforward',
          'This recipe makes a complete one-pot meal that needs only a simple raita or papad on the side',
          'Using mushroom instead of paneer or potato in a pulao creates a lighter dish that still feels hearty and filling',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        contentType: 'ingredients',
        items: [
          '250g Milky Mushrooms, sliced',
          '1½ cups basmati rice, soaked for 20 minutes',
          '1 large onion, thinly sliced',
          '2 tomatoes, chopped',
          '1 tsp ginger-garlic paste',
          '2 green chillies, slit',
          '1 tsp red chilli powder',
          '½ tsp turmeric powder',
          '1 tsp garam masala',
          '½ tsp coriander powder',
          'Whole spices: 1 bay leaf, 4 cloves, 2 cardamom, 1 small cinnamon stick',
          '2 tbsp oil or ghee',
          'Salt as needed',
          '2¾ cups water',
          'Fresh coriander and mint for garnish',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        contentType: 'steps',
        items: [
          'Soak basmati rice for 20 minutes and drain.',
          'Heat oil or ghee in a heavy pot.',
          'Add whole spices and let them splutter.',
          'Add sliced onion and cook until golden brown.',
          'Add ginger-garlic paste and green chillies.',
          'Add tomatoes and cook until soft.',
          'Add red chilli powder, turmeric, coriander powder, and salt.',
          'Add milky mushroom slices and cook for 3–4 minutes.',
          'Add drained rice and gently mix.',
          'Add water, check salt.',
          'Bring to a boil, then reduce heat, cover and cook for 15 minutes.',
          'Rest covered for 5 minutes before opening.',
          'Add garam masala, garnish with coriander and mint.',
          'Serve hot with raita.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Milky Mushroom Pulao is a one-pot meal that makes everyday rice feel more interesting. Milky mushrooms are ideal for pulao because they stay firm and don\'t break down during cooking.',
          'We start by browning the onions well. Golden brown onions are the foundation of the flavour. Under-cooked onions will make the pulao taste raw and flat.',
          'The mushrooms go in after the masala base is ready. We give them a few minutes to cook into the spice base before adding rice. This pre-cooking step ensures the mushrooms absorb the masala flavour rather than just sitting in the rice.',
          'The water ratio for soaked basmati is roughly 1:1.8. After the pulao comes to a boil, we reduce to low heat and cook covered. The rest period with the lid on is important — the steam inside continues cooking the rice and settles the dish.',
          'A simple raita or plain curd with papad is all this pulao needs beside it.',
        ],
      },
    ],
  },
  {
    id: 'button-mushroom-tomato-rice',
    title: 'Button Mushroom Tomato Rice',
    categoryIds: ['everyday-meals', 'mushroom-recipes'],
    primaryCategoryLabel: 'Everyday Meals',
    cookingTime: '25 minutes',
    serves: '2–3 people',
    nutritionProfiles: [NUTRITION_BUTTON_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Button Mushroom in this recipe',
        contentType: 'nutrition',
        items: [
          'Button mushrooms have a compact size that distributes evenly throughout rice, so every spoonful has mushroom in it',
          'Their mild umami taste pairs naturally with tangy tomato and spiced onion to create a balanced rice dish',
          'They cook quickly once sliced, making this a practical everyday recipe for busy home cooking',
          'Button mushrooms bring depth to a simple tomato rice without making it feel heavy',
          'This recipe is a good everyday option because button mushrooms are widely available and affordable',
          'The mushroom and tomato combination creates a sauce-like texture in the rice that makes it satisfying without needing a separate curry',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        contentType: 'ingredients',
        items: [
          '200g Button Mushrooms, quartered',
          '2 cups cooked rice',
          '2 tomatoes, finely chopped',
          '1 onion, finely chopped',
          '2 green chillies, slit',
          '1 tsp ginger-garlic paste',
          '½ tsp turmeric powder',
          '1 tsp red chilli powder',
          '½ tsp coriander powder',
          '¼ tsp garam masala',
          'Salt as needed',
          '2 tbsp oil',
          'Curry leaves',
          'Fresh coriander for garnish',
          '1 tsp lemon juice',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        contentType: 'steps',
        items: [
          'Heat oil in a wide pan.',
          'Add curry leaves, onion, and green chillies.',
          'Cook until onion is soft and lightly golden.',
          'Add ginger-garlic paste.',
          'Add tomatoes and cook until they break down and the oil separates.',
          'Add turmeric, red chilli powder, coriander powder, and salt.',
          'Add button mushrooms and cook until tender, about 5 minutes.',
          'Add cooked rice and gently fold everything together.',
          'Cook for 2–3 more minutes on medium heat.',
          'Finish with garam masala and lemon juice.',
          'Garnish with fresh coriander.',
          'Serve hot with papad or raita.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Button Mushroom Tomato Rice is the kind of recipe that turns leftover cooked rice into a proper meal in 25 minutes. It uses simple ingredients that most kitchens already have.',
          'The tomato base is the heart of this dish. We cook the tomatoes until they fully break down and the oil separates from them. This is the sign that the masala is ready. Under-cooked tomato makes the rice taste acidic and unfinished.',
          'Button mushrooms go in next and cook quickly. They absorb the masala and become part of the sauce-like base that will coat the rice.',
          'We use cooked rice that has cooled slightly. Hot freshly cooked rice can become mushy when stirred with a wet masala. Slightly cooled rice holds its grain structure better.',
          'Lemon juice at the end brightens the entire dish and balances the richness of the tomato-mushroom masala.',
        ],
      },
    ],
  },
  {
    id: 'oyster-mushroom-lemon-rice',
    title: 'Oyster Mushroom Lemon Rice',
    categoryIds: ['everyday-meals', 'mushroom-recipes'],
    primaryCategoryLabel: 'Everyday Meals',
    cookingTime: '20 minutes',
    serves: '2–3 people',
    nutritionProfiles: [NUTRITION_OYSTER_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Oyster Mushroom in this recipe',
        contentType: 'nutrition',
        items: [
          'Oyster mushrooms have a naturally light texture that suits lemon rice, which is a fresh and bright dish',
          'Their mild taste does not fight with the lemon and turmeric flavours that define lemon rice',
          'Quick-cooking oyster mushrooms can be added to the tempering stage without needing separate preparation',
          'They bring an earthy, savoury depth to lemon rice that makes it feel like more than a plain seasoned rice',
          'Oyster mushrooms absorb the lemon-turmeric oil base well, so they taste seasoned through, not just coated on the outside',
          'This recipe is a good way to use oyster mushrooms in an everyday South Indian rice format that is already familiar',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        contentType: 'ingredients',
        items: [
          '150g Oyster Mushrooms, torn into medium pieces',
          '2 cups cooked rice, cooled',
          '2 tbsp lemon juice',
          '½ tsp turmeric powder',
          'Salt as needed',
          '2 tbsp oil',
          '1 tsp mustard seeds',
          '½ tsp urad dal',
          '½ tsp chana dal',
          '2 dry red chillies',
          '1 green chilli, slit',
          '10–12 curry leaves',
          '2 tbsp roasted peanuts',
          'Pinch of asafoetida',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        contentType: 'steps',
        items: [
          'Ensure the cooked rice is cooled and separated.',
          'Season the rice with turmeric and salt first.',
          'Heat oil in a pan.',
          'Add mustard seeds and let them pop.',
          'Add urad dal and chana dal and fry until light golden.',
          'Add dry red chillies, green chilli, and curry leaves.',
          'Add oyster mushrooms and cook on medium heat for 3–4 minutes.',
          'Add asafoetida and roasted peanuts.',
          'Add the turmeric-seasoned rice.',
          'Gently fold everything together.',
          'Add lemon juice and mix.',
          'Check salt and adjust.',
          'Serve warm with papad or pickle.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Oyster Mushroom Lemon Rice uses the familiar South Indian lemon rice method as its base, with oyster mushrooms added to give the dish more depth and protein.',
          'We season the rice with turmeric first. This coats each grain lightly and ensures the yellow colour is even throughout the dish. The salt at this stage also seasons the rice before it meets the tempering.',
          'The tempering is the key. Mustard seeds, urad dal, chana dal, dried chillies, and curry leaves give the oil its flavour. When the oyster mushrooms go into this aromatic oil, they cook in it and absorb those flavours.',
          'Roasted peanuts add crunch. They are added just before the rice so they stay crispy.',
          'Lemon juice goes in last, after everything is mixed. If lemon is added too early, heat reduces its freshness. Adding it after cooking keeps the citrus flavour bright.',
        ],
      },
    ],
  },
  {
    id: 'milky-mushroom-sambar-curry',
    title: 'Milky Mushroom Sambar-Style Curry',
    categoryIds: ['everyday-meals', 'mushroom-recipes'],
    primaryCategoryLabel: 'Everyday Meals',
    cookingTime: '35 minutes',
    serves: '3–4 people',
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Milky Mushroom in this recipe',
        contentType: 'nutrition',
        items: [
          'Milky mushrooms have a firm, meaty texture that holds up well in a long-simmered sambar-style curry',
          'Their natural umami adds depth to the tamarind and lentil base without needing extra stock',
          'They absorb sambar spice mix well, taking on the full flavour of the dish after simmering',
          'Milky mushroom pieces stay recognisable in the curry even after long cooking, unlike softer mushrooms that can break down',
          'This recipe works well over rice, idli, or dosa, making it a versatile everyday curry',
          'Using mushroom instead of drumstick or pearl onion gives sambar a heartier, more filling quality',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        contentType: 'ingredients',
        items: [
          '250g Milky Mushrooms, cut into large pieces',
          '½ cup toor dal or masoor dal, cooked and mashed',
          '1 onion, roughly chopped',
          '2 tomatoes, roughly chopped',
          '1 small piece tamarind, soaked and extracted (or 1 tsp tamarind paste)',
          '1½ tsp sambar powder',
          '½ tsp turmeric powder',
          '1 tsp red chilli powder',
          'Salt as needed',
          '2 tbsp oil',
          '1 tsp mustard seeds',
          '½ tsp cumin seeds',
          '2 dry red chillies',
          'Curry leaves',
          'Pinch of asafoetida',
          'Fresh coriander for garnish',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        contentType: 'steps',
        items: [
          'Cook and mash the dal separately.',
          'Soak tamarind and extract the water, or use tamarind paste.',
          'Heat oil in a pot.',
          'Add mustard seeds, cumin, dry red chillies, curry leaves, and asafoetida.',
          'Add onion and cook until soft.',
          'Add tomatoes and cook until they soften.',
          'Add milky mushrooms and cook for 4–5 minutes.',
          'Add turmeric, red chilli powder, and sambar powder.',
          'Add tamarind water and salt.',
          'Add mashed dal and water to adjust consistency.',
          'Simmer for 10–12 minutes.',
          'Garnish with fresh coriander.',
          'Serve over rice or with idli or dosa.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Milky Mushroom Sambar-Style Curry takes the warmth of South Indian sambar and builds it around milky mushroom instead of the usual vegetables.',
          'The dal is the backbone. We cook and mash it separately, then add it to the curry. It gives the broth a natural body and a slightly thick consistency that makes the curry feel wholesome.',
          'Tamarind is the sourness that defines sambar. The quantity matters. Too much makes it aggressively sour. Just enough gives it the characteristic tang that makes a sambar-style curry feel complete.',
          'Milky mushrooms go in early because they benefit from simmering time. As they cook in the tamarind-spice broth, they absorb the sambar flavour deeply.',
          'Sambar powder carries a blend of roasted spices that would take many individual ingredients to replicate. Using a good quality sambar powder simplifies this recipe significantly.',
          'This curry works over hot rice, alongside idli, or spooned over dosa.',
        ],
      },
    ],
  },
  {
    id: 'button-mushroom-chapati-gravy',
    title: 'Button Mushroom Chapati Gravy',
    categoryIds: ['everyday-meals', 'mushroom-recipes'],
    primaryCategoryLabel: 'Everyday Meals',
    cookingTime: '25 minutes',
    serves: '2–3 people',
    nutritionProfiles: [NUTRITION_BUTTON_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Button Mushroom in this recipe',
        contentType: 'nutrition',
        items: [
          'Button mushrooms are compact and absorb onion-tomato gravy well, making each piece flavourful inside and out',
          'Their mild taste suits a tomato-onion chapati gravy because it does not compete with the base flavours',
          'They cook quickly enough for a weekday dinner side dish that needs to be on the table in under 30 minutes',
          'Button mushrooms bring a light meaty quality to the curry without heaviness, making the meal feel satisfying without being rich',
          'The curry has enough sauce to dip chapati easily without being too watery or too thick',
          'This is a reliable everyday recipe that uses standard masala and widely available mushrooms',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        contentType: 'ingredients',
        items: [
          '250g Button Mushrooms, halved or quartered',
          '2 onions, finely chopped',
          '3 tomatoes, pureed or finely chopped',
          '1 tsp ginger-garlic paste',
          '1 tsp red chilli powder',
          '½ tsp turmeric powder',
          '1 tsp coriander powder',
          '½ tsp cumin powder',
          '½ tsp garam masala',
          '2 tbsp oil',
          'Salt as needed',
          '½ cup water',
          'Fresh coriander for garnish',
          '1 tbsp cream or butter, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        contentType: 'steps',
        items: [
          'Heat oil in a pan.',
          'Add onions and cook until golden brown.',
          'Add ginger-garlic paste and cook for 1 minute.',
          'Add tomatoes or tomato puree.',
          'Cook until the oil separates from the masala.',
          'Add turmeric, red chilli, coriander powder, cumin powder, and salt.',
          'Add button mushrooms and stir well.',
          'Add water and mix.',
          'Cover and cook for 10–12 minutes on medium heat.',
          'Add garam masala.',
          'Add cream or butter if preferred.',
          'Garnish with coriander and serve with chapati.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Button Mushroom Chapati Gravy is a reliable everyday recipe that works best with fresh mushrooms, a standard masala base, and a little patience.',
          'The onion-tomato base is the key. We cook the onions until genuinely golden — not just softened. Golden onions bring a sweetness that stops the curry from tasting raw. The tomatoes go in next and cook down completely until the oil separates. This separation is the signal that the masala is ready for the mushrooms.',
          'Button mushrooms go in and simmer in the masala with a little water. They release their own moisture as they cook, which naturally enriches the gravy.',
          'Garam masala is added only at the end. Adding it too early dulls its fragrance. A pinch added just before serving gives the curry its warm aroma.',
          'Cream or butter is optional. Without it, the curry is light. With it, it becomes slightly richer and restaurant-style.',
        ],
      },
    ],
  },
  {
    id: 'oyster-mushroom-coconut-curry-rice',
    title: 'Oyster Mushroom Coconut Curry for Rice',
    categoryIds: ['everyday-meals', 'mushroom-recipes'],
    primaryCategoryLabel: 'Everyday Meals',
    cookingTime: '30 minutes',
    serves: '3–4 people',
    nutritionProfiles: [NUTRITION_OYSTER_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Oyster Mushroom in this recipe',
        contentType: 'nutrition',
        items: [
          'Oyster mushrooms have a naturally tender texture that suits slow-simmered coconut curry, absorbing the coconut and spice flavours completely',
          'Their mild taste works well with coconut milk, which creates a rich, smooth curry base',
          'Oyster mushrooms cook gently in coconut milk without becoming tough, giving the curry a soft, pleasant texture',
          'Their natural earthiness pairs with Kerala-style coconut and whole spice flavours',
          'This is a filling curry that works well poured generously over plain rice for an everyday meal',
          'Coconut milk softens the mushroom\'s natural earthiness and makes the curry feel complete without needing heavy masala',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        contentType: 'ingredients',
        items: [
          '200g Oyster Mushrooms, torn into large pieces',
          '1 cup coconut milk',
          '1 onion, thinly sliced',
          '2 green chillies, slit',
          '1 tsp ginger-garlic paste',
          '2 tomatoes, chopped',
          '½ tsp turmeric powder',
          '1 tsp black pepper powder',
          '1 tsp coriander powder',
          '½ tsp garam masala',
          '2 tbsp coconut oil',
          'Curry leaves',
          'Salt as needed',
          'Fresh coriander for garnish',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        contentType: 'steps',
        items: [
          'Heat coconut oil in a pot.',
          'Add curry leaves and let them splutter.',
          'Add sliced onion and green chillies.',
          'Cook until onion turns soft and golden.',
          'Add ginger-garlic paste.',
          'Add tomatoes and cook until soft.',
          'Add turmeric, pepper, coriander powder, and salt.',
          'Add oyster mushrooms and cook for 3–4 minutes.',
          'Add coconut milk and stir gently.',
          'Simmer on low heat for 8–10 minutes.',
          'Do not boil vigorously after adding coconut milk.',
          'Add garam masala.',
          'Garnish with coriander and serve over rice.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Oyster Mushroom Coconut Curry for Rice is a gentle, aromatic dish. The whole character of this curry comes from the coconut oil and coconut milk combination, which gives it a warmth and richness that lighter curries don\'t have.',
          'We use coconut oil from the start because it brings an aroma to the tempering that neutral oils cannot match. Curry leaves bloomed in coconut oil smell like coastal Indian cooking.',
          'The mushrooms go in before the coconut milk so they can absorb the masala base first. If they go directly into coconut milk, they taste raw in the centre.',
          'The most important rule after adding coconut milk is to keep the heat low. High heat will cause the coconut milk to separate and become grainy. We want a smooth, silky curry that clings to the rice.',
          'Garam masala at the end gives warmth.',
        ],
      },
    ],
  },
  {
    id: 'button-mushroom-egg-bhurji',
    title: 'Button Mushroom Egg Bhurji',
    categoryIds: ['everyday-meals', 'mushroom-recipes'],
    primaryCategoryLabel: 'Everyday Meals',
    cookingTime: '20 minutes',
    serves: '2 people',
    nutritionProfiles: [NUTRITION_BUTTON_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Button Mushroom in this recipe',
        contentType: 'nutrition',
        items: [
          'Button mushrooms cooked with eggs create a naturally protein-rich, satisfying breakfast or quick dinner option',
          'Their mild taste blends with scrambled egg seamlessly, making the bhurji feel like one cohesive dish',
          'Button mushrooms add volume and texture to the bhurji without making it heavy or hard to eat',
          'They cook at a similar pace to egg when added at the right stage, so the timing is easy to manage',
          'The mushroom and egg combination brings both umami and complete protein together in one pan',
          'This is one of the most practical uses for button mushrooms at home — quick, filling, and needing minimal ingredients',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        contentType: 'ingredients',
        items: [
          '150g Button Mushrooms, finely chopped',
          '4 eggs',
          '1 onion, finely chopped',
          '1 tomato, finely chopped',
          '1 green chilli, finely chopped',
          '½ tsp red chilli powder',
          '¼ tsp turmeric powder',
          '¼ tsp garam masala',
          'Salt as needed',
          '2 tbsp oil or butter',
          'Fresh coriander for garnish',
          '½ tsp black pepper powder',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        contentType: 'steps',
        items: [
          'Heat oil or butter in a pan.',
          'Add onion and green chilli and cook until soft.',
          'Add finely chopped button mushrooms.',
          'Cook until the mushroom moisture evaporates.',
          'Add tomato and cook until soft.',
          'Add red chilli powder, turmeric, and salt.',
          'Beat the eggs lightly and pour over the cooked mushroom-tomato base.',
          'Scramble on medium heat, folding gently.',
          'Do not cook on high heat — keep the egg soft and moist.',
          'Add garam masala and pepper.',
          'Garnish with fresh coriander.',
          'Serve with chapati, bread, or rice.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Button Mushroom Egg Bhurji is one of the most practical recipes in this collection. It uses simple ingredients, comes together in under 20 minutes, and works as breakfast, lunch, or a quick dinner with chapati or rice.',
          'The mushrooms must be cooked until completely dry before the egg is added. Wet mushrooms will make the egg bhurji watery and the egg will not scramble well.',
          'We beat the eggs lightly and pour them over the cooked mushroom-tomato base. Medium heat is important here. High heat makes the egg tough and dry. The egg should fold gently into the mushroom mixture, staying soft and slightly creamy.',
          'Garam masala goes in at the end, just like in many egg dishes. A pinch added before serving gives the bhurji its warm, spiced finish.',
          'This recipe is flexible. More mushrooms means a more vegetable-forward bhurji. More eggs means a richer one.',
        ],
      },
    ],
  },
  {
    id: 'milky-mushroom-dal-curry',
    title: 'Milky Mushroom Dal Curry',
    categoryIds: ['everyday-meals', 'mushroom-recipes'],
    primaryCategoryLabel: 'Everyday Meals',
    cookingTime: '35 minutes',
    serves: '3–4 people',
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Milky Mushroom in this recipe',
        contentType: 'nutrition',
        items: [
          'Milky mushrooms added to dal create a combined protein source that makes the dal more filling and nutritious',
          'Their firm texture survives the long cooking time of dal without breaking down, giving the curry pleasant chunky pieces',
          'Milky mushroom brings natural umami depth to the dal, reducing the need for extra masala or flavour boosters',
          'The combination of lentil protein and mushroom umami makes this a substantial everyday meal over rice',
          'This recipe suits everyday cooking because both milky mushroom and common dal are affordable, accessible ingredients',
          'The mushroom absorbs the dal\'s spiced cooking liquid, making each piece taste deeply seasoned',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        contentType: 'ingredients',
        items: [
          '200g Milky Mushrooms, cut into large pieces',
          '¾ cup toor dal or masoor dal',
          '1 onion, finely chopped',
          '2 tomatoes, finely chopped',
          '1 tsp ginger-garlic paste',
          '1 tsp red chilli powder',
          '½ tsp turmeric powder',
          '1 tsp coriander powder',
          '½ tsp garam masala',
          'Salt as needed',
          '2 tbsp oil or ghee',
          '1 tsp mustard seeds',
          '½ tsp cumin seeds',
          'Curry leaves',
          'Fresh coriander for garnish',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        contentType: 'steps',
        items: [
          'Pressure cook the dal with turmeric and water until soft. Mash lightly.',
          'Heat oil or ghee in a pot.',
          'Add mustard seeds and cumin seeds.',
          'Add curry leaves and onion.',
          'Cook until onion is golden.',
          'Add ginger-garlic paste.',
          'Add tomatoes and cook until the masala thickens.',
          'Add red chilli, coriander powder, and salt.',
          'Add milky mushroom pieces and cook for 5 minutes.',
          'Add the cooked dal and mix.',
          'Add water to adjust consistency.',
          'Simmer for 8–10 minutes.',
          'Add garam masala.',
          'Garnish with coriander and serve over rice or with chapati.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Milky Mushroom Dal Curry is built for everyday cooking. Dal is already a staple in most Indian homes. Adding milky mushroom to it gives the same comfort with more depth and a satisfying texture that plain dal does not have.',
          'We cook the dal separately first. This gives us control over its consistency. Dal that is cooked in the same pot as the mushrooms can become over-softened or unevenly spiced.',
          'The mushrooms are cooked in the masala base before the dal is added. This gives them time to absorb the onion-tomato-spice flavours so they don\'t taste bland next to the dal.',
          'When the dal goes in, we adjust the water. The curry should be thick enough to coat rice nicely but not dry enough to clump.',
          'This curry works over rice, with chapati, or alongside plain idli for a more substantial meal.',
        ],
      },
    ],
  },
  {
    id: 'button-mushroom-dosa-side-masala',
    title: 'Button Mushroom Dosa Side Masala',
    categoryIds: ['everyday-meals', 'mushroom-recipes'],
    primaryCategoryLabel: 'Everyday Meals',
    cookingTime: '20 minutes',
    serves: '2–3 people',
    nutritionProfiles: [NUTRITION_BUTTON_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Button Mushroom in this recipe',
        contentType: 'nutrition',
        items: [
          'Button mushrooms have a fine, even texture that works beautifully as a stuffing or side masala for dosa',
          'Their size means they can be kept as small pieces that fit naturally inside a dosa without making it bulky',
          'The mild flavour of button mushroom pairs with classic potato masala spices, making it a familiar taste in an improved format',
          'Button mushrooms bring their own moisture to the masala, reducing the need for extra water or oil',
          'This recipe works as both a stuffing inside the dosa and as a side served alongside, making it flexible for different serving styles',
          'Using mushroom as a partial or full replacement for the potato in dosa masala reduces starch while keeping the dish satisfying',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        contentType: 'ingredients',
        items: [
          '200g Button Mushrooms, finely chopped',
          '1 medium potato, boiled and mashed, optional',
          '1 onion, thinly sliced',
          '2 green chillies, slit',
          '1 tsp ginger, grated',
          '½ tsp turmeric powder',
          '½ tsp mustard seeds',
          '½ tsp urad dal',
          '10–12 curry leaves',
          'Pinch of asafoetida',
          'Salt as needed',
          '2 tbsp oil',
          'Fresh coriander for garnish',
          '1 tsp lemon juice',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        contentType: 'steps',
        items: [
          'Finely chop the button mushrooms.',
          'Boil and mash the potato if using.',
          'Heat oil in a pan.',
          'Add mustard seeds and let them pop.',
          'Add urad dal, curry leaves, and asafoetida.',
          'Add sliced onion and green chillies.',
          'Cook until onion is soft.',
          'Add ginger and turmeric.',
          'Add button mushrooms and cook until the moisture evaporates.',
          'Add mashed potato if using and mix well.',
          'Check salt and adjust.',
          'Add lemon juice and fresh coriander.',
          'Use as a dosa stuffing or as a side masala.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Button Mushroom Dosa Side Masala replaces or supplements the traditional potato masala. It uses the same onion-turmeric-curry leaves base, but with finely chopped button mushrooms instead of just potato.',
          'The mushrooms are cooked until completely dry in this recipe. Any remaining moisture would make the masala wet and difficult to stuff inside a dosa.',
          'Potato can be included for a more traditional feel or omitted entirely for a lighter, lower-carb masala. When both are used, the potato gives body and the mushroom gives flavour.',
          'Asafoetida and urad dal in the tempering are what give this masala its characteristic dosa-side smell.',
          'Lemon juice and fresh coriander at the end make the masala feel fresh and alive, not heavy.',
          'Served inside a crispy dosa or as a side alongside plain dosa with sambar and chutney, this is a practical everyday breakfast option.',
        ],
      },
    ],
  },
  {
    id: 'oyster-mushroom-rasam-curry',
    title: 'Oyster Mushroom Rasam Curry',
    categoryIds: ['everyday-meals', 'mushroom-recipes'],
    primaryCategoryLabel: 'Everyday Meals',
    cookingTime: '25 minutes',
    serves: '3–4 people',
    nutritionProfiles: [NUTRITION_OYSTER_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Oyster Mushroom in this recipe',
        contentType: 'nutrition',
        items: [
          'Oyster mushrooms cook quickly in a thin broth-style curry, absorbing the tamarind and pepper flavours of rasam-style seasoning',
          'Their tender texture suits a thin, poured curry like rasam that is meant to be drunk or poured over rice',
          'Oyster mushrooms bring natural umami to rasam, which normally relies on tomato, pepper, and tamarind for its flavour',
          'They are light and digestive-friendly, matching the medicinal warmth that rasam is traditionally associated with',
          'This recipe gives rasam an additional ingredient that makes it feel more like a light curry while keeping its characteristic sour-pepper taste',
          'A mushroom rasam curry is comforting and practical, especially for rainy days or when something light and warming is needed',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        contentType: 'ingredients',
        items: [
          '150g Oyster Mushrooms, torn into medium pieces',
          '1 small piece tamarind soaked in water (or 1 tsp tamarind paste)',
          '2 tomatoes, finely chopped',
          '1 tsp black pepper powder',
          '1 tsp cumin powder',
          '½ tsp turmeric powder',
          '2 tsp rasam powder',
          '4–5 garlic cloves, crushed',
          'Salt as needed',
          '2 cups water',
          '2 tbsp oil',
          '1 tsp mustard seeds',
          '2 dry red chillies',
          '10–12 curry leaves',
          'Pinch of asafoetida',
          'Fresh coriander for garnish',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        contentType: 'steps',
        items: [
          'Extract tamarind water or dissolve tamarind paste in 1 cup water.',
          'Heat oil in a pot.',
          'Add mustard seeds, dry red chillies, curry leaves, and asafoetida.',
          'Add crushed garlic and cook briefly.',
          'Add tomatoes and cook until soft.',
          'Add turmeric, black pepper, cumin powder, rasam powder, and salt.',
          'Add tamarind water.',
          'Add oyster mushrooms.',
          'Add remaining water.',
          'Simmer on medium heat for 10–12 minutes.',
          'Adjust sourness and salt.',
          'Garnish with coriander and serve over rice or as a warm broth.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Oyster Mushroom Rasam Curry sits between a rasam and a thin curry. It has the sour, pepper-forward character of rasam but with oyster mushroom pieces simmered in it, giving it more body.',
          'Tamarind is the backbone. The quantity should be adjusted based on personal preference. Start with less and add more after tasting. Rasam should be pleasantly sour, not sharp.',
          'Rasam powder does the seasoning work. It contains a pre-roasted blend of spices made for this kind of thin curry.',
          'Black pepper is essential and should not be reduced. In rasam, pepper is medicine and flavour together. The warmth it provides is part of what makes rasam a comforting, digestive preparation.',
          'Oyster mushrooms simmer gently in this thin broth and absorb the tamarind-pepper flavour completely. They cook quickly, so 10–12 minutes of simmering is enough.',
          'This rasam curry can be poured directly over rice or served in a cup as a warm drink after a meal.',
        ],
      },
    ],
  },
]
