import type { RecipeData } from '@/types'
import {
  NUTRITION_BUTTON_MUSHROOM_USDA,
  NUTRITION_OYSTER_MUSHROOM_USDA,
} from '@/constants/NUTRITION_PROFILES'

export const HEALTHY_PLATE_RECIPES: RecipeData[] = [
  {
    id: 'oyster-mushroom-lemon-green-plate',
    title: 'Oyster Mushroom Lemon Green Plate',
    categoryIds: ['healthy-plates', 'mushroom-recipes'],
    primaryCategoryLabel: 'Healthy Plates',
    cookingTime: '20 minutes',
    serves: '1–2 people',
    nutritionProfiles: [NUTRITION_OYSTER_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Why this plate works',
        contentType: 'nutrition',
        items: [
          'Oyster mushrooms are low in calories and rich in protein, making them ideal as the main element of a light, balanced plate',
          'Leafy greens bring folate, iron, and fibre alongside the mushroom protein',
          'Lemon dressing keeps the plate fresh and bright without adding heavy sauce or dressing',
          'A simple plate format makes portion control easy and the meal visible — you can see what you are eating',
          'Cooked grains like millet or brown rice add complex carbohydrates and make the plate more sustaining',
          'This plate requires minimal cooking and comes together quickly for a weekday lunch or light dinner',
        ],
      },
      {
        id: 'ingredients',
        title: 'Plate Components',
        contentType: 'ingredients',
        items: [
          '150g Oyster Mushrooms, pan-roasted',
          '1 cup cooked millet, brown rice, or quinoa',
          '1 cup fresh spinach or mixed greens',
          '½ cucumber, sliced',
          '1 small carrot, grated or sliced',
          '2 tbsp roasted peanuts or sunflower seeds',
          'Lemon dressing: 1 tbsp lemon juice, 1 tsp olive oil, salt, pepper, ¼ tsp cumin',
          '1 tsp oil for roasting mushrooms',
          'Salt, pepper, and cumin for seasoning the mushrooms',
        ],
      },
      {
        id: 'process',
        title: 'Plate Assembly',
        contentType: 'steps',
        items: [
          'Cook the grains and keep them ready.',
          'Season oyster mushrooms with salt, pepper, and a pinch of cumin.',
          'Pan-roast on high heat until golden and slightly crispy at the edges.',
          'Mix lemon dressing separately.',
          'Wash and dry the greens.',
          'Arrange cooked grains in one section of the plate.',
          'Add fresh greens and raw vegetables.',
          'Place the roasted oyster mushrooms on top.',
          'Add roasted peanuts or seeds.',
          'Drizzle the lemon dressing just before eating.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Oyster Mushroom Lemon Green Plate is built for simplicity and visibility. A healthy plate should look like a healthy plate. When we can see the grains, greens, vegetables, and protein clearly separated on the plate, it feels balanced and deliberate.',
          'Oyster mushrooms are pan-roasted at high heat so they develop a slight golden crust. This gives the plate a warm, satisfying element without any deep frying.',
          'The lemon dressing is kept minimal — lemon, oil, salt, pepper, cumin. It brightens the greens and the mushrooms without coating the plate in a heavy sauce.',
          'Roasted peanuts or seeds bring a crunch that makes the plate feel complete. Without them, the plate can feel too soft and uniform in texture.',
          'This plate is best eaten fresh, before the dressing softens the greens.',
        ],
      },
    ],
  },
  {
    id: 'button-mushroom-egg-fitness-plate',
    title: 'Button Mushroom Egg Fitness Plate',
    categoryIds: ['healthy-plates', 'mushroom-recipes'],
    primaryCategoryLabel: 'Healthy Plates',
    cookingTime: '20 minutes',
    serves: '1–2 people',
    nutritionProfiles: [NUTRITION_BUTTON_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Why this plate works',
        contentType: 'nutrition',
        items: [
          'Button mushroom and egg together create a high-protein, low-calorie plate suitable for active people',
          'Eggs bring complete amino acid protein and healthy fats; mushrooms bring B vitamins, fibre, and umami',
          'The combination of cooked greens and raw salad on the same plate provides both cooked-vegetable warmth and fresh crunch',
          'This plate is filling without being heavy, making it suitable before or after exercise',
          'Keeping cooking simple — just pan-cooking and boiling — preserves the nutritional quality of all components',
          'A fitness-focused plate does not need to taste bland; this one uses cumin, pepper, and lemon to make it flavourful',
        ],
      },
      {
        id: 'ingredients',
        title: 'Plate Components',
        contentType: 'ingredients',
        items: [
          '150g Button Mushrooms, sautéed',
          '2–3 eggs, boiled or pan-cooked as preferred',
          '1 cup cooked oats, millet, or brown rice',
          '1 cup leafy greens (spinach or methi)',
          '½ cucumber, sliced',
          '1 small tomato, sliced',
          '½ tsp black pepper powder',
          '½ tsp cumin powder',
          '1 tbsp lemon juice',
          'Salt as needed',
          '1 tsp oil',
          'Fresh coriander, optional',
        ],
      },
      {
        id: 'process',
        title: 'Plate Assembly',
        contentType: 'steps',
        items: [
          'Cook the grain base and keep ready.',
          'Boil or cook eggs in preferred style.',
          'Sauté button mushrooms with oil, pepper, cumin, and salt.',
          'Add leafy greens to the mushroom pan briefly and toss.',
          'Slice the boiled eggs.',
          'Arrange grain base in one section.',
          'Place mushroom and greens beside the grains.',
          'Add sliced egg on the plate.',
          'Add raw cucumber and tomato.',
          'Squeeze lemon over the full plate before eating.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Button Mushroom Egg Fitness Plate is for people who eat with a health goal in mind but still want their food to taste good. It is protein-forward and light in calories, without tasting like diet food.',
          'We cook the button mushrooms until they are slightly golden and their moisture is fully evaporated. Wet mushrooms on a fitness plate feel heavy and soggy.',
          'Leafy greens are quickly tossed in the same pan as the mushrooms for just a minute, so they wilt slightly and absorb the seasoning. They should be cooked just enough to soften without becoming dull.',
          'Eggs can be done any way — boiled, scrambled, or fried in a dry pan. The yolk of a boiled egg adds healthy fat that makes the plate sustaining. Scrambled eggs with the mushrooms is another option for a more combined dish.',
          'Lemon over the plate at the end is non-negotiable. It brings the whole plate alive.',
        ],
      },
    ],
  },
  {
    id: 'broccoli-microgreen-chickpea-plate',
    title: 'Broccoli Microgreen Chickpea Plate',
    categoryIds: ['healthy-plates', 'microgreen-recipes'],
    primaryCategoryLabel: 'Healthy Plates',
    cookingTime: '20 minutes',
    serves: '1–2 people',
    cards: [
      {
        id: 'goodness',
        title: 'Why this plate works',
        contentType: 'nutrition',
        items: [
          'Broccoli microgreens are best kept raw and used as a fresh, crisp top layer over warm cooked chickpeas',
          'Chickpeas provide plant-based protein and complex carbohydrates, making this a genuinely filling plate',
          'The combination of warm spiced chickpeas and cool, raw microgreens gives the plate interesting temperature and texture contrast',
          'Lemon brightens the whole plate and helps the body absorb iron from the greens and chickpeas',
          'No grain is needed here — the chickpeas provide enough carbohydrate and body for a light meal',
          'This plate can be assembled in under 20 minutes using pre-cooked or canned chickpeas',
        ],
      },
      {
        id: 'ingredients',
        title: 'Plate Components',
        contentType: 'ingredients',
        items: [
          '1 cup fresh broccoli microgreens',
          '1 cup cooked chickpeas (or canned, drained)',
          '1 small onion, finely chopped',
          '1 tomato, finely chopped',
          '1 green chilli, finely chopped',
          '½ tsp cumin powder',
          '½ tsp coriander powder',
          '¼ tsp chaat masala',
          '1 tsp lemon juice',
          'Salt and black pepper as needed',
          '1 tsp oil',
          '2 tbsp pomegranate seeds, optional',
          '1 tbsp roasted peanuts, optional',
        ],
      },
      {
        id: 'process',
        title: 'Plate Assembly',
        contentType: 'steps',
        items: [
          'Heat oil in a small pan.',
          'Add onion and green chilli and cook until soft.',
          'Add tomato and cook briefly.',
          'Add cooked chickpeas, cumin, coriander, and salt.',
          'Toss well and cook for 3–4 minutes.',
          'Add chaat masala and remove from heat.',
          'Place the warm spiced chickpeas in the centre or side of the plate.',
          'Add fresh broccoli microgreens generously on top.',
          'Add pomegranate seeds and peanuts if using.',
          'Squeeze lemon just before eating.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Broccoli Microgreen Chickpea Plate is designed around a simple pairing: warm spiced chickpeas and cool, raw broccoli microgreens. The two elements balance each other well.',
          'We spice the chickpeas with a light onion-tomato base and a small amount of masala. The goal is to flavour them without making them into a curry. They should taste like well-seasoned, warm chickpeas, not a sauce-heavy dish.',
          'Chaat masala is the finishing touch for the chickpeas. It gives a sweet-sour tangy note that makes even simply spiced chickpeas taste lively.',
          'The broccoli microgreens go on raw at the end. They are placed over the warm chickpeas, not stirred in. The warmth from the chickpeas slightly wilts them without cooking them, keeping their fresh flavour.',
          'Lemon juice over the full plate ties everything together.',
        ],
      },
    ],
  },
  {
    id: 'sunflower-microgreen-paneer-plate',
    title: 'Sunflower Microgreen Paneer Plate',
    categoryIds: ['healthy-plates', 'microgreen-recipes'],
    primaryCategoryLabel: 'Healthy Plates',
    cookingTime: '25 minutes',
    serves: '1–2 people',
    cards: [
      {
        id: 'goodness',
        title: 'Why this plate works',
        contentType: 'nutrition',
        items: [
          'Sunflower microgreens bring a nutty, juicy crunch to the plate that pairs well with the softness of paneer tikka',
          'Paneer provides protein and healthy fat from dairy; microgreens bring fresh vitamins and minerals',
          'A grain base of millet or brown rice makes the plate sustaining without being heavy',
          'Sunflower microgreens are best used raw here, contrasting with the warm, lightly charred paneer',
          'The combination of warm paneer, fresh greens, and a light dressing creates a satisfying plate that does not feel like it is missing anything',
          'This plate is colourful, nutritious, and takes under 30 minutes to assemble',
        ],
      },
      {
        id: 'ingredients',
        title: 'Plate Components',
        contentType: 'ingredients',
        items: [
          '1 cup fresh sunflower microgreens',
          '150g paneer, cut into cubes and lightly marinated',
          '½ tsp red chilli powder',
          '¼ tsp garam masala',
          '¼ tsp cumin powder',
          '1 tsp lemon juice',
          'Salt as needed',
          '1 cup cooked millet, quinoa, or brown rice',
          '½ cucumber, sliced',
          '1 small tomato, sliced',
          '1 tsp oil for cooking',
          'Green chutney or yogurt dip for serving, optional',
        ],
      },
      {
        id: 'process',
        title: 'Plate Assembly',
        contentType: 'steps',
        items: [
          'Marinate paneer cubes in chilli powder, garam masala, cumin, lemon, and salt.',
          'Cook marinated paneer on a hot tawa or pan until lightly golden.',
          'Cook grain base and keep ready.',
          'Wash and dry sunflower microgreens.',
          'Arrange cooked grain in one section of the plate.',
          'Add sliced cucumber and tomato.',
          'Place the cooked paneer pieces.',
          'Add fresh sunflower microgreens generously.',
          'Serve with green chutney or yogurt dip on the side.',
          'Squeeze lemon just before eating.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Sunflower Microgreen Paneer Plate is about combining cooked warmth with raw freshness. The paneer tikka is warm and slightly charred. The sunflower microgreens are cool, juicy, and crunchy. They work well together on the same plate.',
          'The paneer needs just a quick marinade and a hot pan. We want a lightly charred outside, not a fully cooked-through drying. Paneer that has been cooked too long becomes rubbery and dry.',
          'Sunflower microgreens go on raw at the end. They should not be heated or wilted here. Their juicy crunch is what balances the richness of paneer.',
          'The grain base can be millet, brown rice, or quinoa. Each works differently. Millet is the lightest option. Brown rice gives a familiar texture. Quinoa gives additional protein.',
          'Green chutney on the side makes the plate feel complete and adds a bright, herbal freshness.',
        ],
      },
    ],
  },
  {
    id: 'radish-microgreen-sprout-peanut-plate',
    title: 'Radish Microgreen Sprout & Peanut Plate',
    categoryIds: ['healthy-plates', 'microgreen-recipes'],
    primaryCategoryLabel: 'Healthy Plates',
    cookingTime: '15 minutes',
    serves: '1–2 people',
    cards: [
      {
        id: 'goodness',
        title: 'Why this plate works',
        contentType: 'nutrition',
        items: [
          'Radish microgreens bring a natural peppery freshness that makes this a light, flavourful plate without needing heavy spice',
          'Mixed sprouts add plant-based protein and make the plate more sustaining',
          'Roasted peanuts bring additional protein, healthy fat, and crunch',
          'This is a mostly raw plate — no cooking of the main components is needed, making it fast and nutrient-preserving',
          'Lemon and cumin work as the dressing, keeping the plate simple and digestive',
          'The plate provides protein, healthy fat, fibre, and fresh micronutrients in one bowl-style serving',
        ],
      },
      {
        id: 'ingredients',
        title: 'Plate Components',
        contentType: 'ingredients',
        items: [
          '1 cup fresh radish microgreens',
          '½ cup mixed sprouts (moong, chana, or any available)',
          '3 tbsp roasted peanuts',
          '1 small cucumber, chopped',
          '1 small tomato, chopped',
          '1 small onion, finely chopped',
          '1 green chilli, finely chopped, optional',
          '1 tbsp lemon juice',
          '¼ tsp roasted cumin powder',
          '¼ tsp black pepper',
          'Pinch of black salt',
          'Salt as needed',
          '2 tbsp pomegranate seeds, optional',
          'Fresh coriander, optional',
        ],
      },
      {
        id: 'process',
        title: 'Plate Assembly',
        contentType: 'steps',
        items: [
          'Clean and dry radish microgreens.',
          'Mix cucumber, tomato, onion, and green chilli.',
          'Add lemon juice, cumin powder, black pepper, black salt, and regular salt.',
          'Add sprouts and peanuts to the mixed vegetables.',
          'Toss gently.',
          'Add radish microgreens only at the end.',
          'Toss gently once more without crushing the greens.',
          'Add pomegranate seeds and coriander if using.',
          'Serve immediately.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Radish Microgreen Sprout & Peanut Plate is the simplest plate in the collection. Almost everything is raw and uncooked. The effort is in the assembly, not the cooking.',
          'Radish microgreens have a clean peppery bite. They are the element that makes this more than just a sprout salad. Their flavour is immediate and lively.',
          'We season the vegetables and sprouts first, then add the microgreens. If the microgreens sit in the lemon and salt too long, they will soften and lose their fresh character.',
          'Roasted peanuts go in with the sprouts, not at the very end. They absorb a little of the lemon dressing and become lightly seasoned.',
          'Black salt is optional but adds that chaat-style edge that makes the plate taste familiar and satisfying.',
          'Eat this immediately after assembling.',
        ],
      },
    ],
  },
  {
    id: 'pea-shoot-sesame-oyster-mushroom-plate',
    title: 'Pea Shoot Sesame Oyster Mushroom Plate',
    categoryIds: ['healthy-plates', 'mushroom-recipes', 'microgreen-recipes'],
    primaryCategoryLabel: 'Healthy Plates',
    cookingTime: '20 minutes',
    serves: '1–2 people',
    nutritionProfiles: [NUTRITION_OYSTER_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Why this plate works',
        contentType: 'nutrition',
        items: [
          'Pea shoots have a naturally sweet, tender taste that works well alongside the earthy, roasted flavour of oyster mushrooms',
          'Oyster mushrooms roasted on high heat give the plate a warm, satisfying protein-rich element',
          'Sesame seeds add healthy fat, a nutty flavour, and crunch without adding heaviness',
          'Pea shoots can be used raw or very lightly cooked, depending on how much warmth is preferred on the plate',
          'This plate has a mild, clean flavour that makes it suitable for people who want something light but filling',
          'A brown rice or millet grain base makes this a complete balanced meal',
        ],
      },
      {
        id: 'ingredients',
        title: 'Plate Components',
        contentType: 'ingredients',
        items: [
          '1 cup fresh pea shoots',
          '150g Oyster Mushrooms, pan-roasted',
          '1 cup cooked brown rice or millet',
          '½ cucumber, sliced',
          '1 tbsp sesame seeds, toasted',
          '1 tsp sesame oil',
          '1 tsp soy sauce',
          '1 tbsp lemon juice',
          '¼ tsp black pepper',
          'Salt as needed',
          '1 tsp oil for roasting mushrooms',
          '2 tsp spring onion greens, optional',
        ],
      },
      {
        id: 'process',
        title: 'Plate Assembly',
        contentType: 'steps',
        items: [
          'Cook grain base and keep ready.',
          'Toast sesame seeds in a dry pan and set aside.',
          'Season oyster mushrooms with salt and pepper.',
          'Pan-roast on high heat until golden at the edges.',
          'Deglaze the pan briefly with a few drops of soy sauce.',
          'Make dressing: sesame oil, lemon juice, soy sauce, pepper, salt.',
          'Arrange grain in one section of the plate.',
          'Add fresh pea shoots and sliced cucumber.',
          'Place the roasted oyster mushrooms.',
          'Drizzle the sesame dressing over the plate.',
          'Top with toasted sesame seeds and spring onion greens.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Pea Shoot Sesame Oyster Mushroom Plate is built around the combination of warm roasted mushroom and fresh, sweet pea shoots. Sesame ties them together with a nutty aroma.',
          'The oyster mushrooms need high heat and a sear. We pan-roast them until golden at the edges, then add a few drops of soy sauce at the end. The soy sauce quickly reduces on the hot pan and creates a light glaze on the mushrooms.',
          'Pea shoots are left raw here. Their sweetness and tender crunch are the contrast to the warm, savoury mushrooms. A quick toss in a little sesame dressing is enough.',
          'The sesame dressing — sesame oil, lemon, soy — gives the plate a clean, aromatic quality without being heavy.',
          'Toasted sesame seeds finish the plate with crunch and a warm, nutty smell.',
        ],
      },
    ],
  },
  {
    id: 'beetroot-microgreen-paneer-colour-plate',
    title: 'Beetroot Microgreen Paneer Colour Plate',
    categoryIds: ['healthy-plates', 'microgreen-recipes'],
    primaryCategoryLabel: 'Healthy Plates',
    cookingTime: '20 minutes',
    serves: '1–2 people',
    cards: [
      {
        id: 'goodness',
        title: 'Why this plate works',
        contentType: 'nutrition',
        items: [
          'Beetroot microgreens bring beautiful red-purple colour that makes the plate look visually striking and premium',
          'Paneer provides protein and dairy fat; the microgreens bring a fresh, earthy contrast to cooked paneer',
          'Raw microgreens on a warm paneer plate create a temperature and texture contrast that makes each bite interesting',
          'The plate is naturally colourful without added food colouring or heavy sauces',
          'Millet or quinoa gives the plate a low-GI grain base that keeps energy stable',
          'This is a visually impressive plate that is genuinely simple to assemble',
        ],
      },
      {
        id: 'ingredients',
        title: 'Plate Components',
        contentType: 'ingredients',
        items: [
          '1 cup fresh beetroot microgreens',
          '150g paneer, cut and lightly seasoned',
          '1 cup cooked millet or quinoa',
          '½ cucumber, sliced',
          '1 small tomato, sliced',
          '2 tbsp roasted peanuts',
          '1 tsp lemon juice',
          '¼ tsp cumin powder',
          'Pinch of black salt',
          'Salt and pepper as needed',
          '1 tsp oil for cooking paneer',
          'Green chutney for serving, optional',
        ],
      },
      {
        id: 'process',
        title: 'Plate Assembly',
        contentType: 'steps',
        items: [
          'Season paneer pieces with cumin, pepper, and salt.',
          'Cook on a hot pan with a little oil until lightly golden.',
          'Cook grain base and let it cool slightly.',
          'Clean and dry beetroot microgreens.',
          'Arrange grain in one section of the plate.',
          'Add cucumber and tomato slices.',
          'Place the cooked paneer pieces.',
          'Add beetroot microgreens generously over the paneer.',
          'Add roasted peanuts.',
          'Squeeze lemon over the plate.',
          'Serve with green chutney on the side.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Beetroot Microgreen Paneer Colour Plate is designed for presentation as much as flavour. Beetroot microgreens are vivid red-purple. Paneer is pale and golden. Together on a plate they create a colour contrast that immediately signals freshness and care.',
          'The paneer is seasoned simply — just cumin, pepper, and salt — and cooked until it has a light golden surface. We don\'t over-marinate or over-spice it. The microgreens are the flavour contrast, and they should be allowed to speak.',
          'Beetroot microgreens are mildly earthy and slightly sweet. They pair well with the neutral, milky taste of paneer.',
          'Roasted peanuts add the crunch that balances the soft textures of paneer and grain.',
          'The plate looks most impressive when the microgreens are placed last, scattered generously over the top.',
        ],
      },
    ],
  },
  {
    id: 'button-mushroom-foxtail-millet-curd-plate',
    title: 'Button Mushroom Foxtail Millet Curd Plate',
    categoryIds: ['healthy-plates', 'mushroom-recipes'],
    primaryCategoryLabel: 'Healthy Plates',
    cookingTime: '25 minutes',
    serves: '1–2 people',
    nutritionProfiles: [NUTRITION_BUTTON_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Why this plate works',
        contentType: 'nutrition',
        items: [
          'Foxtail millet is a traditional South Indian grain with a lower glycaemic index than white rice, making it a better everyday grain choice',
          'Button mushrooms sautéed with mild masala bring protein and umami to the plate',
          'Thick curd provides probiotics, calcium, and a cooling element that balances the warm mushroom masala',
          'The combination of millet, mushroom, and curd gives the plate protein, complex carbohydrates, and beneficial bacteria',
          'This plate suits people managing blood sugar or looking for a lighter, more functional everyday lunch',
          'Foxtail millet cooks quickly and has a mild, slightly nutty flavour that goes well with mushroom and curd',
        ],
      },
      {
        id: 'ingredients',
        title: 'Plate Components',
        contentType: 'ingredients',
        items: [
          '150g Button Mushrooms, sautéed with mild masala',
          '1 cup cooked foxtail millet',
          '½ cup thick curd',
          '½ cucumber, sliced',
          '1 small carrot, grated',
          '¼ tsp roasted cumin powder',
          '¼ tsp black pepper',
          'Salt as needed',
          '1 tsp oil for mushrooms',
          '½ tsp cumin seeds and curry leaves for mushroom tempering',
          'Fresh coriander, optional',
          '1 tbsp roasted peanuts, optional',
        ],
      },
      {
        id: 'process',
        title: 'Plate Assembly',
        contentType: 'steps',
        items: [
          'Cook foxtail millet with 1:2 water ratio until fluffy.',
          'Heat oil in a pan, add cumin seeds and curry leaves.',
          'Add button mushrooms and cook until dry and slightly golden.',
          'Season with salt and pepper.',
          'Let the millet and mushroom cool slightly.',
          'Whisk curd with cumin powder, salt, and pepper.',
          'Arrange millet in one section of the plate.',
          'Place sautéed mushrooms beside the millet.',
          'Add cucumber and grated carrot.',
          'Spoon the curd on the side or over the millet.',
          'Top with roasted peanuts and fresh coriander.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Button Mushroom Foxtail Millet Curd Plate is a functional, balanced meal that suits everyday lunch, especially for people interested in millets or managing their diet more intentionally.',
          'Foxtail millet has a gentle, nutty taste that holds up well alongside the mushroom masala. It should not be overcooked — the millet grains should remain separate and slightly firm, like a good cooked rice.',
          'The mushrooms are sautéed simply with cumin and curry leaves. A heavy masala would overpower the millet and curd, so we keep the spice light.',
          'The curd is seasoned with cumin and pepper so it is not just plain cold curd sitting on the plate. This small step of seasoning the curd makes the whole plate taste more intentional.',
          'The plate works well as a full meal, with the curd providing cooling balance to the warm mushroom and millet.',
        ],
      },
    ],
  },
  {
    id: 'prozekt1-fresh-harvest-plate',
    title: 'Prozekt-1 Fresh Harvest Plate',
    categoryIds: ['healthy-plates', 'mushroom-recipes', 'microgreen-recipes'],
    primaryCategoryLabel: 'Healthy Plates',
    cookingTime: '30 minutes',
    serves: '1–2 people',
    nutritionProfiles: [NUTRITION_BUTTON_MUSHROOM_USDA, NUTRITION_OYSTER_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'About this Plate',
        contentType: 'nutrition',
        items: [
          'This plate is built entirely from what Prozekt-1 grows: mushrooms and microgreens',
          'A combination of button mushroom and oyster mushroom gives the plate two different mushroom textures and flavour profiles',
          'Fresh microgreens on top keep the plate alive and vibrant',
          'This plate showcases the natural quality of farm-fresh produce without hiding it under heavy seasoning',
          'A grain base of millet or brown rice makes it a complete and sustaining meal',
          'The nutritional value comes naturally from the ingredients, not from supplements or additives',
        ],
      },
      {
        id: 'ingredients',
        title: 'Plate Components',
        contentType: 'ingredients',
        items: [
          '100g Button Mushrooms, sautéed',
          '100g Oyster Mushrooms, pan-roasted',
          '1 cup fresh mixed microgreens (sunflower, radish, or any seasonal variety)',
          '1 cup cooked millet or brown rice',
          '½ cucumber, sliced',
          '1 small tomato, sliced',
          '2 tbsp roasted peanuts or seeds',
          'Simple dressing: lemon juice, olive oil or cold-pressed oil, salt, pepper, cumin',
          '1 tsp butter or oil for cooking mushrooms',
          'Salt, pepper, and herbs for seasoning',
          'Green chutney or yogurt dip, optional',
        ],
      },
      {
        id: 'process',
        title: 'Plate Assembly',
        contentType: 'steps',
        items: [
          'Cook grain base and let it cool slightly.',
          'Season and sauté button mushrooms until golden.',
          'Season and pan-roast oyster mushrooms on high heat separately.',
          'Clean and dry the microgreens.',
          'Prepare lemon dressing.',
          'Arrange grain in one section of the plate.',
          'Place button mushrooms and oyster mushrooms side by side.',
          'Add cucumber and tomato.',
          'Layer fresh microgreens over the mushrooms.',
          'Add roasted peanuts or seeds.',
          'Drizzle the lemon dressing just before eating.',
          'Serve with green chutney or yogurt dip if preferred.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Prozekt-1 Fresh Harvest Plate is our signature plate. It uses two mushrooms and fresh microgreens — everything we grow — on a single plate. It is the most direct expression of what Prozekt-1 grows and believes in.',
          'Button mushrooms are sautéed until golden. Oyster mushrooms are pan-roasted at high heat to get their lightly crispy, earthy character. Both are cooked separately because they need different levels of heat and time.',
          'Fresh microgreens go on raw, scattered generously over the mushrooms and the full plate. The visual result is a plate that looks layered, fresh, and alive.',
          'The grain base under everything makes it a complete meal. Millet or brown rice both work. The grain should be slightly warm so the plate does not feel cold.',
          'The dressing is simple: lemon, a good oil, salt, pepper, and cumin. It is all the plate needs. The natural flavours of the mushrooms and microgreens are what carry the dish.',
          'This plate represents Prozekt-1 as it is: fresh produce, real ingredients, no shortcuts.',
        ],
      },
    ],
  },
]
