import {
  SUNFLOWER_MICROGREEN_PEANUT_KACHUMBER_IMAGES,
  RADISH_MICROGREEN_CURD_TOSS_IMAGES,
  MUSTARD_MICROGREEN_COCONUT_PACHADI_IMAGES,
  BROCCOLI_MICROGREEN_LEMON_CURD_DIP_IMAGES,
} from '@/assets/Recipe Book'
import type { RecipeData } from '@/types'

export const MICROGREEN_RECIPES: RecipeData[] = [
  {
    id: 'sunflower-microgreen-peanut-kachumber',
    title: 'Sunflower Microgreen Peanut Kachumber',
    bestWith: 'Fresh Sunflower Microgreens',
    categoryIds: ['microgreen-recipes', 'healthy-plates'],
    primaryCategoryLabel: 'Microgreen Recipes',
    cookingTime: '10 minutes',
    serves: '2 people',
    thumbnailSrc: SUNFLOWER_MICROGREEN_PEANUT_KACHUMBER_IMAGES.thumbnail,
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Sunflower Microgreens in this recipe',
        imageSrc: SUNFLOWER_MICROGREEN_PEANUT_KACHUMBER_IMAGES.goodness,
        imageAlt: 'Sunflower Microgreens sketch',
        contentType: 'nutrition',
        items: [
          'Sunflower microgreens have a juicy crunch and mild nutty taste, so they work beautifully in a fresh kachumber-style salad',
          'Their thicker stems give better bite than delicate leafy greens, especially when mixed with cucumber, onion, lemon, and peanuts',
          'They are best used raw in this recipe, because cooking would soften the crunch that makes sunflower microgreens enjoyable',
          'The roasted peanuts match their natural nuttiness and make the salad feel fuller without needing heavy dressing',
          'Lemon, chilli, and salt brighten the microgreens, but we add them carefully so the greens stay fresh instead of becoming watery',
          'This recipe is a simple way to use microgreens as the main ingredient, not just as decoration on top of food',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: SUNFLOWER_MICROGREEN_PEANUT_KACHUMBER_IMAGES.ingredients,
        imageAlt: 'Ingredients for Sunflower Microgreen Peanut Kachumber',
        contentType: 'ingredients',
        items: [
          '2 cups fresh sunflower microgreens',
          '1 small cucumber, finely chopped',
          '1 small onion, finely chopped',
          '1 small tomato, deseeded and chopped, optional',
          '2 tbsp roasted peanuts, lightly crushed',
          '1 green chilli, finely chopped',
          '1 tbsp lemon juice',
          '¼ tsp black pepper powder',
          '¼ tsp roasted cumin powder',
          'Salt as needed',
          'Fresh coriander leaves, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: SUNFLOWER_MICROGREEN_PEANUT_KACHUMBER_IMAGES.process,
        imageAlt: 'Making Sunflower Microgreen Peanut Kachumber',
        contentType: 'steps',
        items: [
          'Clean the sunflower microgreens gently and dry them well.',
          'Chop cucumber, onion, green chilli, and tomato if using.',
          'Lightly crush the roasted peanuts.',
          'Mix cucumber, onion, chilli, lemon juice, pepper, cumin powder, and salt.',
          'Add sunflower microgreens only at the end.',
          'Toss gently so the greens do not bruise.',
          'Add crushed peanuts just before serving.',
          'Serve immediately as a fresh side salad.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: SUNFLOWER_MICROGREEN_PEANUT_KACHUMBER_IMAGES.howWeMakeIt,
        imageAlt: 'Sunflower Microgreen Peanut Kachumber served',
        contentType: 'narrative',
        narrative: [
          'Sunflower Microgreen Peanut Kachumber is one of the easiest ways to make microgreens feel familiar on an Indian plate. It has the freshness of a normal kachumber, but the sunflower microgreens bring a juicy crunch that makes it feel more interesting than just cucumber and onion.',
          'We keep the microgreens raw because that is where they taste best. Sunflower microgreens have thicker stems and a mild nutty flavour, so they don\'t need cooking.',
          'The cucumber gives coolness, onion gives sharpness, green chilli gives a little heat, and lemon wakes everything up. Tomato is optional because it can make the salad watery if it is too soft.',
          'The important part is timing. Salt and lemon should not sit too long with the microgreens. We first mix the basic chopped ingredients with seasoning, then add the sunflower microgreens at the end and toss gently.',
          'Roasted peanuts go in last because they bring crunch and a warm nutty taste that matches the sunflower microgreens nicely.',
        ],
      },
    ],
  },
  {
    id: 'radish-microgreen-curd-toss',
    title: 'Radish Microgreen Curd Toss',
    bestWith: 'Fresh Radish Microgreens',
    categoryIds: ['microgreen-recipes', 'healthy-plates'],
    primaryCategoryLabel: 'Microgreen Recipes',
    cookingTime: '10 minutes',
    serves: '2 people',
    thumbnailSrc: RADISH_MICROGREEN_CURD_TOSS_IMAGES.thumbnail,
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Radish Microgreens in this recipe',
        imageSrc: RADISH_MICROGREEN_CURD_TOSS_IMAGES.goodness,
        imageAlt: 'Radish Microgreens sketch',
        contentType: 'nutrition',
        items: [
          'Radish microgreens have a natural peppery bite, so they bring flavour without needing heavy spices',
          'Their sharpness balances beautifully with cool curd and cucumber',
          'They are best used raw here because heat would reduce their fresh crunch and lively taste',
          'A small amount can make a simple curd bowl feel bright, fresh, and more interesting',
          'Roasted cumin and black pepper support the radish flavour without covering it',
          'This recipe is a good way to introduce radish microgreens to people who enjoy curd rice, raita, or fresh Indian-style sides',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: RADISH_MICROGREEN_CURD_TOSS_IMAGES.ingredients,
        imageAlt: 'Ingredients for Radish Microgreen Curd Toss',
        contentType: 'ingredients',
        items: [
          '1½ cups fresh radish microgreens',
          '1 cup thick curd',
          '½ cucumber, finely chopped',
          '1 small onion, finely chopped, optional',
          '1 tbsp grated carrot, optional',
          '½ tsp roasted cumin powder',
          '¼ tsp black pepper powder',
          '½ tsp lemon juice',
          'Salt as needed',
          '1 tbsp pomegranate seeds, optional',
          'Few coriander leaves, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: RADISH_MICROGREEN_CURD_TOSS_IMAGES.process,
        imageAlt: 'Making Radish Microgreen Curd Toss',
        contentType: 'steps',
        items: [
          'Clean the radish microgreens gently and dry them well.',
          'Whisk the curd until smooth.',
          'Add cucumber, onion, carrot, roasted cumin powder, black pepper, lemon juice, and salt.',
          'Mix the curd base first.',
          'Add radish microgreens only at the end.',
          'Toss gently so the greens stay fresh and crisp.',
          'Add pomegranate seeds if using.',
          'Serve immediately as a fresh curd side.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: RADISH_MICROGREEN_CURD_TOSS_IMAGES.howWeMakeIt,
        imageAlt: 'Radish Microgreen Curd Toss served',
        contentType: 'narrative',
        narrative: [
          'Radish Microgreen Curd Toss is built around contrast. Radish microgreens are naturally sharp and peppery, so instead of fighting that taste, we pair it with something cool. Thick curd does that job beautifully.',
          'We keep the microgreens raw because their freshness is the whole point. When radish microgreens are fresh, they give a clean pepper-like hit that wakes up a simple curd bowl.',
          'The cucumber adds cool crunch, while onion gives a little sharpness if someone likes a stronger taste. Roasted cumin is important because it gives the curd that familiar Indian raita flavour.',
          'We mix the curd base first before adding the microgreens. This matters because salt and lemon can soften delicate greens if they sit too long.',
          'Pomegranate seeds are optional, but they work nicely here. Their small sweet pop balances the peppery greens and makes the bowl look more inviting.',
        ],
      },
    ],
  },
  {
    id: 'mustard-microgreen-coconut-pachadi',
    title: 'Mustard Microgreen Coconut Pachadi',
    bestWith: 'Fresh Mustard Microgreens',
    categoryIds: ['microgreen-recipes', 'healthy-plates'],
    primaryCategoryLabel: 'Microgreen Recipes',
    cookingTime: '12 minutes',
    serves: '2–3 people',
    thumbnailSrc: MUSTARD_MICROGREEN_COCONUT_PACHADI_IMAGES.thumbnail,
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Mustard Microgreens in this recipe',
        imageSrc: MUSTARD_MICROGREEN_COCONUT_PACHADI_IMAGES.goodness,
        imageAlt: 'Mustard Microgreens sketch',
        contentType: 'nutrition',
        items: [
          'Mustard microgreens have a natural spicy bite, so they bring flavour even before adding chilli',
          'Their sharp taste works well with coconut because coconut softens the heat and makes the dish balanced',
          'They are best added fresh at the end so their flavour stays lively instead of becoming dull',
          'A small handful can make a simple pachadi taste brighter, fresher, and more interesting',
          'Their bold flavour suits Indian meals well, especially rice, dosa, idli, chapati, and millet plates',
          'This recipe lets mustard microgreens behave like the main flavour, not just a garnish',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: MUSTARD_MICROGREEN_COCONUT_PACHADI_IMAGES.ingredients,
        imageAlt: 'Ingredients for Mustard Microgreen Coconut Pachadi',
        contentType: 'ingredients',
        items: [
          '1½ cups fresh mustard microgreens',
          '½ cup fresh grated coconut',
          '2 tbsp roasted peanuts or roasted gram',
          '1 small green chilli',
          '½ tsp cumin seeds',
          '1 small garlic clove, optional',
          '1 tsp lemon juice or little tamarind water',
          'Salt as needed',
          '2–3 tbsp water, for grinding',
          '1 tsp oil (for tempering)',
          '½ tsp mustard seeds (for tempering)',
          '½ tsp urad dal, optional (for tempering)',
          '1 dry red chilli (for tempering)',
          'Curry leaves (for tempering)',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: MUSTARD_MICROGREEN_COCONUT_PACHADI_IMAGES.process,
        imageAlt: 'Making Mustard Microgreen Coconut Pachadi',
        contentType: 'steps',
        items: [
          'Clean the mustard microgreens gently and dry them well.',
          'Grind coconut, peanuts or roasted gram, green chilli, cumin, garlic, salt, and little water into a coarse paste.',
          'Transfer the paste to a bowl.',
          'Add lemon juice or a little tamarind water.',
          'Chop the mustard microgreens roughly if they are long.',
          'Mix the microgreens into the coconut paste only at the end.',
          'Heat oil for tempering.',
          'Add mustard seeds, urad dal, dry red chilli, and curry leaves.',
          'Pour the tempering over the pachadi.',
          'Mix gently and serve fresh.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: MUSTARD_MICROGREEN_COCONUT_PACHADI_IMAGES.howWeMakeIt,
        imageAlt: 'Mustard Microgreen Coconut Pachadi served',
        contentType: 'narrative',
        narrative: [
          'Mustard Microgreen Coconut Pachadi is all about balancing sharpness. Mustard microgreens have a natural spicy kick, almost like they are already carrying a little seasoning inside them. So we don\'t treat them like plain leaves. We build the recipe around their bold taste.',
          'The coconut base is what makes the dish friendly. Fresh coconut brings sweetness and softness, while roasted peanuts or roasted gram give body. We grind the coconut mixture first without the microgreens. If we grind mustard microgreens too much, their fresh bite can become flat and slightly harsh.',
          'Lemon juice or a little tamarind water gives brightness. Both work, but we should not add too much sourness because the mustard flavour should still lead.',
          'The tempering finishes the dish. Mustard seeds, curry leaves, dry chilli, and a little oil bring that warm aroma that makes pachadi feel complete.',
          'This pachadi works beautifully with hot rice, dosa, idli, chapati, millet dosa, or even as a side for curd rice.',
        ],
      },
    ],
  },
  {
    id: 'broccoli-microgreen-lemon-curd-dip',
    title: 'Broccoli Microgreen Lemon Curd Dip',
    bestWith: 'Fresh Broccoli Microgreens',
    categoryIds: ['microgreen-recipes', 'healthy-plates'],
    primaryCategoryLabel: 'Microgreen Recipes',
    cookingTime: '10 minutes',
    serves: '2–3 people',
    thumbnailSrc: BROCCOLI_MICROGREEN_LEMON_CURD_DIP_IMAGES.thumbnail,
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Broccoli Microgreens in this recipe',
        imageSrc: BROCCOLI_MICROGREEN_LEMON_CURD_DIP_IMAGES.goodness,
        imageAlt: 'Broccoli Microgreens goodness',
        contentType: 'nutrition',
        items: [
          'Broccoli microgreens have a mild, fresh taste, so they work well in a cool curd-based dip without becoming overpowering',
          'Their clean green flavour pairs nicely with lemon, garlic, pepper, and roasted cumin',
          'They are best used raw here because heat would reduce their freshness and delicate bite',
          'Thick curd gives the dip body, while the microgreens make it feel lighter and fresher',
          'This recipe is useful for people who want to use microgreens in a simple way beyond just sprinkling them on top',
          'It works well as a side for chapati, dosa, paratha, millet crackers, sandwiches, or vegetable sticks',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: BROCCOLI_MICROGREEN_LEMON_CURD_DIP_IMAGES.ingredients,
        imageAlt: 'Ingredients for Broccoli Microgreen Lemon Curd Dip',
        contentType: 'ingredients',
        items: [
          '1½ cups fresh broccoli microgreens',
          '1 cup thick curd or hung curd',
          '1 small garlic clove, grated',
          '1 tsp lemon juice',
          '¼ tsp black pepper powder',
          '¼ tsp roasted cumin powder',
          'Salt as needed',
          '1 tbsp finely chopped onion, optional',
          '1 tsp olive oil or cold-pressed oil, optional',
          'Few coriander leaves, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: BROCCOLI_MICROGREEN_LEMON_CURD_DIP_IMAGES.process,
        imageAlt: 'Making Broccoli Microgreen Lemon Curd Dip',
        contentType: 'steps',
        items: [
          'Clean the broccoli microgreens gently and dry them well.',
          'Chop the microgreens roughly if they are long.',
          'Whisk thick curd until smooth.',
          'Add grated garlic, lemon juice, pepper, roasted cumin powder, and salt.',
          'Mix the curd base first.',
          'Add broccoli microgreens only at the end.',
          'Fold gently so the greens stay fresh.',
          'Add onion or coriander if preferred.',
          'Serve fresh as a dip, spread, or side.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: BROCCOLI_MICROGREEN_LEMON_CURD_DIP_IMAGES.howWeMakeIt,
        imageAlt: 'Broccoli Microgreen Lemon Curd Dip served',
        contentType: 'narrative',
        narrative: [
          'Broccoli Microgreen Lemon Curd Dip is made for days when we want something fresh, cool, and easy. Broccoli microgreens are not as sharp as radish and not as spicy as mustard. They have a cleaner, gentler green taste.',
          'The curd is important here. Thick curd or hung curd gives the dip body, almost like a soft spread. If the curd is too watery, the dip becomes loose and the microgreens start floating instead of blending into it.',
          'Garlic is used very lightly. Just one small clove is enough to bring flavour without covering the microgreens. Lemon juice brightens the dip, black pepper gives a soft heat, and roasted cumin gives that familiar Indian curd-side taste.',
          'The microgreens go in only at the end. Salt and lemon can soften them if they sit too long. We mix the curd first, then gently fold the greens in so they stay fresh and slightly crisp.',
          'The final dip should feel creamy first, then fresh and lemony, with a gentle green bite from the broccoli microgreens.',
        ],
      },
    ],
  },
  {
    id: 'pea-shoot-garlic-sesame-toss',
    title: 'Pea Shoot Garlic Sesame Toss',
    bestWith: 'Fresh Pea Shoots',
    categoryIds: ['microgreen-recipes', 'healthy-plates'],
    primaryCategoryLabel: 'Microgreen Recipes',
    cookingTime: '10–14 minutes',
    serves: '2 people',
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Pea Shoots in this recipe',
        contentType: 'nutrition',
        items: [
          'Pea shoots have a naturally sweet, fresh taste, so they work well with mild garlic and sesame',
          'Their tender stems give a gentle crunch without feeling tough',
          'A very quick toss keeps their green freshness while making them softer and easier to pair with meals',
          'Sesame adds a nutty flavour that complements the mild sweetness of pea shoots',
          'This recipe is useful for people who want microgreens in a warm dish, not only in salads',
          'Pea shoots work well as a side with rice, noodles, chapati, eggs, or mushroom dishes',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        contentType: 'ingredients',
        items: [
          '2 cups fresh pea shoots',
          '4–5 garlic cloves, finely chopped',
          '1 tsp sesame seeds',
          '1 small green chilli, slit, optional',
          '½ tsp black pepper powder',
          '1 tsp lemon juice',
          'Salt as needed',
          '1 tbsp oil or butter',
          '1 tsp soy sauce, optional',
          'Spring onion greens, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        contentType: 'steps',
        items: [
          'Clean the pea shoots gently and dry them well.',
          'Trim any tough ends if needed.',
          'Heat oil or butter in a pan.',
          'Add sesame seeds and let them turn slightly aromatic.',
          'Add garlic and green chilli.',
          'Cook only until the garlic smells warm, not brown.',
          'Add pea shoots and toss quickly.',
          'Add salt, pepper, and soy sauce if using.',
          'Cook for only 1–2 minutes.',
          'Finish with lemon juice.',
          'Serve warm immediately.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Pea Shoot Garlic Sesame Toss is a very quick recipe, and that is exactly why it works. Pea shoots are tender, fresh, and slightly sweet, so we don\'t want to overcook them or bury them under heavy masala.',
          'We start with sesame seeds because they bring a gentle nuttiness. Garlic comes next, but we keep it light. Burnt garlic would make the whole dish bitter, so we cook it only until it smells good.',
          'The pea shoots go in only after the base is ready. They don\'t need long cooking. A quick toss is enough. They should relax in the pan, not collapse completely.',
          'A little black pepper gives warmth, and lemon juice at the end keeps the flavour bright. Soy sauce is optional; it gives a slightly savoury touch.',
          'The final dish should feel fresh, warm, lightly garlicky, and slightly nutty.',
        ],
      },
    ],
  },
  {
    id: 'amaranth-microgreen-curd-rice-bowl',
    title: 'Amaranth Microgreen Curd Rice Bowl',
    bestWith: 'Fresh Amaranth Microgreens',
    categoryIds: ['microgreen-recipes', 'healthy-plates'],
    primaryCategoryLabel: 'Microgreen Recipes',
    cookingTime: '10 minutes',
    serves: '2 people',
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Amaranth Microgreens in this recipe',
        contentType: 'nutrition',
        items: [
          'Amaranth microgreens have a soft texture and earthy taste, so they work well with cooling curd rice',
          'Their red and pink tones make a simple bowl look fresh and premium without needing heavy garnish',
          'They are best added raw at the end so their colour, softness, and fresh bite stay intact',
          'Their gentle flavour does not disturb the comfort taste of curd rice',
          'They pair well with cucumber, roasted peanuts, mustard tempering, and curry leaves',
          'This recipe is useful for making everyday curd rice feel fresher, lighter, and more colourful',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        contentType: 'ingredients',
        items: [
          '1½ cups fresh amaranth microgreens',
          '1½ cups cooked rice, cooled',
          '1 cup thick curd',
          '¼ cup milk or water, if needed',
          '½ cucumber, finely chopped',
          '2 tbsp roasted peanuts, lightly crushed',
          '1 green chilli, finely chopped, optional',
          'Salt as needed',
          '1 tsp oil (for tempering)',
          '½ tsp mustard seeds (for tempering)',
          '½ tsp urad dal, optional (for tempering)',
          '1 dry red chilli (for tempering)',
          'Curry leaves (for tempering)',
          'Pinch of asafoetida, optional (for tempering)',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        contentType: 'steps',
        items: [
          'Cool the cooked rice completely.',
          'Mix rice, curd, salt, and a little milk or water if needed.',
          'Add cucumber and green chilli.',
          'Clean the amaranth microgreens gently and dry them well.',
          'Prepare tempering with oil, mustard seeds, urad dal, dry chilli, curry leaves, and asafoetida.',
          'Let the tempering cool slightly.',
          'Mix the tempering into the curd rice.',
          'Add amaranth microgreens only at the end.',
          'Top with crushed roasted peanuts.',
          'Serve fresh, not too cold.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Amaranth Microgreen Curd Rice Bowl is built around comfort and colour. Curd rice is already soft, cooling, and familiar, so the microgreens should not make it complicated. Amaranth microgreens bring a gentle earthy taste and beautiful red-pink colour.',
          'We start with cooled rice because hot rice will make the curd split and can also soften the microgreens too much later. The curd should be thick enough to coat the rice, but not so thick that the bowl feels heavy.',
          'Cucumber adds a cool crunch, and the tempering gives the bowl its familiar South Indian smell. We let the tempering cool slightly before mixing, because very hot oil can dull the freshness of the curd and greens.',
          'The amaranth microgreens go in at the very end. We gently fold them into the bowl and keep some on top so the dish looks alive.',
          'Roasted peanuts finish the bowl with a little crunch and nuttiness.',
        ],
      },
    ],
  },
  {
    id: 'fenugreek-microgreen-moong-dal-kosambari',
    title: 'Fenugreek Microgreen Moong Dal Kosambari',
    bestWith: 'Fresh Fenugreek Microgreens',
    categoryIds: ['microgreen-recipes', 'healthy-plates'],
    primaryCategoryLabel: 'Microgreen Recipes',
    cookingTime: '45 minutes (includes soaking)',
    serves: '2–3 people',
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Fenugreek Microgreens in this recipe',
        contentType: 'nutrition',
        items: [
          'Fenugreek microgreens bring the familiar methi aroma in a softer, fresher form than mature methi leaves',
          'Their slight bitterness works well with soaked moong dal because the dal gives a mild, nutty balance',
          'Fresh coconut softens the sharpness and makes the kosambari feel fuller without making it heavy',
          'Lemon brightens the greens and keeps the flavour fresh instead of letting the bitterness dominate',
          'They are best added raw at the end so their aroma, colour, and gentle bite stay alive',
          'This recipe suits fenugreek microgreens because it respects their natural taste instead of hiding it',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        contentType: 'ingredients',
        items: [
          '1½ cups fresh fenugreek microgreens',
          '½ cup yellow moong dal',
          '¼ cup fresh grated coconut',
          '1 small cucumber, finely chopped',
          '1 green chilli, finely chopped',
          '1 tbsp lemon juice',
          'Salt as needed',
          'Fresh coriander leaves, optional',
          '1 tsp oil (for tempering)',
          '½ tsp mustard seeds (for tempering)',
          '½ tsp cumin seeds (for tempering)',
          '1 dry red chilli (for tempering)',
          'Curry leaves (for tempering)',
          'Pinch of asafoetida, optional (for tempering)',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        contentType: 'steps',
        items: [
          'Wash and soak yellow moong dal for 30 minutes.',
          'Drain the dal completely.',
          'Clean the fenugreek microgreens gently and dry them well.',
          'Mix soaked moong dal, cucumber, green chilli, coconut, lemon juice, and salt.',
          'Prepare tempering with oil, mustard seeds, cumin seeds, dry red chilli, curry leaves, and asafoetida.',
          'Let the tempering cool slightly.',
          'Add the tempering to the dal mixture.',
          'Add fenugreek microgreens only at the end.',
          'Toss gently without crushing the greens.',
          'Serve fresh as a light side dish.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Fenugreek Microgreen Moong Dal Kosambari is a fresh dish with a little character. Fenugreek microgreens are not bland greens. They have that gentle methi bitterness and aroma, but in a younger, fresher way.',
          'Moong dal does that beautifully. Once soaked, it becomes soft enough to eat but still has a nice bite. It brings a mild nuttiness that sits well with the fenugreek flavour. Coconut gives the dish a soft sweetness that rounds off the bitterness.',
          'The lemon is important. Without it, the fenugreek can feel a little flat. Lemon lifts the whole bowl and makes the microgreens taste fresh.',
          'The tempering gives the kosambari its familiar Indian finish. We let the tempering cool slightly before mixing. Very hot oil can soften the microgreens too quickly.',
          'The fenugreek microgreens go in last. The final dish should feel crunchy from dal, cool from cucumber, soft from coconut, and slightly bitter-fresh from the fenugreek microgreens.',
        ],
      },
    ],
  },
  {
    id: 'coriander-microgreen-coconut-chutney',
    title: 'Coriander Microgreen Fresh Coconut Chutney',
    bestWith: 'Fresh Coriander Microgreens',
    categoryIds: ['microgreen-recipes', 'healthy-plates'],
    primaryCategoryLabel: 'Microgreen Recipes',
    cookingTime: '10 minutes',
    serves: '2–3 people',
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Coriander Microgreens in this recipe',
        contentType: 'nutrition',
        items: [
          'Coriander microgreens bring the familiar coriander aroma in a softer, fresher form',
          'Their tender leaves and stems blend well into chutney without needing long grinding',
          'Fresh coconut gives body and mild sweetness, which balances the green flavour of the microgreens',
          'Lemon keeps the chutney bright and helps the coriander microgreens taste fresh instead of flat',
          'They are best used raw here because cooking would reduce their fresh aroma',
          'This recipe makes coriander microgreens the main ingredient, not just a finishing garnish',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        contentType: 'ingredients',
        items: [
          '1½ cups fresh coriander microgreens',
          '½ cup fresh grated coconut',
          '2 tbsp roasted gram or roasted peanuts',
          '1 green chilli',
          '½ inch ginger',
          '½ tsp cumin seeds',
          '1 tsp lemon juice',
          'Salt as needed',
          '2–4 tbsp water, for grinding',
          '1 tsp oil (for tempering)',
          '½ tsp mustard seeds (for tempering)',
          '½ tsp urad dal, optional (for tempering)',
          '1 dry red chilli (for tempering)',
          'Curry leaves (for tempering)',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        contentType: 'steps',
        items: [
          'Clean the coriander microgreens gently and dry them well.',
          'Add coconut, roasted gram or peanuts, green chilli, ginger, cumin, salt, and little water to a mixer.',
          'Grind into a coarse chutney base.',
          'Add coriander microgreens and pulse briefly.',
          'Do not over-grind after adding the microgreens.',
          'Add lemon juice and mix.',
          'Prepare tempering with oil, mustard seeds, urad dal, dry chilli, and curry leaves.',
          'Pour the tempering over the chutney.',
          'Serve fresh with dosa, idli, chapati, rice, or snacks.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Coriander Microgreen Fresh Coconut Chutney is made for people who already love coriander, but want something fresher and softer. Coriander microgreens have that familiar aroma, but they are more delicate than mature coriander leaves.',
          'The coconut gives the chutney its body. Without coconut, the microgreens can become too light and watery. Roasted gram or peanuts help thicken the chutney. Ginger gives a small warm kick, green chilli brings heat, and cumin adds that earthy chutney flavour.',
          'We grind the coconut base first. If we add coriander microgreens too early and grind them for too long, their fresh aroma becomes dull. So we make the base first, then add the microgreens and pulse only briefly.',
          'Lemon juice goes in after grinding. It brightens the chutney and keeps the coriander flavour awake.',
          'The final chutney should feel fresh, coconutty, lightly spicy, and aromatic.',
        ],
      },
    ],
  },
  {
    id: 'beetroot-microgreen-lemon-peanut-chaat',
    title: 'Beetroot Microgreen Lemon Peanut Chaat',
    bestWith: 'Fresh Beetroot Microgreens',
    categoryIds: ['microgreen-recipes', 'healthy-plates'],
    primaryCategoryLabel: 'Microgreen Recipes',
    cookingTime: '10–12 minutes',
    serves: '2 people',
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Beetroot Microgreens in this recipe',
        contentType: 'nutrition',
        items: [
          'Beetroot microgreens bring beautiful red-purple colour, so they make a simple chaat look fresh and premium',
          'Their mild earthy taste works well with lemon, cucumber, peanuts, and light chaat-style seasoning',
          'They are best used raw here because cooking can reduce their fresh look, soft bite, and natural colour appeal',
          'Their tender leaves and stems add fresh greens to the plate without making the dish feel heavy',
          'Roasted peanuts give crunch and body, which balances the softness of beetroot microgreens',
          'Lemon and black salt brighten the earthy flavour and make the microgreens feel lively instead of flat',
          'This recipe uses beetroot microgreens as the main fresh ingredient, not just as a decoration on top',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        contentType: 'ingredients',
        items: [
          '1½ cups fresh beetroot microgreens',
          '½ cucumber, finely chopped',
          '1 small onion, finely chopped',
          '2 tbsp roasted peanuts, lightly crushed',
          '1 tbsp pomegranate seeds, optional',
          '1 green chilli, finely chopped, optional',
          '1 tbsp lemon juice',
          '¼ tsp roasted cumin powder',
          '¼ tsp black pepper powder',
          'Pinch of black salt',
          'Salt as needed',
          'Fresh coriander leaves, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        contentType: 'steps',
        items: [
          'Clean the beetroot microgreens gently and dry them well.',
          'Chop cucumber, onion, green chilli, and coriander if using.',
          'Lightly crush the roasted peanuts.',
          'Mix cucumber, onion, green chilli, lemon juice, roasted cumin powder, black pepper, black salt, and regular salt.',
          'Add beetroot microgreens only at the end.',
          'Toss gently so the leaves and stems do not bruise.',
          'Add roasted peanuts and pomegranate seeds just before serving.',
          'Serve immediately while the microgreens are still fresh and bright.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Beetroot Microgreen Lemon Peanut Chaat is built around colour first. Beetroot microgreens have that fresh red-purple look, and we don\'t want to waste it by hiding them in a cooked dish. They should stay visible, fresh, and soft on the plate.',
          'The taste of beetroot microgreens is mild and slightly earthy, so we pair them with ingredients that lift that flavour. Cucumber brings cool crunch, onion gives a little sharpness, lemon adds brightness, and black salt gives that chaat-like edge.',
          'The peanuts are important. Beetroot microgreens are soft, so roasted peanuts give the dish a proper bite. They also bring a warm nutty flavour that makes the chaat feel more satisfying.',
          'We mix the seasoning with cucumber and onion first, then add the beetroot microgreens at the end. The final toss should be gentle, almost like we are dressing the greens, not crushing them.',
          'The finished chaat should look bright, taste fresh, and feel light but not empty.',
        ],
      },
    ],
  },
  {
    id: 'basil-microgreen-tomato-curd-spread',
    title: 'Basil Microgreen Tomato Curd Spread',
    bestWith: 'Fresh Basil Microgreens',
    categoryIds: ['microgreen-recipes', 'healthy-plates'],
    primaryCategoryLabel: 'Microgreen Recipes',
    cookingTime: '10 minutes',
    serves: '2–3 people',
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Basil Microgreens in this recipe',
        contentType: 'nutrition',
        items: [
          'Basil microgreens bring a fresh, sweet-herbal aroma that works beautifully with tomato and curd',
          'Their flavour is more delicate than mature basil leaves, so they are best used raw and added at the end',
          'They help make a simple curd spread taste fresher without needing heavy spice or strong dressing',
          'Tomato adds natural tang and juiciness, while thick curd gives the spread body and softness',
          'Basil microgreens work well in this recipe because their aroma lifts the whole dish without overpowering it',
          'This is a good way to use basil microgreens in everyday food, not only in pasta-style or restaurant plating',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        contentType: 'ingredients',
        items: [
          '1½ cups fresh basil microgreens',
          '1 cup thick curd or hung curd',
          '1 small tomato, deseeded and finely chopped',
          '1 small garlic clove, grated',
          '¼ tsp black pepper powder',
          '¼ tsp roasted cumin powder',
          '1 tsp lemon juice',
          'Salt as needed',
          '1 tsp olive oil or cold-pressed oil, optional',
          '1 tbsp finely chopped onion, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        contentType: 'steps',
        items: [
          'Clean the basil microgreens gently and dry them well.',
          'Deseed and finely chop the tomato.',
          'Whisk thick curd until smooth.',
          'Add tomato, garlic, pepper, roasted cumin powder, lemon juice, salt, and oil if using.',
          'Mix the curd base first.',
          'Add basil microgreens only at the end.',
          'Fold gently so the greens stay fresh and aromatic.',
          'Serve immediately as a spread, dip, or fresh side.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Basil Microgreen Tomato Curd Spread is made for freshness. Basil microgreens have a gentle sweet-herbal smell, and that is the main thing we want to protect. So we don\'t cook them, grind them heavily, or bury them under strong spices.',
          'The curd gives the recipe its body. Thick curd or hung curd works best because it holds the tomato and microgreens together like a proper spread.',
          'Tomato brings a fresh tang, but we remove the seeds first. That small step matters because tomato seeds and juice can make the spread watery. Garlic is used very lightly — just enough to give depth, not enough to dominate the basil.',
          'Black pepper gives a soft warmth, roasted cumin makes it feel familiar for Indian plates, and lemon juice brightens everything. The basil microgreens go in only at the end because their aroma is delicate.',
          'The final spread should feel cool from the curd, lightly tangy from tomato and lemon, and fresh from the basil microgreens.',
        ],
      },
    ],
  },
]
