import {
  BUTTON_MUSHROOM_BUTTER_MASALA_IMAGES,
  BUTTON_MUSHROOM_CHETTINAD_CURRY_IMAGES,
  BUTTON_MUSHROOM_GARLIC_MASALA_IMAGES,
  MILKY_MUSHROOM_COCONUT_KURMA_IMAGES,
  MILKY_MUSHROOM_PEPPER_FRY_IMAGES,
  WHITE_OYSTER_COCONUT_PEPPER_CURRY_IMAGES,
  WHITE_OYSTER_MUSHROOM_SUKKA_IMAGES,
  PINK_OYSTER_MUSHROOM_MASALA_ROAST_IMAGES,
  PINK_OYSTER_MUSHROOM_TAMARIND_CURRY_IMAGES,
  SHIITAKE_SOY_GARLIC_STIR_CURRY_IMAGES,
  LIONS_MANE_MUSHROOM_ROAST_IMAGES,
  CORDYCEPS_MUSHROOM_MILD_MASALA_IMAGES,
  SHIITAKE_MUSHROOM_PEPPER_MASALA_IMAGES,
} from '@/assets/Recipe Book'
import {
  NUTRITION_BUTTON_MUSHROOM_USDA,
  NUTRITION_LIONS_MANE_MUSHROOM,
  NUTRITION_OYSTER_MUSHROOM_MATVARETABELLEN,
  NUTRITION_OYSTER_MUSHROOM_USDA,
  NUTRITION_PINK_OYSTER_MUSHROOM,
  NUTRITION_SHIITAKE_MUSHROOM,
} from '@/constants/NUTRITION_PROFILES'
import type { RecipeData } from '@/types'

export const MUSHROOM_RECIPES: RecipeData[] = [
  {
    id: 'milky-mushroom-pepper-fry',
    title: 'Milky Mushroom Pepper Fry',
    bestWith: 'Fresh Milky Mushroom',
    categoryIds: ['mushroom-recipes', 'everyday-meals'],
    primaryCategoryLabel: 'Mushroom Recipes',
    cookingTime: '25 minutes',
    serves: '2–3 people',
    thumbnailSrc: MILKY_MUSHROOM_PEPPER_FRY_IMAGES.thumbnail,
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Milky Mushroom',
        imageSrc: MILKY_MUSHROOM_PEPPER_FRY_IMAGES.goodness,
        imageAlt: 'Milky Mushroom sketch',
        contentType: 'nutrition',
        items: [
          'Firm, meaty texture that holds well while cooking',
          'Mild taste that works beautifully with pepper and curry leaves',
          'Gives a satisfying bite without becoming too soft or mushy',
          'Suitable for dry fries, roasts, curries, and South Indian-style side dishes',
          'A good mushroom for people trying mushrooms for the first time because it blends well with familiar Indian flavours',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: MILKY_MUSHROOM_PEPPER_FRY_IMAGES.ingredients,
        imageAlt: 'Ingredients for Milky Mushroom Pepper Fry',
        contentType: 'ingredients',
        items: [
          '250 g milky mushrooms',
          '1 large onion, sliced',
          '1 green chilli, slit',
          '1 tsp ginger-garlic paste',
          '½ tsp turmeric powder',
          '1 tsp freshly crushed black pepper',
          '½ tsp coriander powder',
          '½ tsp garam masala',
          'Curry leaves',
          'Salt as needed',
          '2 tbsp oil or ghee',
          'Lemon juice, optional',
          'Fresh coriander leaves, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: MILKY_MUSHROOM_PEPPER_FRY_IMAGES.process,
        imageAlt: 'Making Milky Mushroom Pepper Fry',
        contentType: 'steps',
        items: [
          'Clean the milky mushrooms gently and trim the hard base if needed.',
          'Cut them into medium pieces.',
          'Heat oil or ghee in a pan.',
          'Add curry leaves, sliced onion, and green chilli.',
          'Fry until the onion turns soft and lightly golden.',
          'Add ginger-garlic paste and cook until the raw smell reduces.',
          'Add turmeric powder, coriander powder, salt, and the mushrooms.',
          'Cook on medium flame until the mushrooms release water.',
          'Continue cooking until the moisture reduces.',
          'Add crushed black pepper and garam masala near the end.',
          'Toss well until the mushrooms look lightly roasted and coated.',
          'Finish with lemon juice or coriander leaves if preferred.',
          'Serve hot with rice, chapati, dosa, or curd rice.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: MILKY_MUSHROOM_PEPPER_FRY_IMAGES.howWeMakeIt,
        imageAlt: 'Milky Mushroom Pepper Fry served hot',
        contentType: 'narrative',
        narrative: [
          'Milky Mushroom Pepper Fry works best when the mushroom is allowed to stay as the main bite of the dish. We don\'t cut it too small, because milky mushroom has a firm, meaty texture that deserves to be felt. Medium pieces are ideal — big enough to hold shape, small enough to catch the pepper, onion, and curry leaf flavour.',
          'We start with oil or ghee, curry leaves, onion, and green chilli. This gives the dish that familiar South Indian base before the mushrooms even enter the pan. The onions should soften and turn slightly golden, not too dark. Then the ginger-garlic paste goes in and cooks down until the raw smell settles.',
          'Once the mushrooms are added, they will release some moisture. That is normal. The trick is to let that water cook out slowly instead of rushing the dish. As the moisture reduces, the mushroom starts firming up again and the masala begins to cling to the pieces.',
          'Black pepper goes near the end because we want its heat to stay fresh and sharp. If pepper cooks for too long, it can become dull and slightly bitter. Added at the right time, it gives the dish warmth without overpowering the mushroom.',
          'The final pepper fry should be dry, glossy, and lightly roasted. The mushroom should feel firm when you bite into it, with the onion sweetness, curry leaf aroma, and pepper heat coming together. It should sit comfortably beside rice, chapati, dosa, or curd rice, but still feel like the main thing on the plate.',
        ],
      },
    ],
  },
  {
    id: 'milky-mushroom-coconut-kurma',
    title: 'Milky Mushroom Coconut Kurma',
    bestWith: 'Fresh Milky Mushroom',
    categoryIds: ['mushroom-recipes', 'everyday-meals'],
    primaryCategoryLabel: 'Mushroom Recipes',
    cookingTime: '30–35 minutes',
    serves: '3 people',
    thumbnailSrc: MILKY_MUSHROOM_COCONUT_KURMA_IMAGES.thumbnail,
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Milky Mushroom',
        imageSrc: MILKY_MUSHROOM_COCONUT_KURMA_IMAGES.goodness,
        imageAlt: 'Milky Mushroom sketch',
        contentType: 'nutrition',
        items: [
          'Firm texture that holds well in creamy gravies',
          'Mild flavour that blends smoothly with coconut and spices',
          'Gives the kurma a meaty bite without making it feel heavy',
          'Works well in both mild and medium-spiced dishes',
          'A good mushroom for family-style curries because it stays visible and satisfying in the gravy',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: MILKY_MUSHROOM_COCONUT_KURMA_IMAGES.ingredients,
        imageAlt: 'Ingredients for Milky Mushroom Coconut Kurma',
        contentType: 'ingredients',
        items: [
          '250 g milky mushrooms',
          '1 large onion, sliced',
          '1 tomato, chopped',
          '1 green chilli, slit',
          '1 tsp ginger-garlic paste',
          '½ tsp turmeric powder',
          '1 tsp coriander powder',
          '½ tsp cumin powder',
          '½ tsp garam masala',
          'Curry leaves',
          'Salt as needed',
          '2 tbsp oil',
          '¾ cup water, as needed',
          'Fresh coriander leaves, optional',
          '½ cup fresh grated coconut (for paste)',
          '8–10 cashews or 1 tbsp roasted gram (for paste)',
          '½ tsp fennel seeds (for paste)',
          '2 small cardamoms (for paste)',
          '1 small piece cinnamon (for paste)',
          '2 cloves (for paste)',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: MILKY_MUSHROOM_COCONUT_KURMA_IMAGES.process,
        imageAlt: 'Making Milky Mushroom Coconut Kurma',
        contentType: 'steps',
        items: [
          'Clean the milky mushrooms gently and trim the hard base if needed.',
          'Cut them into medium pieces.',
          'Grind coconut, cashews or roasted gram, fennel, cardamom, cinnamon, cloves, and a little water into a smooth paste.',
          'Heat oil in a pan.',
          'Add curry leaves, onion, and green chilli.',
          'Fry until the onion turns soft.',
          'Add ginger-garlic paste and cook until the raw smell reduces.',
          'Add tomato, turmeric, coriander powder, cumin powder, and salt.',
          'Cook until the tomato softens.',
          'Add the milky mushrooms and mix well.',
          'Add the coconut paste and water.',
          'Cover and cook until the mushrooms become tender.',
          'Simmer until the kurma turns creamy and medium-thick.',
          'Add garam masala near the end.',
          'Finish with coriander leaves if preferred.',
          'Serve hot with chapati, dosa, parotta, appam, idiyappam, or rice.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: MILKY_MUSHROOM_COCONUT_KURMA_IMAGES.howWeMakeIt,
        imageAlt: 'Milky Mushroom Coconut Kurma served',
        contentType: 'narrative',
        narrative: [
          'Milky Mushroom Coconut Kurma is a softer, creamier mushroom recipe. Unlike pepper fry or ghee roast, this one is not about sharp heat or roasting. It is about letting the mushroom sit inside a mild coconut gravy and slowly take in the flavour.',
          'We keep the milky mushrooms in medium pieces because kurma needs the mushroom to hold its place. The gravy is rich and smooth, so if the mushroom pieces are too small, they get lost. Milky mushroom works nicely here because it stays firm even after simmering.',
          'The coconut paste is the heart of this recipe. Fresh coconut gives body and sweetness, cashews or roasted gram help thicken the gravy, and fennel gives that gentle kurma aroma. Cardamom, cinnamon, and cloves should stay in the background. They should make the gravy smell warm, not overpower the mushroom.',
          'We first cook onion, green chilli, ginger-garlic, tomato, and basic spices to build the base. The tomato gives a small tang, but this should not become a tomato-heavy curry. Once the mushrooms go in, we let them mix with the masala before adding the coconut paste.',
          'After the coconut paste is added, the curry should simmer gently. High heat can make coconut gravies turn rough, so we keep it steady and let the kurma thicken slowly. The final dish should feel mild, comforting, and full. The mushroom gives bite, the coconut gives softness, and the spices give warmth.',
        ],
      },
    ],
  },
  {
    id: 'button-mushroom-butter-masala',
    title: 'Button Mushroom Butter Masala',
    bestWith: 'Fresh Button Mushroom',
    categoryIds: ['mushroom-recipes', 'everyday-meals'],
    primaryCategoryLabel: 'Mushroom Recipes',
    cookingTime: '30–35 minutes',
    serves: '3 people',
    thumbnailSrc: BUTTON_MUSHROOM_BUTTER_MASALA_IMAGES.thumbnail,
    nutritionProfiles: [NUTRITION_BUTTON_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Button Mushroom',
        imageSrc: BUTTON_MUSHROOM_BUTTER_MASALA_IMAGES.goodness,
        imageAlt: 'Fresh Button Mushroom',
        contentType: 'nutrition',
        items: [
          'Soft, tender texture that works beautifully in creamy gravies',
          'Mild flavour that absorbs tomato, butter, and spice well',
          'Naturally low in calories before cooking',
          'Naturally low in fat and cholesterol-free before cooking',
          'Provides useful nutrients like potassium, selenium, copper, riboflavin, niacin, and pantothenic acid',
          'Easy mushroom for first-time mushroom eaters because the taste is gentle and familiar in Indian gravies',
          'Works well in rich curries without needing heavy masala to hide the mushroom',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: BUTTON_MUSHROOM_BUTTER_MASALA_IMAGES.ingredients,
        imageAlt: 'Ingredients for Button Mushroom Butter Masala',
        contentType: 'ingredients',
        items: [
          '250 g button mushrooms',
          '2 medium onions, chopped',
          '3 medium tomatoes, chopped or pureed',
          '8–10 cashews, soaked',
          '1 tsp ginger-garlic paste',
          '1 tsp red chilli powder',
          '½ tsp turmeric powder',
          '1 tsp coriander powder',
          '½ tsp cumin powder',
          '½ tsp garam masala',
          '1 tbsp butter',
          '1 tbsp oil',
          '2 tbsp fresh cream or thick curd',
          '½ tsp kasuri methi, crushed',
          'Salt as needed',
          '½ cup water, as needed',
          'Fresh coriander leaves, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: BUTTON_MUSHROOM_BUTTER_MASALA_IMAGES.process,
        imageAlt: 'Making Button Mushroom Butter Masala',
        contentType: 'steps',
        items: [
          'Clean the button mushrooms gently.',
          'Cut them into halves or quarters depending on size.',
          'Heat oil and butter in a pan.',
          'Add onions and cook until soft.',
          'Add ginger-garlic paste and cook until the raw smell reduces.',
          'Add tomatoes, cashews, turmeric, chilli powder, coriander powder, cumin powder, and salt.',
          'Cook until the tomatoes soften and the masala thickens.',
          'Cool slightly and blend into a smooth gravy.',
          'Add the gravy back to the pan with a little water.',
          'Add button mushrooms and cook until tender.',
          'Add garam masala and crushed kasuri methi near the end.',
          'Finish with cream or thick curd.',
          'Serve hot with chapati, naan, parotta, jeera rice, or pulao.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: BUTTON_MUSHROOM_BUTTER_MASALA_IMAGES.howWeMakeIt,
        imageAlt: 'Button Mushroom Butter Masala served',
        contentType: 'narrative',
        narrative: [
          'Button Mushroom Butter Masala is the kind of curry that makes mushrooms feel familiar even to someone who usually chooses paneer or chicken gravy. Button mushrooms have a soft, clean bite, and they sit very comfortably inside a buttery tomato masala.',
          'We usually cut the mushrooms into halves or quarters instead of slicing them too thin. A button mushroom should still feel like a mushroom when you bite into it. If it is sliced too thin, it disappears into the gravy.',
          'The gravy starts with onion, tomato, ginger-garlic, cashews, and spices. The onions give body, the tomatoes bring colour and slight tang, and the cashews make the gravy smooth without making it too heavy.',
          'Once the gravy is smooth, the button mushrooms go in. They cook quickly, so we don\'t need to boil them for too long. They should become tender but not rubbery. The gravy should coat them well.',
          'Kasuri methi goes near the end because its aroma is delicate. A little cream or thick curd finishes the dish and softens the spice. The final curry should feel rich, smooth, and comforting.',
        ],
      },
    ],
  },
  {
    id: 'button-mushroom-garlic-masala',
    title: 'Button Mushroom Garlic Masala',
    bestWith: 'Fresh Button Mushroom',
    categoryIds: ['mushroom-recipes', 'everyday-meals'],
    primaryCategoryLabel: 'Mushroom Recipes',
    cookingTime: '25–30 minutes',
    serves: '2–3 people',
    thumbnailSrc: BUTTON_MUSHROOM_GARLIC_MASALA_IMAGES.thumbnail,
    nutritionProfiles: [NUTRITION_BUTTON_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Button Mushroom',
        imageSrc: BUTTON_MUSHROOM_GARLIC_MASALA_IMAGES.goodness,
        imageAlt: 'Button Mushroom sketch',
        contentType: 'nutrition',
        items: [
          'Soft, tender mushroom with a clean bite',
          'Mild flavour that takes garlic and spice very well',
          'Naturally low in calories before cooking',
          'Naturally low in fat and cholesterol-free before cooking',
          'Works well in both dry masala and semi-gravy style recipes',
          'A familiar mushroom variety for customers who are new to mushroom cooking',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: BUTTON_MUSHROOM_GARLIC_MASALA_IMAGES.ingredients,
        imageAlt: 'Ingredients for Button Mushroom Garlic Masala',
        contentType: 'ingredients',
        items: [
          '250 g button mushrooms',
          '1 large onion, finely chopped',
          '8–10 garlic cloves, finely chopped or crushed',
          '1 green chilli, slit',
          '1 small tomato, finely chopped',
          '½ tsp turmeric powder',
          '1 tsp red chilli powder',
          '1 tsp coriander powder',
          '½ tsp cumin powder',
          '½ tsp black pepper powder',
          '½ tsp garam masala',
          'Curry leaves or coriander leaves',
          'Salt as needed',
          '2 tbsp oil',
          '¼ cup water, only if needed',
          'Lemon juice, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: BUTTON_MUSHROOM_GARLIC_MASALA_IMAGES.process,
        imageAlt: 'Making Button Mushroom Garlic Masala',
        contentType: 'steps',
        items: [
          'Clean the button mushrooms gently.',
          'Cut them into halves or quarters depending on size.',
          'Heat oil in a pan.',
          'Add garlic and cook until aromatic, not dark brown.',
          'Add onion and green chilli.',
          'Fry until the onion turns soft and lightly golden.',
          'Add tomato, turmeric, chilli powder, coriander powder, cumin powder, pepper powder, and salt.',
          'Cook until the tomato softens and the masala thickens.',
          'Add button mushrooms and mix well.',
          'Cook on medium flame until the mushrooms release moisture.',
          'Continue cooking until the masala coats the mushrooms well.',
          'Add a splash of water only if you want a softer semi-gravy.',
          'Add garam masala near the end.',
          'Finish with coriander leaves or lemon juice if preferred.',
          'Serve hot with chapati, dosa, parotta, rice, or curd rice.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: BUTTON_MUSHROOM_GARLIC_MASALA_IMAGES.howWeMakeIt,
        imageAlt: 'Button Mushroom Garlic Masala served',
        contentType: 'narrative',
        narrative: [
          'Button Mushroom Garlic Masala is for the days when we want the mushroom to taste bold, but not complicated. Garlic is the main character here, and button mushroom is a good match for it because the mushroom is mild, soft, and ready to take in strong flavours.',
          'We cut the button mushrooms into halves or quarters, depending on their size. For this recipe, we want each mushroom piece to stay visible and give a soft bite when eaten with rice or chapati.',
          'The garlic goes into the oil first, but we don\'t burn it. Garlic should smell warm and slightly sweet, not bitter. Once it becomes aromatic, onion and green chilli go in. The onion gives body to the masala, while the green chilli gives a fresh heat.',
          'Tomato is used only to bring a little softness and tang. This is not a tomato-heavy curry like butter masala. When the mushrooms enter the pan, they first soften and release water. We let that moisture reduce so the masala can grip the mushroom properly.',
          'The final dish should smell clearly of garlic, but the mushroom should still come through. It should be spicy, warm, slightly glossy, and comfortable enough for everyday meals.',
        ],
      },
    ],
  },
  {
    id: 'button-mushroom-chettinad-curry',
    title: 'Button Mushroom Chettinad Curry',
    bestWith: 'Fresh Button Mushroom',
    categoryIds: ['mushroom-recipes', 'everyday-meals'],
    primaryCategoryLabel: 'Mushroom Recipes',
    cookingTime: '35 minutes',
    serves: '3 people',
    thumbnailSrc: BUTTON_MUSHROOM_CHETTINAD_CURRY_IMAGES.thumbnail,
    nutritionProfiles: [NUTRITION_BUTTON_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Button Mushroom in this recipe',
        imageSrc: BUTTON_MUSHROOM_CHETTINAD_CURRY_IMAGES.goodness,
        imageAlt: 'Button Mushroom sketch',
        contentType: 'nutrition',
        items: [
          'Button mushrooms are mild and soft, so they balance well with the strong roasted spices used in Chettinad-style curry',
          'Their tender bite works nicely in a thick masala because they absorb flavour without becoming too heavy',
          'Since raw button mushrooms are naturally low in calories and fat, the richness of this dish mainly comes from the coconut, oil, and spices added while cooking',
          'Button mushrooms contain useful nutrients like potassium, copper, selenium, riboflavin, niacin, and pantothenic acid',
          'They cook quickly, which helps this curry develop flavour without needing a long cooking time',
          'Their gentle taste makes this recipe a good way to introduce bold South Indian flavours without the mushroom feeling too strong or unfamiliar',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: BUTTON_MUSHROOM_CHETTINAD_CURRY_IMAGES.ingredients,
        imageAlt: 'Ingredients for Button Mushroom Chettinad Curry',
        contentType: 'ingredients',
        items: [
          '250 g button mushrooms',
          '1 large onion, finely chopped',
          '1 tomato, finely chopped',
          '1 tsp ginger-garlic paste',
          '1 green chilli, slit',
          'Curry leaves',
          '½ tsp turmeric powder',
          '1 tsp red chilli powder',
          'Salt as needed',
          '2 tbsp oil',
          '½ cup water, as needed',
          'Fresh coriander leaves, optional',
          '1 tbsp coriander seeds (for Chettinad masala)',
          '1 tsp fennel seeds (for Chettinad masala)',
          '½ tsp cumin seeds (for Chettinad masala)',
          '½ tsp black pepper (for Chettinad masala)',
          '3–4 dry red chillies (for Chettinad masala)',
          '1 small piece cinnamon (for Chettinad masala)',
          '2 cloves (for Chettinad masala)',
          '1 cardamom (for Chettinad masala)',
          '2 tbsp grated coconut (for Chettinad masala)',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: BUTTON_MUSHROOM_CHETTINAD_CURRY_IMAGES.process,
        imageAlt: 'Making Button Mushroom Chettinad Curry',
        contentType: 'steps',
        items: [
          'Clean the button mushrooms gently.',
          'Cut them into halves or quarters depending on size.',
          'Dry roast coriander seeds, fennel, cumin, pepper, dry red chillies, cinnamon, cloves, cardamom, and coconut.',
          'Cool the roasted mixture and grind it into a coarse or smooth masala paste with little water.',
          'Heat oil in a pan.',
          'Add curry leaves, onion, and green chilli.',
          'Fry until the onion turns soft and lightly golden.',
          'Add ginger-garlic paste and cook until the raw smell reduces.',
          'Add tomato, turmeric, chilli powder, and salt.',
          'Cook until the tomato softens and the masala thickens.',
          'Add the button mushrooms and mix well.',
          'Add the ground Chettinad masala and a little water.',
          'Cover and cook until the mushrooms become tender.',
          'Simmer until the curry turns thick and aromatic.',
          'Finish with coriander leaves if preferred.',
          'Serve hot with rice, chapati, dosa, parotta, or idiyappam.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: BUTTON_MUSHROOM_CHETTINAD_CURRY_IMAGES.howWeMakeIt,
        imageAlt: 'Button Mushroom Chettinad Curry served',
        contentType: 'narrative',
        narrative: [
          'Button Mushroom Chettinad Curry is not meant to be shy. This is a stronger mushroom curry, built around roasted spices, coconut, pepper, and curry leaves. Button mushrooms work well here because they are mild enough to carry the Chettinad masala without clashing with it.',
          'The Chettinad masala is where the dish gets its character. Coriander seeds give body, fennel gives a mild sweetness, cumin gives earthiness, pepper gives warmth, and dry red chillies bring heat. The coconut helps round everything off so the curry feels deep and full.',
          'We roast these ingredients before grinding because roasting wakes up the aroma. The kitchen should start smelling like something serious is about to happen.',
          'The onion and tomato base keeps the curry grounded. Once this cooks down, the button mushrooms go in and start releasing a little moisture. That moisture helps the Chettinad paste settle into the curry instead of staying raw or powdery.',
          'We simmer it only until the mushrooms turn tender and the curry becomes thick. The final curry should be dark, warm, peppery, and aromatic, with soft mushroom pieces sitting inside a thick roasted masala.',
        ],
      },
    ],
  },
  {
    id: 'white-oyster-mushroom-sukka',
    title: 'White Oyster Mushroom Sukka',
    bestWith: 'Fresh White Oyster Mushroom',
    categoryIds: ['mushroom-recipes', 'everyday-meals'],
    primaryCategoryLabel: 'Mushroom Recipes',
    cookingTime: '25–30 minutes',
    serves: '2–3 people',
    thumbnailSrc: WHITE_OYSTER_MUSHROOM_SUKKA_IMAGES.thumbnail,
    nutritionProfiles: [NUTRITION_OYSTER_MUSHROOM_MATVARETABELLEN],
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of White Oyster Mushroom in this recipe',
        imageSrc: WHITE_OYSTER_MUSHROOM_SUKKA_IMAGES.goodness,
        imageAlt: 'White Oyster Mushroom sketch',
        contentType: 'nutrition',
        items: [
          'White oyster mushrooms are soft and quick-cooking, so they work well in a dry sukka without needing long simmering',
          'Their thin, layered shape catches coconut, pepper, curry leaves, and roasted masala beautifully',
          'Raw oyster mushrooms are naturally low in calories and fat, so the richness of this recipe mostly comes from coconut and oil',
          'They contain useful nutrients such as fibre, potassium, phosphorus, niacin, riboflavin, and pantothenic acid',
          'Their light texture keeps this sukka from feeling too heavy, even when cooked with coconut and spices',
          'They are good for people who want a mushroom dish with strong flavour but still a soft, easy bite',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: WHITE_OYSTER_MUSHROOM_SUKKA_IMAGES.ingredients,
        imageAlt: 'Ingredients for White Oyster Mushroom Sukka',
        contentType: 'ingredients',
        items: [
          '250 g white oyster mushrooms',
          '1 large onion, finely sliced',
          '2 green chillies, slit',
          '1 tsp ginger-garlic paste',
          '½ tsp turmeric powder',
          '1 tsp red chilli powder',
          '½ tsp black pepper powder',
          '1 tsp coriander powder',
          '½ tsp cumin powder',
          '½ cup fresh grated coconut',
          'Curry leaves',
          'Salt as needed',
          '2 tbsp oil',
          'Fresh coriander leaves, optional',
          'Lemon juice, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: WHITE_OYSTER_MUSHROOM_SUKKA_IMAGES.process,
        imageAlt: 'Making White Oyster Mushroom Sukka',
        contentType: 'steps',
        items: [
          'Clean the oyster mushrooms gently.',
          'Tear them into medium strips by hand.',
          'Heat oil in a pan.',
          'Add curry leaves, onion, and green chillies.',
          'Fry until the onion turns soft and lightly golden.',
          'Add ginger-garlic paste and cook until the raw smell reduces.',
          'Add turmeric, chilli powder, coriander powder, cumin powder, pepper powder, and salt.',
          'Add the oyster mushrooms and mix gently.',
          'Cook on medium flame until the mushrooms release moisture.',
          'Continue cooking until the moisture reduces.',
          'Add grated coconut and toss well.',
          'Roast for a few minutes until the coconut coats the mushrooms.',
          'Finish with coriander leaves or lemon juice if preferred.',
          'Serve hot with rice, chapati, dosa, or rasam rice.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: WHITE_OYSTER_MUSHROOM_SUKKA_IMAGES.howWeMakeIt,
        imageAlt: 'White Oyster Mushroom Sukka served',
        contentType: 'narrative',
        narrative: [
          'White Oyster Mushroom Sukka is a dry mushroom dish, but it should never feel dry in the mouth. The idea is to let the oyster mushroom stay soft while the coconut and spices cling to its edges. Oyster mushrooms are delicate, so we don\'t chop them harshly. We tear them by hand into medium strips, keeping their natural shape.',
          'The base starts with curry leaves, onion, and green chilli. Ginger-garlic paste adds depth, but we cook it until the raw sharpness goes away. Since oyster mushroom has a mild flavour, raw garlic can dominate it if we rush this part.',
          'The spices stay simple: chilli for heat, coriander for body, cumin for earthiness, turmeric for colour, and pepper for warmth. Once the mushrooms go in, they soften quickly and release moisture. We let that moisture reduce slowly so the masala can sit properly on the mushroom.',
          'Grated coconut goes near the end. If we add it too early, it can become heavy and lose its fresh sweetness. Added at the right time, it coats the oyster mushroom lightly and gives the dish that sukka-style finish.',
          'The final dish should be dry enough to serve as a side, but still juicy when you bite into the mushroom. It should feel homely, warm, and slightly rustic.',
        ],
      },
    ],
  },
  {
    id: 'white-oyster-mushroom-coconut-pepper-curry',
    title: 'White Oyster Mushroom Coconut Pepper Curry',
    bestWith: 'Fresh White Oyster Mushroom',
    categoryIds: ['mushroom-recipes', 'everyday-meals'],
    primaryCategoryLabel: 'Mushroom Recipes',
    cookingTime: '30 minutes',
    serves: '3 people',
    thumbnailSrc: WHITE_OYSTER_COCONUT_PEPPER_CURRY_IMAGES.thumbnail,
    nutritionProfiles: [NUTRITION_OYSTER_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of White Oyster Mushroom in this recipe',
        imageSrc: WHITE_OYSTER_COCONUT_PEPPER_CURRY_IMAGES.goodness,
        imageAlt: 'White Oyster Mushroom sketch',
        contentType: 'nutrition',
        items: [
          'White oyster mushrooms have a soft, layered texture that absorbs coconut and pepper flavours quickly',
          'Their mild taste balances well with black pepper, curry leaves, and coconut without becoming too strong',
          'Raw oyster mushrooms are naturally low in fat, so the richness in this curry mainly comes from coconut and oil',
          'They provide fibre, protein, potassium, phosphorus, niacin, riboflavin, pantothenic acid, and choline',
          'Because oyster mushrooms cook fast, this curry gets good flavour without long cooking or heavy masala',
          'Their soft bite makes this dish feel comforting, while the pepper keeps it warm and lively',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: WHITE_OYSTER_COCONUT_PEPPER_CURRY_IMAGES.ingredients,
        imageAlt: 'Ingredients for White Oyster Mushroom Coconut Pepper Curry',
        contentType: 'ingredients',
        items: [
          '250 g white oyster mushrooms',
          '1 large onion, finely sliced',
          '1 small tomato, chopped',
          '1 green chilli, slit',
          '1 tsp ginger-garlic paste',
          '½ tsp turmeric powder',
          '1 tsp coriander powder',
          '½ tsp cumin powder',
          '1 tsp freshly crushed black pepper',
          '½ cup fresh grated coconut',
          'Curry leaves',
          'Salt as needed',
          '2 tbsp oil',
          '¾ cup water, as needed',
          'Fresh coriander leaves, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: WHITE_OYSTER_COCONUT_PEPPER_CURRY_IMAGES.process,
        imageAlt: 'Making White Oyster Mushroom Coconut Pepper Curry',
        contentType: 'steps',
        items: [
          'Clean the oyster mushrooms gently.',
          'Tear them into medium strips by hand.',
          'Grind grated coconut with a little water into a coarse or smooth paste.',
          'Heat oil in a pan.',
          'Add curry leaves, onion, and green chilli.',
          'Fry until the onion turns soft.',
          'Add ginger-garlic paste and cook until the raw smell reduces.',
          'Add tomato, turmeric, coriander powder, cumin powder, and salt.',
          'Cook until the tomato softens.',
          'Add oyster mushrooms and mix gently.',
          'Cook until the mushrooms release moisture and start softening.',
          'Add coconut paste and water.',
          'Simmer gently until the curry becomes medium-thick.',
          'Add crushed black pepper near the end.',
          'Finish with coriander leaves if preferred.',
          'Serve hot with rice, chapati, dosa, appam, or idiyappam.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: WHITE_OYSTER_COCONUT_PEPPER_CURRY_IMAGES.howWeMakeIt,
        imageAlt: 'White Oyster Mushroom Coconut Pepper Curry served',
        contentType: 'narrative',
        narrative: [
          'White Oyster Mushroom Coconut Pepper Curry is softer than a sukka and warmer than a plain coconut curry. The mushroom brings the light bite, coconut brings the body, and pepper gives the dish its quiet heat. It should feel comforting first, then slowly warm at the back of the throat.',
          'We tear the oyster mushrooms by hand because their natural layers are part of the dish. The curry starts with curry leaves, onion, and green chilli. Ginger-garlic paste adds depth, while tomato gives just a little softness and tang.',
          'The coconut paste goes in after the mushrooms begin to soften. Once coconut is added, we keep the flame gentle. Coconut gravies do better with patience; too much heat can make them rough instead of smooth.',
          'Pepper goes near the end because we want it fresh and warm, not bitter. Crushed black pepper gives a better bite than fine powder. It sits on the mushroom, mixes into the coconut, and gives the curry that homely pepper heat.',
          'The final curry should be medium-thick, not watery. The oyster mushroom should stay soft, the coconut should feel gentle, and the pepper should make the dish feel alive.',
        ],
      },
    ],
  },
  {
    id: 'pink-oyster-mushroom-masala-roast',
    title: 'Pink Oyster Mushroom Masala Roast',
    bestWith: 'Fresh Pink Oyster Mushroom',
    categoryIds: ['mushroom-recipes', 'everyday-meals'],
    primaryCategoryLabel: 'Mushroom Recipes',
    cookingTime: '25–30 minutes',
    serves: '2–3 people',
    thumbnailSrc: PINK_OYSTER_MUSHROOM_MASALA_ROAST_IMAGES.thumbnail,
    nutritionProfiles: [NUTRITION_PINK_OYSTER_MUSHROOM],
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Pink Oyster Mushroom in this recipe',
        imageSrc: PINK_OYSTER_MUSHROOM_MASALA_ROAST_IMAGES.goodness,
        imageAlt: 'Pink Oyster Mushroom sketch',
        contentType: 'nutrition',
        items: [
          'Pink oyster mushrooms are soft and delicate, so they roast quickly without needing long cooking',
          'Their layered shape catches onion, curry leaves, chilli, and masala well, giving flavour in every bite',
          'Raw oyster mushrooms are naturally low in fat, so the richness of this roast mainly comes from the oil and spice coating',
          'Oyster mushrooms provide fibre, protein, potassium, phosphorus, niacin, riboflavin, pantothenic acid, and choline',
          'Their light texture keeps the roast from feeling too heavy, even when cooked with bold masala',
          'Pink oyster mushrooms work well in this recipe because they can turn lightly crisp at the edges while staying soft inside',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: PINK_OYSTER_MUSHROOM_MASALA_ROAST_IMAGES.ingredients,
        imageAlt: 'Ingredients for Pink Oyster Mushroom Masala Roast',
        contentType: 'ingredients',
        items: [
          '250 g pink oyster mushrooms',
          '1 large onion, sliced',
          '1 green chilli, slit',
          '1 tsp ginger-garlic paste',
          '½ tsp turmeric powder',
          '1 tsp red chilli powder',
          '1 tsp coriander powder',
          '½ tsp cumin powder',
          '½ tsp black pepper powder',
          '½ tsp garam masala',
          'Curry leaves',
          'Salt as needed',
          '2 tbsp oil',
          '1 tsp lemon juice, optional',
          'Fresh coriander leaves, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: PINK_OYSTER_MUSHROOM_MASALA_ROAST_IMAGES.process,
        imageAlt: 'Making Pink Oyster Mushroom Masala Roast',
        contentType: 'steps',
        items: [
          'Clean the pink oyster mushrooms gently.',
          'Tear them into medium strips by hand.',
          'Heat oil in a pan.',
          'Add curry leaves, onion, and green chilli.',
          'Fry until the onion turns soft and lightly golden.',
          'Add ginger-garlic paste and cook until the raw smell reduces.',
          'Add turmeric, chilli powder, coriander powder, cumin powder, pepper powder, and salt.',
          'Add the pink oyster mushrooms and mix gently.',
          'Cook on medium flame until the mushrooms release moisture.',
          'Continue cooking until the moisture reduces.',
          'Roast until the mushroom edges turn slightly crisp.',
          'Add garam masala near the end.',
          'Finish with lemon juice or coriander leaves if preferred.',
          'Serve hot with rice, chapati, dosa, or curd rice.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: PINK_OYSTER_MUSHROOM_MASALA_ROAST_IMAGES.howWeMakeIt,
        imageAlt: 'Pink Oyster Mushroom Masala Roast served',
        contentType: 'narrative',
        narrative: [
          'Pink Oyster Mushroom Masala Roast is a dish where we want the mushroom to stay light but still feel full of flavour. Pink oyster mushrooms are delicate, so we don\'t chop them aggressively. We tear them by hand into medium strips, keeping their natural folds and edges.',
          'The base starts with curry leaves, onion, and green chilli. The onion gives a little sweetness, the curry leaves bring that warm South Indian aroma, and the chilli gives a fresh heat. Ginger-garlic paste goes in after the onion softens.',
          'The spices are kept bold but not too heavy. When the pink oyster mushrooms go in, they soften quickly and release a little moisture. We let that moisture reduce instead of rushing the roast.',
          'This is the important part: oyster mushrooms should not be overcooked until they become flat and lifeless. We cook them only until the masala grips the mushroom and the edges start turning slightly crisp. That gives the dish a nice contrast — soft inside, lightly roasted outside.',
          'The final roast should look dry, glossy, and lightly crisp at the edges. It should taste spicy, warm, and satisfying, while still keeping the natural softness of pink oyster mushroom.',
        ],
      },
    ],
  },
  {
    id: 'pink-oyster-mushroom-tamarind-curry',
    title: 'Pink Oyster Mushroom Tamarind Curry',
    bestWith: 'Fresh Pink Oyster Mushroom',
    categoryIds: ['mushroom-recipes', 'everyday-meals'],
    primaryCategoryLabel: 'Mushroom Recipes',
    cookingTime: '30 minutes',
    serves: '3 people',
    thumbnailSrc: PINK_OYSTER_MUSHROOM_TAMARIND_CURRY_IMAGES.thumbnail,
    nutritionProfiles: [NUTRITION_PINK_OYSTER_MUSHROOM],
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Pink Oyster Mushroom in this recipe',
        imageSrc: PINK_OYSTER_MUSHROOM_TAMARIND_CURRY_IMAGES.goodness,
        imageAlt: 'Pink Oyster Mushroom sketch',
        contentType: 'nutrition',
        items: [
          'Pink oyster mushrooms have a soft, layered texture that absorbs tangy tamarind gravy quickly.',
          'Their mild flavour balances well with tamarind, chilli, curry leaves, and garlic without becoming overpowering.',
          'Since oyster mushrooms are naturally low in fat before cooking, the curry can feel light even with a bold, spicy gravy.',
          'Oyster mushrooms bring useful nutrients like fibre, protein, potassium, phosphorus, niacin, riboflavin, pantothenic acid, and choline.',
          'Their delicate texture makes this curry cook faster than many vegetable gravies.',
          'The slight chew of oyster mushroom works well with tamarind because the mushroom softens while still holding enough bite in the curry.',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: PINK_OYSTER_MUSHROOM_TAMARIND_CURRY_IMAGES.ingredients,
        imageAlt: 'Ingredients for Pink Oyster Mushroom Tamarind Curry',
        contentType: 'ingredients',
        items: [
          '250 g pink oyster mushrooms',
          '1 large onion, finely sliced',
          '1 small tomato, chopped',
          '4–5 garlic cloves, crushed',
          '1 green chilli, slit',
          '1 small lemon-sized tamarind ball, soaked in warm water',
          '½ tsp turmeric powder',
          '1 tsp red chilli powder',
          '1½ tsp coriander powder',
          '½ tsp cumin powder',
          '½ tsp black pepper powder',
          '½ tsp mustard seeds',
          '½ tsp fenugreek seeds',
          'Curry leaves',
          'Salt as needed',
          '2 tbsp oil',
          '1 cup water, as needed',
          'Fresh coriander leaves, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: PINK_OYSTER_MUSHROOM_TAMARIND_CURRY_IMAGES.process,
        imageAlt: 'Making Pink Oyster Mushroom Tamarind Curry',
        contentType: 'steps',
        items: [
          'Clean the pink oyster mushrooms gently.',
          'Tear them into medium strips by hand.',
          'Soak tamarind in warm water and extract the juice.',
          'Heat oil in a pan.',
          'Add mustard seeds and let them crackle.',
          'Add fenugreek seeds, curry leaves, garlic, onion, and green chilli.',
          'Fry until the onion turns soft.',
          'Add tomato, turmeric, chilli powder, coriander powder, cumin powder, pepper powder, and salt.',
          'Cook until the tomato softens and the masala thickens.',
          'Add pink oyster mushrooms and mix gently.',
          'Cook until the mushrooms release moisture and soften.',
          'Add tamarind extract and water.',
          'Simmer until the curry becomes slightly thick and the raw tamarind sharpness settles.',
          'Adjust salt and spice if needed.',
          'Finish with coriander leaves if preferred.',
          'Serve hot with rice, dosa, idli, chapati, or ragi sangati.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: PINK_OYSTER_MUSHROOM_TAMARIND_CURRY_IMAGES.howWeMakeIt,
        imageAlt: 'Pink Oyster Mushroom Tamarind Curry served',
        contentType: 'narrative',
        narrative: [
          'Pink Oyster Mushroom Tamarind Curry is built around contrast. The mushroom is soft and delicate, while the tamarind gravy is sharp, spicy, and full of character. That balance is what makes the dish interesting. The oyster mushroom should not fight the tamarind; it should soak it in and become juicy.',
          'We tear the mushrooms by hand because pink oyster mushrooms have beautiful thin layers. Those layers hold the gravy better than flat-cut pieces. When they go into the curry, they soften quickly and take in the flavour from the tamarind, garlic, chilli, and curry leaves.',
          'The tempering matters in this recipe. Mustard seeds give the first pop of flavour, fenugreek gives a slight bitter depth, and curry leaves bring that warm South Indian smell. Garlic is important here because it stands up well to tamarind. It gives the curry a savoury base so the sourness does not feel empty.',
          'The onion and tomato are cooked down before the mushroom goes in. Onion gives a little sweetness, tomato gives body, and the spices bring heat and warmth. Once the oyster mushrooms are added, they release moisture and soften. We let them settle into the masala before adding tamarind extract.',
          'Tamarind should simmer properly. If it is not cooked enough, the curry tastes raw and sharply sour. When it simmers for a few minutes, the sourness becomes deeper and more rounded. The mushroom then starts tasting juicy, tangy, and spicy instead of plain.',
          'The final curry should be medium-thin to medium-thick, depending on what it is served with. For rice, it can be slightly loose. For dosa or chapati, let it reduce a little more. The bite should feel soft, tangy, warm, and satisfying — the kind of curry that makes plain rice feel complete.',
        ],
      },
    ],
  },
  {
    id: 'shiitake-mushroom-soy-garlic-stir-curry',
    title: 'Shiitake Mushroom Soy-Garlic Stir Curry',
    bestWith: 'Fresh Shiitake Mushroom',
    categoryIds: ['mushroom-recipes'],
    primaryCategoryLabel: 'Mushroom Recipes',
    cookingTime: '25 minutes',
    serves: '2–3 people',
    thumbnailSrc: SHIITAKE_SOY_GARLIC_STIR_CURRY_IMAGES.thumbnail,
    nutritionProfiles: [NUTRITION_SHIITAKE_MUSHROOM],
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Shiitake Mushroom in this recipe',
        imageSrc: SHIITAKE_SOY_GARLIC_STIR_CURRY_IMAGES.goodness,
        imageAlt: 'Fresh Shiitake Mushroom',
        contentType: 'nutrition',
        items: [
          'Shiitake has a deeper, earthier flavour than mild mushrooms, so it works well with garlic, pepper, and soy-style seasoning.',
          'Its slightly chewy texture gives this stir curry a stronger bite without needing a heavy gravy.',
          'Raw shiitake mushroom is naturally low in fat and cholesterol-free before cooking.',
          'Shiitake provides dietary fibre, potassium, phosphorus, copper, zinc, B vitamins, and natural mushroom umami.',
          'Because shiitake already has a savoury depth, this recipe needs only a small amount of soy sauce to bring out the flavour.',
          'This dish is useful for people who want a mushroom recipe that feels bold, aromatic, and slightly different from regular onion-tomato masala.',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: SHIITAKE_SOY_GARLIC_STIR_CURRY_IMAGES.ingredients,
        imageAlt: 'Ingredients for Shiitake Mushroom Soy-Garlic Stir Curry',
        contentType: 'ingredients',
        items: [
          '200 g fresh shiitake mushrooms',
          '1 large onion, sliced',
          '8–10 garlic cloves, finely chopped',
          '1 green chilli, slit',
          '½ tsp black pepper powder',
          '1 tsp soy sauce',
          '½ tsp red chilli flakes or chilli powder',
          '½ tsp coriander powder',
          '¼ tsp turmeric powder, optional',
          'Curry leaves or spring onion greens',
          'Salt as needed',
          '2 tbsp oil',
          '2–3 tbsp water, only if needed',
          'Lemon juice, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: SHIITAKE_SOY_GARLIC_STIR_CURRY_IMAGES.process,
        imageAlt: 'Making Shiitake Mushroom Soy-Garlic Stir Curry',
        contentType: 'steps',
        items: [
          'Clean the shiitake mushrooms gently.',
          'Trim the tough stem ends if needed.',
          'Slice the mushroom caps into medium strips.',
          'Heat oil in a pan.',
          'Add chopped garlic and cook until aromatic, not dark brown.',
          'Add onion and green chilli.',
          'Fry until the onion turns soft.',
          'Add chilli flakes, pepper, coriander powder, turmeric if using, and a little salt.',
          'Add the shiitake mushrooms and toss well.',
          'Cook on medium flame until the mushrooms soften and release moisture.',
          'Add soy sauce and mix well.',
          'Cook until the mushrooms look glossy and lightly roasted.',
          'Add a splash of water only if the pan becomes too dry.',
          'Finish with curry leaves, spring onion greens, or lemon juice if preferred.',
          'Serve hot with rice, chapati, dosa, or simple steamed rice.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: SHIITAKE_SOY_GARLIC_STIR_CURRY_IMAGES.howWeMakeIt,
        imageAlt: 'Shiitake Mushroom Soy-Garlic Stir Curry served',
        contentType: 'narrative',
        narrative: [
          'Shiitake Mushroom Soy-Garlic Stir Curry is for people who like mushrooms with a little more character. Shiitake is not as mild as button mushroom and not as delicate as oyster mushroom. It has a deeper, earthy taste, so we don\'t need to cover it with too many spices. We build around it with garlic, pepper, and a small touch of soy sauce.',
          'We slice the shiitake caps into medium strips because the texture matters here. If the pieces are too thick, the seasoning stays outside. If they are too thin, they lose their chew. Medium strips give that nice balance — soft around the edges, slightly chewy in the centre, and glossy once cooked.',
          'Garlic goes first into the oil because this recipe depends on its aroma. But we don\'t let it turn too dark. Burnt garlic becomes bitter and can spoil the clean umami flavour of shiitake. Once the garlic smells warm, onion and green chilli go in to give the dish sweetness and fresh heat.',
          'The spice is kept controlled. Pepper gives warmth, chilli gives a little sharpness, and coriander powder gives the dish some body without pushing it into a full Indian gravy. Soy sauce is added carefully because shiitake already has its own savoury depth. Too much soy will make the dish salty and flat. A small amount is enough to wake up the mushroom\'s natural flavour.',
          'As the shiitake cooks, it softens and becomes glossy. We let the moisture reduce so the mushroom pieces are coated instead of watery. The final dish should feel bold but not heavy — garlicky, peppery, slightly savoury, and earthy, with the mushroom still clearly leading the plate.',
          'This works well with plain rice, chapati, dosa, or steamed rice. It is simple, but it has a deeper flavour than a regular mushroom fry.',
        ],
      },
    ],
  },
  {
    id: 'shiitake-mushroom-pepper-masala',
    title: 'Shiitake Mushroom Pepper Masala',
    bestWith: 'Fresh Shiitake Mushroom',
    categoryIds: ['mushroom-recipes'],
    primaryCategoryLabel: 'Mushroom Recipes',
    cookingTime: '30 minutes',
    serves: '2–3 people',
    thumbnailSrc: SHIITAKE_MUSHROOM_PEPPER_MASALA_IMAGES.thumbnail,
    nutritionProfiles: [NUTRITION_SHIITAKE_MUSHROOM],
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Shiitake Mushroom in this recipe',
        imageSrc: SHIITAKE_MUSHROOM_PEPPER_MASALA_IMAGES.goodness,
        imageAlt: 'Fresh Shiitake Mushroom',
        contentType: 'nutrition',
        items: [
          'Shiitake has a deeper, earthier taste than mild mushrooms, so it works well in a pepper-based masala',
          'Its slightly chewy texture gives this dish a stronger bite without needing a heavy gravy',
          'Raw shiitake mushroom is naturally low in fat and cholesterol-free before cooking',
          'Shiitake provides dietary fibre, potassium, phosphorus, zinc, copper, folate, and useful B vitamins',
          'Because shiitake already has a natural savoury depth, pepper and onion can build flavour without hiding the mushroom',
          'This recipe suits people who want a mushroom dish that feels bold, warm, and more mature than a regular mushroom curry',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: SHIITAKE_MUSHROOM_PEPPER_MASALA_IMAGES.ingredients,
        imageAlt: 'Ingredients for Shiitake Mushroom Pepper Masala',
        contentType: 'ingredients',
        items: [
          '200 g fresh shiitake mushrooms',
          '1 large onion, finely sliced',
          '1 small tomato, finely chopped',
          '1 green chilli, slit',
          '1 tsp ginger-garlic paste',
          '1½ tsp freshly crushed black pepper',
          '½ tsp turmeric powder',
          '1 tsp coriander powder',
          '½ tsp cumin powder',
          '½ tsp garam masala',
          'Curry leaves',
          'Salt as needed',
          '2 tbsp oil or ghee',
          '¼ cup water, only if needed',
          'Lemon juice, optional',
          'Fresh coriander leaves, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: SHIITAKE_MUSHROOM_PEPPER_MASALA_IMAGES.process,
        imageAlt: 'Making Shiitake Mushroom Pepper Masala',
        contentType: 'steps',
        items: [
          'Clean the shiitake mushrooms gently.',
          'Trim the tough stem ends if needed.',
          'Slice the mushroom caps into medium pieces.',
          'Heat oil or ghee in a pan.',
          'Add curry leaves, onion, and green chilli.',
          'Fry until the onion turns soft and lightly golden.',
          'Add ginger-garlic paste and cook until the raw smell reduces.',
          'Add tomato, turmeric, coriander powder, cumin powder, and salt.',
          'Cook until the tomato softens and the masala thickens.',
          'Add the shiitake mushrooms and mix well.',
          'Cook on medium flame until the mushrooms soften and release a little moisture.',
          'Add a small splash of water only if the masala feels too dry.',
          'Add freshly crushed black pepper and garam masala near the end.',
          'Toss until the mushrooms look glossy and well coated.',
          'Finish with lemon juice or coriander leaves if preferred.',
          'Serve hot with rice, chapati, dosa, parotta, or rasam rice.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: SHIITAKE_MUSHROOM_PEPPER_MASALA_IMAGES.howWeMakeIt,
        imageAlt: 'Shiitake Mushroom Pepper Masala served',
        contentType: 'narrative',
        narrative: [
          'Shiitake Mushroom Pepper Masala is not a soft, mild mushroom curry. It has more depth. Shiitake has an earthy, savoury taste, so we don\'t need to cover it with too many ingredients. We build around it with onion, curry leaves, ginger-garlic, and freshly crushed pepper.',
          'We slice the shiitake caps into medium pieces because the texture is part of the pleasure here. Shiitake should not melt into the masala. It should give a slight chew when you bite into it.',
          'The base starts with curry leaves, onion, and green chilli. Tomato is used lightly here. This is not a tomato gravy; it is a pepper masala. The tomato only gives enough softness to help the spices come together.',
          'Pepper comes near the end because that is where it tastes best. If pepper cooks for too long, it can turn dull and slightly bitter. Freshly crushed pepper added late gives heat, aroma, and a clean bite.',
          'The final dish should be dry to semi-dry, dark, glossy, and peppery. The mushroom should feel chewy, savoury, and coated in masala, with pepper staying sharp enough to make every bite feel alive.',
        ],
      },
    ],
  },
  {
    id: 'lions-mane-mushroom-roast',
    title: "Lion's Mane Mushroom Roast",
    bestWith: "Fresh Lion's Mane Mushroom",
    categoryIds: ['mushroom-recipes'],
    primaryCategoryLabel: 'Mushroom Recipes',
    cookingTime: '25–30 minutes',
    serves: '2 people',
    thumbnailSrc: LIONS_MANE_MUSHROOM_ROAST_IMAGES.thumbnail,
    nutritionProfiles: [NUTRITION_LIONS_MANE_MUSHROOM],
    cards: [
      {
        id: 'goodness',
        title: "Goodness of Lion's Mane Mushroom in this recipe",
        imageSrc: LIONS_MANE_MUSHROOM_ROAST_IMAGES.goodness,
        imageAlt: "Fresh Lion's Mane Mushroom",
        contentType: 'nutrition',
        items: [
          "Lion's mane has a soft, fibrous texture, so it works beautifully in a roast where the edges can brown while the inside stays tender",
          'Its mild, slightly savoury flavour does not need heavy masala; simple garlic, pepper, curry leaves, and ghee or oil are enough',
          "Raw lion's mane mushroom is naturally low in fat, so the richness in this roast mainly comes from the oil or ghee used during cooking",
          "USDA-sourced reference data lists lion's mane with protein, carbohydrate, potassium, phosphorus, iron, zinc, copper, manganese, selenium, thiamin, niacin, vitamin B6, folate, and biotin",
          'Because the mushroom has a naturally shreddable body, it gives a satisfying bite without needing deep frying or thick batter',
          "This recipe is best for people who want to understand lion's mane as a fresh culinary mushroom, not as a supplement or powder",
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: LIONS_MANE_MUSHROOM_ROAST_IMAGES.ingredients,
        imageAlt: "Ingredients for Lion's Mane Mushroom Roast",
        contentType: 'ingredients',
        items: [
          "200 g fresh lion's mane mushroom",
          '1 medium onion, thinly sliced',
          '6–8 garlic cloves, finely chopped',
          '1 green chilli, slit',
          '½ tsp turmeric powder',
          '1 tsp freshly crushed black pepper',
          '½ tsp coriander powder',
          '½ tsp cumin powder',
          '½ tsp garam masala',
          'Curry leaves',
          'Salt as needed',
          '1½ tbsp oil or ghee',
          '1 tsp lemon juice, optional',
          'Fresh coriander leaves, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: LIONS_MANE_MUSHROOM_ROAST_IMAGES.process,
        imageAlt: "Making Lion's Mane Mushroom Roast",
        contentType: 'steps',
        items: [
          "Clean the lion's mane mushroom gently.",
          'Tear it into thick natural pieces by hand.',
          'Do not chop it too small.',
          'Heat oil or ghee in a pan.',
          'Add curry leaves, garlic, onion, and green chilli.',
          'Fry until the onion softens and the garlic turns aromatic.',
          'Add turmeric, coriander powder, cumin powder, and salt.',
          "Add the lion's mane mushroom pieces.",
          'Cook on medium flame until the mushroom releases moisture.',
          'Press the pieces lightly against the pan so the edges roast.',
          'Add crushed black pepper near the end.',
          'Add garam masala and toss gently.',
          'Roast until the outside looks lightly browned and the inside stays tender.',
          'Finish with lemon juice or coriander leaves if preferred.',
          'Serve hot with rice, chapati, dosa, or as a mushroom side dish.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: LIONS_MANE_MUSHROOM_ROAST_IMAGES.howWeMakeIt,
        imageAlt: "Lion's Mane Mushroom Roast served",
        contentType: 'narrative',
        narrative: [
          "Lion's Mane Mushroom Roast needs a gentler hand than regular mushroom fry. This mushroom has a soft, fibrous body, almost like it naturally wants to tear into tender chunks. So we don't chop it into small pieces. We pull it apart by hand into thick, uneven pieces.",
          "We start with oil or ghee, curry leaves, garlic, onion, and green chilli. Garlic is important here, but it should not burn. Lion's mane has a mild flavour and burnt garlic can easily take over the whole dish.",
          'The spices are kept simple. Turmeric gives colour, coriander gives body, cumin gives earthiness, and pepper gives warmth. If we overload it with spices, the mushroom\'s own texture gets lost.',
          'Once the mushroom goes into the pan, it first releases moisture. We let that happen. Then, as the water reduces, we press the pieces lightly against the pan so the surface gets a little browning. That is where the flavour changes.',
          'The final dish should have lightly browned edges, a tender centre, and a warm garlic-pepper smell. The bite should feel soft, fibrous, and satisfying.',
        ],
      },
    ],
  },
  {
    id: 'cordyceps-mushroom-mild-masala',
    title: 'Cordyceps Mushroom Mild Masala',
    bestWith: 'Fresh Cordyceps Mushroom',
    categoryIds: ['mushroom-recipes'],
    primaryCategoryLabel: 'Mushroom Recipes',
    cookingTime: '20–25 minutes',
    serves: '2 people',
    thumbnailSrc: CORDYCEPS_MUSHROOM_MILD_MASALA_IMAGES.thumbnail,
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Cordyceps Mushroom in this recipe',
        imageSrc: CORDYCEPS_MUSHROOM_MILD_MASALA_IMAGES.goodness,
        imageAlt: 'Fresh Cordyceps Mushroom',
        contentType: 'nutrition',
        items: [
          'Cordyceps is a specialty mushroom, so this recipe keeps the masala mild instead of hiding its natural character',
          'Its thin, delicate shape works better with gentle cooking than heavy frying or thick gravy',
          'The mild onion-garlic base helps people taste the mushroom clearly without making the dish confusing',
          'A small amount of pepper and garam masala gives warmth while still keeping the cordyceps as the main ingredient',
          'This recipe is useful for introducing cordyceps as a fresh culinary mushroom, not only as a powder, capsule, or supplement',
          'Since cordyceps can feel unfamiliar to many customers, a simple masala makes it easier to understand on a normal Indian plate',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: CORDYCEPS_MUSHROOM_MILD_MASALA_IMAGES.ingredients,
        imageAlt: 'Ingredients for Cordyceps Mushroom Mild Masala',
        contentType: 'ingredients',
        items: [
          '100–150 g fresh cordyceps mushrooms',
          '1 medium onion, finely sliced',
          '4–5 garlic cloves, finely chopped',
          '1 green chilli, slit',
          '½ tsp ginger, finely grated',
          '¼ tsp turmeric powder',
          '½ tsp coriander powder',
          '¼ tsp cumin powder',
          '½ tsp freshly crushed black pepper',
          '¼ tsp garam masala',
          'Curry leaves',
          'Salt as needed',
          '1½ tbsp oil or ghee',
          '2–3 tbsp water, only if needed',
          'Lemon juice, optional',
          'Fresh coriander leaves, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: CORDYCEPS_MUSHROOM_MILD_MASALA_IMAGES.process,
        imageAlt: 'Making Cordyceps Mushroom Mild Masala',
        contentType: 'steps',
        items: [
          'Clean the cordyceps mushrooms gently.',
          'Keep them mostly whole or cut only the longer pieces.',
          'Heat oil or ghee in a pan.',
          'Add curry leaves, garlic, onion, and green chilli.',
          'Fry until the onion turns soft, not too dark.',
          'Add grated ginger and cook briefly.',
          'Add turmeric, coriander powder, cumin powder, and salt.',
          'Add the cordyceps mushrooms and toss gently.',
          'Cook on medium-low flame until they soften slightly.',
          'Add a splash of water only if the pan becomes too dry.',
          'Add crushed black pepper and garam masala near the end.',
          'Toss gently until the mushrooms are coated and glossy.',
          'Finish with lemon juice or coriander leaves if preferred.',
          'Serve warm with rice, chapati, dosa, or as a small mushroom side dish.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: CORDYCEPS_MUSHROOM_MILD_MASALA_IMAGES.howWeMakeIt,
        imageAlt: 'Cordyceps Mushroom Mild Masala served',
        contentType: 'narrative',
        narrative: [
          "Cordyceps Mushroom Mild Masala needs a different approach from the usual mushroom curry. Cordyceps is thin, delicate, and visually very different, so we don't treat it like button mushroom or milky mushroom. We keep the pieces mostly whole because the shape itself is part of the experience.",
          'The base is intentionally simple. Onion, garlic, curry leaves, and a little green chilli give the dish a familiar Indian flavour, but they don\'t overpower the mushroom. Garlic is cooked gently until aromatic, not browned too much.',
          'We use ginger lightly because it gives warmth without making the dish sharp. The dry spices are also controlled: turmeric for colour, coriander for body, cumin for earthiness, and pepper for a clean finish.',
          'Cordyceps goes into the pan after the base is ready. We cook it on medium-low flame because delicate mushrooms do not need rough handling. The final dish should stay glossy, light, and gently coated.',
          'The final dish should feel mild, warm, and slightly elegant. It should not shout with spice. It should make someone curious, take a second bite, and understand cordyceps as a fresh mushroom that can belong on a normal meal plate.',
        ],
      },
    ],
  },
]
