import {
  PINK_OYSTER_MUSHROOM_65_IMAGES,
  MILKY_MUSHROOM_PAKODI_IMAGES,
  OYSTER_MUSHROOM_CUTLET_IMAGES,
  MUSHROOM_CHEESE_TOAST_BITES_IMAGES,
  MILKY_MUSHROOM_PEPPER_POPCORN_IMAGES,
  BUTTON_MUSHROOM_TAWA_TIKKA_IMAGES,
  BUTTON_MUSHROOM_STUFFED_CAPS_IMAGES,
  SUNFLOWER_MICROGREEN_PANEER_ROLL_BITES_IMAGES,
  OYSTER_MUSHROOM_SPRING_ONION_PAN_BITES_IMAGES,
  MICROGREEN_CHILLI_CHEESE_SANDWICH_TRIANGLES_IMAGES,
} from '@/assets/Recipe Book'
import type { RecipeData } from '@/types'
import {
  NUTRITION_PINK_OYSTER_MUSHROOM,
  NUTRITION_BUTTON_MUSHROOM_USDA,
  NUTRITION_OYSTER_MUSHROOM_USDA,
} from '@/constants/NUTRITION_PROFILES'

export const QUICK_SNACK_RECIPES: RecipeData[] = [
  {
    id: 'pink-oyster-mushroom-65',
    title: 'Pink Oyster Mushroom 65',
    categoryIds: ['quick-snacks', 'mushroom-recipes'],
    primaryCategoryLabel: 'Quick Snacks',
    cookingTime: '25 minutes',
    serves: '3–4 people',
    thumbnailSrc: PINK_OYSTER_MUSHROOM_65_IMAGES.thumbnail,
    nutritionProfiles: [NUTRITION_PINK_OYSTER_MUSHROOM],
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Pink Oyster Mushroom in this recipe',
        imageSrc: PINK_OYSTER_MUSHROOM_65_IMAGES.goodness,
        imageAlt: 'Pink Oyster Mushroom sketch',
        contentType: 'nutrition',
        items: [
          'Pink Oyster Mushrooms are naturally low in fat and high in plant-based protein, making them suitable for this deep-fried style recipe without feeling heavy',
          'Their fan-like texture holds the batter well, creating a crispy coating that stays on during frying',
          'They absorb spice flavours deeply, so each bite carries the full flavour of the 65-style marinade',
          'The mushroom\'s natural umami taste works well with the tangy curd, red chilli, and pepper marinade',
          'Even after frying, the mushroom inside stays moist and tender, giving a satisfying texture contrast',
          'Using mushroom as the base instead of chicken keeps this recipe lighter while maintaining the full flavour of a 65-style dish',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: PINK_OYSTER_MUSHROOM_65_IMAGES.ingredients,
        imageAlt: 'Ingredients for Pink Oyster Mushroom 65',
        contentType: 'ingredients',
        items: [
          '200g Pink Oyster Mushrooms, torn into large pieces',
          '3 tbsp curd (yogurt)',
          '1 tbsp cornflour',
          '1 tbsp rice flour',
          '1 tsp red chilli powder',
          '½ tsp garam masala',
          '½ tsp cumin powder',
          '½ tsp black pepper powder',
          '1 tsp ginger-garlic paste',
          '1 tsp lemon juice',
          'Salt as needed',
          'Oil for frying',
          'Curry leaves for frying',
          'Slit green chillies for frying',
          '1 tsp lemon juice to finish',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: PINK_OYSTER_MUSHROOM_65_IMAGES.process,
        imageAlt: 'Making Pink Oyster Mushroom 65',
        contentType: 'steps',
        items: [
          'Clean the mushrooms gently and tear into large pieces.',
          'Mix curd, cornflour, rice flour, red chilli powder, garam masala, cumin, pepper, ginger-garlic paste, lemon juice, and salt.',
          'Coat the mushroom pieces well and marinate for 15 minutes.',
          'Heat oil for deep or shallow frying.',
          'Fry the mushroom pieces in batches until golden and crispy.',
          'In the last minute, add curry leaves and slit green chillies to the oil and fry briefly.',
          'Drain on paper and finish with a squeeze of lemon juice.',
          'Serve hot immediately.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: PINK_OYSTER_MUSHROOM_65_IMAGES.howWeMakeIt,
        imageAlt: 'Pink Oyster Mushroom 65 served',
        contentType: 'narrative',
        narrative: [
          'Pink Oyster Mushroom 65 is one of our most requested snack dishes. The mushroom\'s fan-like structure holds the spiced curd batter beautifully, and when it fries, it becomes golden outside with a soft, moist centre.',
          'We use curd in the marinade because it tenderises the mushroom and gives the coating a slightly tangy taste that matches the spice mix. Cornflour and rice flour together give the coating crispness without making it too thick or bready.',
          'The 65-style flavour comes from the red chilli, pepper, cumin, and garam masala combination. Ginger-garlic paste brings depth.',
          'The curry leaves and green chillies are added to the hot oil in the last minute of frying. This is the step that makes the dish smell and taste like a proper 65 preparation.',
        ],
      },
    ],
  },
  {
    id: 'milky-mushroom-pakoda',
    title: 'Milky Mushroom Pakoda',
    categoryIds: ['quick-snacks', 'mushroom-recipes'],
    primaryCategoryLabel: 'Quick Snacks',
    cookingTime: '25 minutes',
    serves: '3–4 people',
    thumbnailSrc: MILKY_MUSHROOM_PAKODI_IMAGES.thumbnail,
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Milky Mushroom in this recipe',
        imageSrc: MILKY_MUSHROOM_PAKODI_IMAGES.goodness,
        imageAlt: 'Milky Mushroom sketch',
        contentType: 'nutrition',
        items: [
          'Milky mushrooms have a firm, meaty texture that holds its shape during frying, so the pakoda stays chunky and satisfying',
          'Their mild flavour absorbs the spiced besan batter well, giving each bite a good balance of mushroom and masala taste',
          'They release very little moisture compared to softer mushrooms, which means the batter stays crispy instead of going soggy',
          'The natural umami of milky mushroom adds depth to the pakoda without needing strong masala',
          'Using mushroom as the base makes this a plant-based pakoda option that still feels hearty and filling',
          'Even after frying, the mushroom inside stays moist, creating a good contrast between the crispy outer coating and the soft centre',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: MILKY_MUSHROOM_PAKODI_IMAGES.ingredients,
        imageAlt: 'Ingredients for Milky Mushroom Pakoda',
        contentType: 'ingredients',
        items: [
          '200g Milky Mushrooms, sliced or torn into large pieces',
          '1 cup besan (gram flour)',
          '2 tbsp rice flour',
          '1 tsp red chilli powder',
          '½ tsp turmeric powder',
          '½ tsp cumin seeds',
          '½ tsp black pepper powder',
          '½ tsp garam masala, optional',
          '1 tbsp hot oil (for batter)',
          'Salt as needed',
          'Water as needed to make a thick batter',
          'Oil for deep frying',
          'Curry leaves',
          'Slit green chillies',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: MILKY_MUSHROOM_PAKODI_IMAGES.process,
        imageAlt: 'Making Milky Mushroom Pakoda',
        contentType: 'steps',
        items: [
          'Clean the milky mushrooms and slice or tear into large pieces.',
          'Pat dry the mushroom pieces thoroughly.',
          'Mix besan, rice flour, red chilli, turmeric, cumin seeds, pepper, garam masala, and salt.',
          'Add 1 tbsp hot oil to the batter — this helps crisp the coating.',
          'Add water gradually to make a thick batter that coats the mushroom.',
          'Heat oil for deep frying.',
          'Dip mushroom pieces in the batter and fry in batches until golden and crispy.',
          'Add curry leaves and green chillies to the oil in the last minute.',
          'Drain on paper and serve hot with chutney.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: MILKY_MUSHROOM_PAKODI_IMAGES.howWeMakeIt,
        imageAlt: 'Milky Mushroom Pakoda served',
        contentType: 'narrative',
        narrative: [
          'Milky Mushroom Pakoda is one of the most natural recipes for this mushroom. Milky mushrooms are firm and thick, so they don\'t collapse or turn mushy when they go into hot oil. This gives the pakoda a satisfying chunky texture.',
          'The batter uses besan and rice flour together. Besan gives flavour and body, while rice flour brings the crispness. A spoon of hot oil added to the batter before dipping is a small but important trick — it makes the coating crispier and prevents it from absorbing too much oil during frying.',
          'Patting the mushroom dry before battering matters here. If water is left on the mushroom surface, the batter may not stick well and the frying oil can splatter.',
          'Curry leaves and green chillies are fried separately in the oil at the end and mixed in. They add aroma and that familiar pakoda-stall fragrance.',
        ],
      },
    ],
  },
  {
    id: 'button-mushroom-stuffed-caps',
    title: 'Button Mushroom Stuffed Caps',
    categoryIds: ['quick-snacks', 'mushroom-recipes'],
    primaryCategoryLabel: 'Quick Snacks',
    cookingTime: '30 minutes',
    serves: '2–3 people',
    thumbnailSrc: BUTTON_MUSHROOM_STUFFED_CAPS_IMAGES.thumbnail,
    nutritionProfiles: [NUTRITION_BUTTON_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Button Mushroom in this recipe',
        imageSrc: BUTTON_MUSHROOM_STUFFED_CAPS_IMAGES.goodness,
        imageAlt: 'Button Mushroom Stuffed Caps goodness',
        contentType: 'nutrition',
        items: [
          'Button mushroom caps are naturally cup-shaped, making them ideal for holding stuffing without extra preparation',
          'The stems removed during preparation are reused in the filling, so there is no waste',
          'Button mushrooms have a mild flavour that works as a neutral base, so the stuffing seasoning comes through clearly',
          'Their firm texture holds shape during baking or pan-grilling without becoming too soft',
          'The stuffed cap format makes portion control simple and the presentation naturally impressive',
          'This recipe uses simple stuffing like paneer, onion, capsicum, and spices — keeping it accessible for everyday cooking',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: BUTTON_MUSHROOM_STUFFED_CAPS_IMAGES.ingredients,
        imageAlt: 'Ingredients for Button Mushroom Stuffed Caps',
        contentType: 'ingredients',
        items: [
          '15–18 medium Button Mushrooms',
          '80g paneer, crumbled',
          '1 small onion, finely chopped',
          '1 small green capsicum, finely chopped',
          '1 green chilli, finely chopped',
          '½ tsp cumin powder',
          '½ tsp red chilli powder',
          '¼ tsp garam masala',
          'Salt as needed',
          '1 tbsp oil or butter',
          '1 tbsp grated cheese, optional',
          'Fresh coriander leaves',
          'Chaat masala for finishing, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: BUTTON_MUSHROOM_STUFFED_CAPS_IMAGES.process,
        imageAlt: 'Making Button Mushroom Stuffed Caps',
        contentType: 'steps',
        items: [
          'Wipe the button mushrooms clean with a damp cloth.',
          'Gently remove the stems.',
          'Finely chop the removed stems.',
          'Heat oil or butter in a pan.',
          'Add onion and cook until soft.',
          'Add capsicum, green chilli, and chopped mushroom stems.',
          'Cook for 2–3 minutes.',
          'Add paneer, cumin powder, chilli powder, garam masala, and salt.',
          'Mix well and cook for 1–2 minutes. Let the filling cool slightly.',
          'Fill each mushroom cap generously with the prepared filling.',
          'Place on a greased baking tray or pan.',
          'Bake at 200°C for 12–15 minutes, or pan-grill covered for 8–10 minutes.',
          'Top with grated cheese in the last few minutes if using.',
          'Finish with fresh coriander and chaat masala.',
          'Serve warm immediately.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: BUTTON_MUSHROOM_STUFFED_CAPS_IMAGES.howWeMakeIt,
        imageAlt: 'Button Mushroom Stuffed Caps served',
        contentType: 'narrative',
        narrative: [
          'Button Mushroom Stuffed Caps are elegant, practical, and well-suited to parties, starter plates, or a snack that looks impressive without being complicated.',
          'The mushroom cap does all the structural work. We remove the stems carefully without breaking the cap, then chop those stems and cook them directly into the filling. Using the stems this way is practical and ensures nothing is wasted.',
          'The filling is simple but effective. Onion and capsicum are cooked first to soften. Paneer brings body and a mild creaminess. Spices are kept moderate so the mushroom flavour still comes through.',
          'Whether baked or pan-grilled, the mushroom becomes slightly golden on the outside while staying moist inside. Cheese on top is optional but adds a richness that makes these caps feel indulgent.',
        ],
      },
    ],
  },
  {
    id: 'oyster-mushroom-cutlets',
    title: 'Oyster Mushroom Cutlets',
    categoryIds: ['quick-snacks', 'mushroom-recipes'],
    primaryCategoryLabel: 'Quick Snacks',
    cookingTime: '35 minutes',
    serves: '3–4 people',
    thumbnailSrc: OYSTER_MUSHROOM_CUTLET_IMAGES.thumbnail,
    nutritionProfiles: [NUTRITION_OYSTER_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Oyster Mushroom in this recipe',
        imageSrc: OYSTER_MUSHROOM_CUTLET_IMAGES.goodness,
        imageAlt: 'Fresh Oyster Mushroom',
        contentType: 'nutrition',
        items: [
          'Oyster mushrooms have a natural meaty texture when shredded, so they create a satisfying base for cutlets without needing meat',
          'They blend well with cooked potato and spices, holding together when shaped and shallow-fried',
          'Their mild umami flavour absorbs the masala seasoning fully, giving each cutlet a well-balanced taste',
          'Oyster mushrooms are naturally low in fat and protein-rich, making this a lighter cutlet option',
          'They are quick to cook, so the preparation time for the filling is shorter than traditional vegetable cutlets',
          'This recipe uses a combination of mushroom and potato, which gives the right texture for shaping without falling apart',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: OYSTER_MUSHROOM_CUTLET_IMAGES.ingredients,
        imageAlt: 'Ingredients for Oyster Mushroom Cutlets',
        contentType: 'ingredients',
        items: [
          '200g Oyster Mushrooms, finely chopped or shredded',
          '2 medium potatoes, boiled and mashed',
          '1 small onion, finely chopped',
          '1 green chilli, finely chopped',
          '1 tsp ginger-garlic paste',
          '1 tsp red chilli powder',
          '½ tsp cumin powder',
          '½ tsp garam masala',
          '½ tsp coriander powder',
          'Salt as needed',
          '2 tbsp cornflour or breadcrumbs, for binding',
          'Breadcrumbs or semolina for coating',
          'Oil for shallow frying',
          'Fresh coriander leaves',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: OYSTER_MUSHROOM_CUTLET_IMAGES.process,
        imageAlt: 'Making Oyster Mushroom Cutlets',
        contentType: 'steps',
        items: [
          'Finely chop or shred the oyster mushrooms.',
          'Cook the mushrooms in a pan without oil until their moisture evaporates.',
          'Add a little oil, onion, green chilli, and ginger-garlic paste.',
          'Cook until onion is soft.',
          'Add red chilli, cumin, garam masala, coriander powder, and salt.',
          'Mix well and cook until dry. Let it cool.',
          'Combine the mushroom mixture with mashed potato, cornflour, and fresh coriander.',
          'Mix well and shape into round or oval cutlets.',
          'Coat each cutlet lightly in breadcrumbs or semolina.',
          'Shallow fry on medium heat until golden and crisp on both sides.',
          'Serve hot with chutney or ketchup.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: OYSTER_MUSHROOM_CUTLET_IMAGES.howWeMakeIt,
        imageAlt: 'Oyster Mushroom Cutlets served',
        contentType: 'narrative',
        narrative: [
          'Oyster Mushroom Cutlets are a great plant-based snack that tastes substantial without relying on any meat. The key to a good mushroom cutlet is making sure the filling is completely dry before mixing with potato.',
          'Oyster mushrooms release water when they cook. We cook them in a dry pan first to drive out that moisture before adding oil and other ingredients. If this step is skipped, the cutlet mixture becomes wet and the cutlets won\'t hold shape or crisp up properly.',
          'The mashed potato gives structure. It binds everything together and gives the cutlet a smooth texture inside. Cornflour adds extra binding strength.',
          'The spice mix is straightforward — red chilli, cumin, garam masala, and coriander — but the filling should be fully dry and well-cooked before shaping. A wet or undercooked filling makes the cutlets heavy and difficult to fry.',
          'Coated in breadcrumbs or fine semolina and shallow-fried on medium heat, the cutlets come out golden, crispy, and satisfying.',
        ],
      },
    ],
  },
  {
    id: 'mushroom-cheese-toast-bites',
    title: 'Mushroom Cheese Toast Bites',
    categoryIds: ['quick-snacks', 'mushroom-recipes'],
    primaryCategoryLabel: 'Quick Snacks',
    cookingTime: '20 minutes',
    serves: '2–3 people',
    thumbnailSrc: MUSHROOM_CHEESE_TOAST_BITES_IMAGES.thumbnail,
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Mushroom in this recipe',
        imageSrc: MUSHROOM_CHEESE_TOAST_BITES_IMAGES.goodness,
        imageAlt: 'Mushroom Cheese Toast Bites goodness',
        contentType: 'nutrition',
        items: [
          'Any firm mushroom works here, but button or milky mushroom are ideal because they cook quickly and stay dry enough for a toast topping',
          'Finely chopped mushrooms blend into the toast filling without making the bread soggy',
          'Their natural umami taste pairs naturally with melted cheese, giving depth without needing strong spices',
          'Mushroom brings flavour and body to a simple toast snack that would otherwise taste flat',
          'This recipe is simple, quick, and suitable for breakfast, after-school snacks, or a light starter',
          'Using mushroom in a cheese toast is an easy way to introduce it to people who are new to eating mushroom regularly',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: MUSHROOM_CHEESE_TOAST_BITES_IMAGES.ingredients,
        imageAlt: 'Ingredients for Mushroom Cheese Toast Bites',
        contentType: 'ingredients',
        items: [
          '150g Button or Milky Mushrooms, finely chopped',
          '4–6 bread slices, cut into rectangles or triangles',
          '1 small onion, finely chopped',
          '1 small green capsicum, finely chopped, optional',
          '1 green chilli, finely chopped',
          '½ tsp black pepper powder',
          '¼ tsp mixed herbs or oregano',
          'Salt as needed',
          '1 tbsp butter or oil',
          '½ cup grated cheese (processed or cheddar)',
          'Chilli flakes for topping, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: MUSHROOM_CHEESE_TOAST_BITES_IMAGES.process,
        imageAlt: 'Making Mushroom Cheese Toast Bites',
        contentType: 'steps',
        items: [
          'Finely chop the mushrooms.',
          'Heat butter or oil in a pan.',
          'Add onion and cook until soft.',
          'Add mushrooms and cook until the moisture evaporates and the mixture is dry.',
          'Add capsicum, green chilli, pepper, herbs, and salt.',
          'Mix well and cook for 1–2 more minutes.',
          'Let the mixture cool slightly.',
          'Butter the bread slices lightly.',
          'Spread the mushroom filling on each slice.',
          'Top with grated cheese.',
          'Bake or toast in an oven at 200°C for 8–10 minutes, or use a grill pan with a lid for 5–7 minutes.',
          'Finish with chilli flakes if preferred.',
          'Cut into bite-sized pieces and serve hot.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: MUSHROOM_CHEESE_TOAST_BITES_IMAGES.howWeMakeIt,
        imageAlt: 'Mushroom Cheese Toast Bites served',
        contentType: 'narrative',
        narrative: [
          'Mushroom Cheese Toast Bites are designed to be quick, simple, and reliably enjoyable. The mushroom filling does all the flavour work. Cheese holds it on the bread and brings melty richness.',
          'The most important step is cooking the mushroom mixture until it is completely dry. Wet mushroom filling makes the bread soft and difficult to eat as a bite-sized piece. We cook out all the moisture before the filling goes onto the bread.',
          'Mixed herbs or oregano give the toast a slightly café-style aroma. Black pepper brings gentle heat without needing chilli.',
          'These can be prepared in a standard oven, a countertop toaster oven, or even in a closed grill pan. All methods work.',
          'Cutting into small rectangles or triangles makes them easy to serve as a starter, a snack box item, or a party bite.',
        ],
      },
    ],
  },
  {
    id: 'milky-mushroom-pepper-popcorn',
    title: 'Milky Mushroom Pepper Popcorn',
    categoryIds: ['quick-snacks', 'mushroom-recipes'],
    primaryCategoryLabel: 'Quick Snacks',
    cookingTime: '20 minutes',
    serves: '2–3 people',
    thumbnailSrc: MILKY_MUSHROOM_PEPPER_POPCORN_IMAGES.thumbnail,
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Milky Mushroom in this recipe',
        imageSrc: MILKY_MUSHROOM_PEPPER_POPCORN_IMAGES.goodness,
        imageAlt: 'Milky Mushroom Pepper Popcorn goodness',
        contentType: 'nutrition',
        items: [
          'Milky mushrooms cut into small bite-sized cubes hold their shape during frying, giving this recipe its satisfying popcorn-like texture',
          'Their mild flavour absorbs the pepper-spice coating cleanly, giving each piece a bold taste',
          'The firm texture of milky mushroom means the coating stays crispy on the outside without the mushroom becoming mushy inside',
          'Their natural moisture content is lower than oyster mushroom, so the coating fries dry instead of steaming',
          'Small-cut milky mushroom pieces are easy to eat as a finger food snack, making them practical for serving at home or in an event setting',
          'This recipe uses minimal ingredients but delivers a crunchy, spicy result that works as a teatime snack or party starter',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: MILKY_MUSHROOM_PEPPER_POPCORN_IMAGES.ingredients,
        imageAlt: 'Ingredients for Milky Mushroom Pepper Popcorn',
        contentType: 'ingredients',
        items: [
          '200g Milky Mushrooms, cut into small bite-sized cubes',
          '2 tbsp cornflour',
          '1 tbsp rice flour',
          '1 tsp black pepper powder',
          '½ tsp red chilli powder',
          '¼ tsp garlic powder or ½ tsp ginger-garlic paste',
          '¼ tsp turmeric powder',
          'Salt as needed',
          'Oil for deep frying',
          '½ tsp extra black pepper for finishing',
          'Chaat masala for finishing, optional',
          'Lemon wedge for serving',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: MILKY_MUSHROOM_PEPPER_POPCORN_IMAGES.process,
        imageAlt: 'Making Milky Mushroom Pepper Popcorn',
        contentType: 'steps',
        items: [
          'Cut milky mushrooms into small bite-sized cubes.',
          'Pat them dry thoroughly.',
          'Mix cornflour, rice flour, black pepper, red chilli, garlic powder, turmeric, and salt.',
          'Toss the mushroom cubes in the dry flour mixture until evenly coated.',
          'Heat oil for deep frying.',
          'Fry the mushroom pieces in small batches until golden and crispy.',
          'Drain on paper.',
          'Toss immediately with extra black pepper and chaat masala if using.',
          'Serve hot with a lemon wedge.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: MILKY_MUSHROOM_PEPPER_POPCORN_IMAGES.howWeMakeIt,
        imageAlt: 'Milky Mushroom Pepper Popcorn served',
        contentType: 'narrative',
        narrative: [
          'Milky Mushroom Pepper Popcorn is named for the way it looks and eats. Small crispy cubes of mushroom tossed in black pepper and spice, eaten with your fingers while still warm.',
          'The dry flour coating is the key. We use cornflour and rice flour together. No egg, no batter, no liquid. Just a dry coat that sticks naturally to the mushroom surface.',
          'Patting the mushroom cubes dry before coating matters. Even a little surface moisture can make the flour coating uneven and cause it to fall off in the oil.',
          'Black pepper is the main flavour. It should be noticeable in every bite. We use it in the coating and again as a finishing toss right after frying, while the mushrooms are still hot.',
          'These are best eaten immediately while the coating is still crunchy.',
        ],
      },
    ],
  },
  {
    id: 'button-mushroom-tawa-tikka',
    title: 'Button Mushroom Tawa Tikka',
    categoryIds: ['quick-snacks', 'mushroom-recipes'],
    primaryCategoryLabel: 'Quick Snacks',
    cookingTime: '25 minutes',
    serves: '2–3 people',
    thumbnailSrc: BUTTON_MUSHROOM_TAWA_TIKKA_IMAGES.thumbnail,
    nutritionProfiles: [NUTRITION_BUTTON_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Button Mushroom in this recipe',
        imageSrc: BUTTON_MUSHROOM_TAWA_TIKKA_IMAGES.goodness,
        imageAlt: 'Button Mushroom Tawa Tikka goodness',
        contentType: 'nutrition',
        items: [
          'Button mushrooms are compact and uniform in size, so they cook evenly on a tawa without needing to be cut',
          'They have a neutral, mild taste that absorbs the tikka-style spiced curd marinade fully',
          'Their surface becomes slightly charred on a hot tawa, giving the tikka smokiness and colour without needing a tandoor',
          'Button mushrooms stay firm during pan-cooking and don\'t collapse or become watery like some softer varieties',
          'This recipe uses a curd-based marinade that tenderises the mushroom and gives the coating a slightly tangy finish',
          'Cooking on a tawa instead of deep-frying makes this a lighter tikka preparation without sacrificing taste',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: BUTTON_MUSHROOM_TAWA_TIKKA_IMAGES.ingredients,
        imageAlt: 'Ingredients for Button Mushroom Tawa Tikka',
        contentType: 'ingredients',
        items: [
          '250g Button Mushrooms, wiped clean, stems trimmed',
          '4 tbsp thick curd',
          '1 tsp red chilli powder',
          '½ tsp kashmiri chilli powder, for colour',
          '½ tsp cumin powder',
          '½ tsp coriander powder',
          '½ tsp garam masala',
          '1 tsp ginger-garlic paste',
          '1 tsp lemon juice',
          '1 tbsp oil (in marinade)',
          'Salt as needed',
          '1 tbsp oil for tawa cooking',
          'Chaat masala for finishing',
          'Onion rings and lemon wedge for serving',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: BUTTON_MUSHROOM_TAWA_TIKKA_IMAGES.process,
        imageAlt: 'Making Button Mushroom Tawa Tikka',
        contentType: 'steps',
        items: [
          'Wipe the button mushrooms clean.',
          'Mix curd, red chilli powder, kashmiri chilli, cumin, coriander, garam masala, ginger-garlic paste, lemon juice, oil, and salt.',
          'Coat the mushrooms in the marinade and rest for 20 minutes.',
          'Heat a tawa or cast iron pan on high flame.',
          'Add oil and arrange the mushrooms in a single layer.',
          'Do not move them for 2 minutes to let a char develop.',
          'Flip and cook the other side similarly.',
          'Cook until the marinade is dry and slightly charred.',
          'Sprinkle chaat masala immediately after removing from the pan.',
          'Serve with onion rings, lemon, and green chutney.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: BUTTON_MUSHROOM_TAWA_TIKKA_IMAGES.howWeMakeIt,
        imageAlt: 'Button Mushroom Tawa Tikka served',
        contentType: 'narrative',
        narrative: [
          'Button Mushroom Tawa Tikka is a no-oven tikka that still has the smoky, charred character of a restaurant-style preparation.',
          'The marinade uses thick curd, which holds the spices on the mushroom and creates a slightly sticky coating when it hits the hot tawa. Kashmiri chilli gives colour without making it too spicy.',
          'The tawa must be hot before the mushrooms go in. If the pan is not hot enough, the mushrooms will release water and simmer instead of char. High heat creates the char that gives this recipe its character.',
          'We let the mushrooms sit undisturbed on one side before flipping. Moving them too early prevents the crust from forming.',
          'Chaat masala is added only after cooking because heat can change its taste. The finishing masala gives each tikka a bright, tangy finish.',
        ],
      },
    ],
  },
  {
    id: 'sunflower-microgreen-paneer-roll-bites',
    title: 'Sunflower Microgreen Paneer Roll Bites',
    categoryIds: ['quick-snacks', 'microgreen-recipes'],
    primaryCategoryLabel: 'Quick Snacks',
    cookingTime: '20 minutes',
    serves: '2–3 people',
    thumbnailSrc: SUNFLOWER_MICROGREEN_PANEER_ROLL_BITES_IMAGES.thumbnail,
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Sunflower Microgreens in this recipe',
        imageSrc: SUNFLOWER_MICROGREEN_PANEER_ROLL_BITES_IMAGES.goodness,
        imageAlt: 'Sunflower Microgreen Paneer Roll Bites goodness',
        contentType: 'nutrition',
        items: [
          'Sunflower microgreens bring a natural nutty crunch that pairs well with soft paneer and fresh chutney in a roll',
          'They are used raw inside the roll, which preserves their fresh taste and visible texture',
          'Their juicy stems give each bite a slight freshness that lightens what could otherwise be a heavy paneer snack',
          'They add visual greenery inside the roll without needing to be cooked or prepared separately',
          'The crunch of sunflower microgreens contrasts nicely with the softness of paneer tikka and chapati',
          'This recipe is a natural way to include microgreens in a snack format that is familiar and well-liked',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: SUNFLOWER_MICROGREEN_PANEER_ROLL_BITES_IMAGES.ingredients,
        imageAlt: 'Ingredients for Sunflower Microgreen Paneer Roll Bites',
        contentType: 'ingredients',
        items: [
          '1 cup fresh sunflower microgreens',
          '200g paneer, cut into strips and marinated',
          '2 tbsp thick curd',
          '½ tsp red chilli powder',
          '¼ tsp garam masala',
          '¼ tsp cumin powder',
          '½ tsp ginger-garlic paste',
          'Salt as needed',
          '4 chapatis or thin rotis, warm',
          '2 tbsp green chutney',
          '2 tbsp yogurt-based dip or mayonnaise',
          '½ onion, thinly sliced',
          '½ green capsicum, thinly sliced',
          '1 tsp lemon juice',
          '1 tsp oil for cooking',
          'Chaat masala for finishing',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: SUNFLOWER_MICROGREEN_PANEER_ROLL_BITES_IMAGES.process,
        imageAlt: 'Making Sunflower Microgreen Paneer Roll Bites',
        contentType: 'steps',
        items: [
          'Marinate paneer strips in curd, chilli powder, garam masala, cumin, ginger-garlic paste, and salt.',
          'Cook the paneer strips on a hot tawa or pan until lightly charred on both sides.',
          'Prepare the filling station: green chutney, microgreens, sliced onion, capsicum.',
          'Spread green chutney and yogurt dip on each warm chapati.',
          'Place 2–3 paneer strips at the centre.',
          'Add a small handful of sunflower microgreens on top of the paneer.',
          'Add sliced onion and capsicum.',
          'Squeeze a few drops of lemon juice.',
          'Sprinkle chaat masala.',
          'Roll the chapati tightly and cut in half.',
          'Serve immediately while the chapati is still warm.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: SUNFLOWER_MICROGREEN_PANEER_ROLL_BITES_IMAGES.howWeMakeIt,
        imageAlt: 'Sunflower Microgreen Paneer Roll Bites served',
        contentType: 'narrative',
        narrative: [
          'Sunflower Microgreen Paneer Roll Bites are designed to show that microgreens don\'t just belong in salads. Here, they go inside a warm chapati roll alongside spiced paneer tikka.',
          'The paneer is cooked on a hot tawa until it gets a slight char, similar to paneer tikka. This gives each roll a smoky, slightly crispy paneer piece that contrasts with the fresh microgreens inside.',
          'The sunflower microgreens stay raw and go in just before rolling. They add a fresh, juicy crunch and bring a visual freshness to what is otherwise a familiar paneer roll.',
          'Green chutney and a yogurt dip are spread on the chapati first. They add moisture, tang, and freshness.',
          'Cut in half, these rolls make compact, tidy bites that are easy to serve as a starter, snack box item, or party finger food.',
        ],
      },
    ],
  },
  {
    id: 'oyster-mushroom-spring-onion-pan-bites',
    title: 'Oyster Mushroom Spring Onion Pan Bites',
    categoryIds: ['quick-snacks', 'mushroom-recipes'],
    primaryCategoryLabel: 'Quick Snacks',
    cookingTime: '20 minutes',
    serves: '2–3 people',
    thumbnailSrc: OYSTER_MUSHROOM_SPRING_ONION_PAN_BITES_IMAGES.thumbnail,
    nutritionProfiles: [NUTRITION_OYSTER_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Oyster Mushroom in this recipe',
        imageSrc: OYSTER_MUSHROOM_SPRING_ONION_PAN_BITES_IMAGES.goodness,
        imageAlt: 'Oyster Mushroom Spring Onion Pan Bites goodness',
        contentType: 'nutrition',
        items: [
          'Oyster mushrooms have a naturally tender texture that becomes slightly crispy when pan-roasted on high heat',
          'Their broad, flat shape gives them more surface area for browning, which creates a good char without deep frying',
          'Spring onion softens the natural earthiness of oyster mushroom and adds a fresh green flavour to the pan bites',
          'Oyster mushrooms cook quickly, making this a fast snack that can be prepared in under 20 minutes',
          'Their flavour absorbs soy or pepper seasoning easily, so even a simple spice mix gives each bite a full taste',
          'This recipe is light enough to be a starter but flavourful enough to stand on its own as a snack',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: OYSTER_MUSHROOM_SPRING_ONION_PAN_BITES_IMAGES.ingredients,
        imageAlt: 'Ingredients for Oyster Mushroom Spring Onion Pan Bites',
        contentType: 'ingredients',
        items: [
          '200g Oyster Mushrooms, torn into medium pieces',
          '3–4 stalks spring onion, bulbs and greens separated, sliced',
          '4–5 garlic cloves, thinly sliced',
          '1 green chilli, slit',
          '½ tsp black pepper powder',
          '1 tsp soy sauce or tamari',
          '½ tsp red chilli flakes',
          'Salt as needed',
          '1 tbsp oil',
          '1 tsp sesame oil for finishing, optional',
          '1 tsp lemon juice',
          'Sesame seeds for topping, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: OYSTER_MUSHROOM_SPRING_ONION_PAN_BITES_IMAGES.process,
        imageAlt: 'Making Oyster Mushroom Spring Onion Pan Bites',
        contentType: 'steps',
        items: [
          'Tear oyster mushrooms into medium pieces.',
          'Pat them dry to remove surface moisture.',
          'Heat a heavy pan or cast iron on high flame.',
          'Add oil and arrange oyster mushroom pieces in a single layer.',
          'Do not disturb for 2–3 minutes to let a sear develop.',
          'Flip and cook the other side.',
          'Push mushrooms to the side and add garlic, spring onion bulbs, and green chilli.',
          'Toss together quickly.',
          'Add soy sauce, pepper, and chilli flakes.',
          'Cook for 1–2 more minutes on high heat.',
          'Add spring onion greens.',
          'Finish with sesame oil, lemon juice, and sesame seeds.',
          'Serve immediately from the pan.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: OYSTER_MUSHROOM_SPRING_ONION_PAN_BITES_IMAGES.howWeMakeIt,
        imageAlt: 'Oyster Mushroom Spring Onion Pan Bites served',
        contentType: 'narrative',
        narrative: [
          'Oyster Mushroom Spring Onion Pan Bites are built around high heat and quick cooking. Oyster mushrooms need a hot pan to develop a proper sear. In a warm pan, they will simply steam and become soft. High heat gives them a slightly crispy edge.',
          'The mushrooms go in a single layer without being moved for the first 2–3 minutes. That undisturbed time is what creates the golden sear. After flipping, the second side cooks faster because the pan is already very hot.',
          'Garlic and spring onion bulbs go in only after the mushrooms are mostly cooked. They should be fragrant but not burnt.',
          'Soy sauce gives the bites a savoury depth. Sesame oil at the end brings an aromatic finish that makes the dish feel complete.',
          'These are best eaten straight from the pan.',
        ],
      },
    ],
  },
  {
    id: 'microgreen-chilli-cheese-sandwich-triangles',
    title: 'Microgreen Chilli Cheese Sandwich Triangles',
    categoryIds: ['quick-snacks', 'microgreen-recipes'],
    primaryCategoryLabel: 'Quick Snacks',
    cookingTime: '15 minutes',
    serves: '2 people',
    thumbnailSrc: MICROGREEN_CHILLI_CHEESE_SANDWICH_TRIANGLES_IMAGES.thumbnail,
    cards: [
      {
        id: 'goodness',
        title: 'Goodness of Microgreens in this recipe',
        imageSrc: MICROGREEN_CHILLI_CHEESE_SANDWICH_TRIANGLES_IMAGES.goodness,
        imageAlt: 'Microgreen Chilli Cheese Sandwich Triangles goodness',
        contentType: 'nutrition',
        items: [
          'A mix of available microgreens works well here — sunflower for crunch, radish for a light pepper bite, or broccoli for a mild fresh taste',
          'Using microgreens raw inside a toasted sandwich keeps their freshness alive even after the bread is grilled',
          'They add visible green texture to what is otherwise a simple cheese sandwich',
          'Microgreens bring a fresh, herbal note that lifts the taste and balances the richness of melted cheese',
          'This recipe is a practical daily way to include microgreens in a meal that needs no cooking',
          'It is suitable for breakfast, lunchboxes, or a quick snack when fresh microgreens are available',
        ],
      },
      {
        id: 'ingredients',
        title: 'Ingredients',
        imageSrc: MICROGREEN_CHILLI_CHEESE_SANDWICH_TRIANGLES_IMAGES.ingredients,
        imageAlt: 'Ingredients for Microgreen Chilli Cheese Sandwich Triangles',
        contentType: 'ingredients',
        items: [
          '4 bread slices',
          '1 cup mixed fresh microgreens (sunflower, radish, or broccoli)',
          '½ cup grated cheese',
          '1 green chilli, finely chopped',
          '1 tbsp butter',
          '¼ tsp black pepper powder',
          'Pinch of oregano or mixed herbs',
          '2 tsp green chutney or mustard spread, optional',
        ],
      },
      {
        id: 'process',
        title: 'Process',
        imageSrc: MICROGREEN_CHILLI_CHEESE_SANDWICH_TRIANGLES_IMAGES.process,
        imageAlt: 'Making Microgreen Chilli Cheese Sandwich Triangles',
        contentType: 'steps',
        items: [
          'Butter one side of each bread slice.',
          'On the unbuttered side, spread green chutney or mustard if using.',
          'Add a layer of grated cheese.',
          'Add chopped green chilli, a pinch of pepper, and herbs.',
          'Place a generous amount of fresh microgreens on top.',
          'Close the sandwich with the second slice, buttered side facing out.',
          'Toast on a hot tawa or in a sandwich maker until golden and crisp.',
          'Cut into triangles.',
          'Serve immediately while the cheese is melted and the greens are still fresh inside.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        imageSrc: MICROGREEN_CHILLI_CHEESE_SANDWICH_TRIANGLES_IMAGES.howWeMakeIt,
        imageAlt: 'Microgreen Chilli Cheese Sandwich Triangles served',
        contentType: 'narrative',
        narrative: [
          'Microgreen Chilli Cheese Sandwich Triangles are a straightforward recipe that makes microgreens accessible for anyone. The key principle is simple: the cheese melts, the bread toasts, and the microgreens inside stay fresh.',
          'We butter the outside of the bread, not the inside. This gives a clean, evenly golden surface when it toasts on the tawa.',
          'The cheese goes directly on the bread first. When the sandwich is toasted, the cheese melts and holds the microgreens in place when the sandwich is cut. Without the cheese layer, the microgreens can shift and fall out.',
          'The microgreens are added raw and placed on the melted cheese layer. The heat from the toast gently warms them without fully cooking them, which keeps their fresh character.',
          'Cutting into triangles after toasting is the final step. Triangle-cut sandwiches are easier to hold as finger food, and the cross-section shows the colourful layers inside.',
        ],
      },
    ],
  },
]
