import type { RecipeData } from '@/types'
import {
  NUTRITION_BUTTON_MUSHROOM_USDA,
  NUTRITION_OYSTER_MUSHROOM_USDA,
} from '@/constants/NUTRITION_PROFILES'

export const READY_MEAL_BOX_RECIPES: RecipeData[] = [
  {
    id: 'mushroom-rice-box',
    title: 'Mushroom Rice Box',
    categoryIds: ['meal-prep-ideas', 'everyday-meals'],
    primaryCategoryLabel: 'Meal Prep Ideas',
    cookingTime: '30 minutes',
    serves: '1 box / 1 person',
    nutritionProfiles: [NUTRITION_BUTTON_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Why this box works',
        contentType: 'nutrition',
        items: [
          'Button mushroom rice is a complete carbohydrate and protein combination that travels well in a box',
          'The rice absorbs the mushroom masala and stays flavourful even after cooling',
          'This box suits office lunch or a school meal because it does not need reheating to taste good',
          'Mushroom rice is filling enough to be a full meal without needing an additional curry',
          'The box works for meal prep: make a large batch and portion into single-serve boxes for the week',
          'Simple sides like a small pickle or papad complete the box without adding preparation complexity',
        ],
      },
      {
        id: 'ingredients',
        title: 'Box Contents',
        contentType: 'ingredients',
        items: [
          '1 serving Button Mushroom Tomato Rice or Milky Mushroom Pulao',
          '1 small portion thick curd or raita',
          'Pickle, 1–2 pieces',
          'Papad or roasted seeds, optional',
          'Lemon wedge',
          'Fresh coriander garnish',
        ],
      },
      {
        id: 'process',
        title: 'Box Preparation',
        contentType: 'steps',
        items: [
          'Prepare Button Mushroom Tomato Rice or Milky Mushroom Pulao.',
          'Allow to cool to room temperature before boxing.',
          'Portion the rice into the box — about 1.5 to 2 cups per serving.',
          'Pack curd or raita separately in a small container.',
          'Add pickle and lemon wedge.',
          'Add papad or seeds on the side if included.',
          'Close the box and refrigerate if preparing the night before.',
          'Best consumed within 6–8 hours of preparation.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Mushroom Rice Box is a meal prep-friendly format designed for office lunches, school tiffins, and catering boxes. The mushroom rice at its base is already a complete dish — flavourful, filling, and functional.',
          'We cool the rice fully before boxing. Hot rice placed directly in a closed box traps steam and makes the grains soggy.',
          'Curd is packed separately because it should not mix with rice until eating. Once mixed, it softens the rice quickly.',
          'Pickle adds a sharp, tangy element that makes the box taste complete even without a side curry.',
          'For catering or event use, these boxes can be assembled in large batches and distributed efficiently.',
        ],
      },
    ],
  },
  {
    id: 'mushroom-chapati-curry-box',
    title: 'Mushroom Chapati Curry Box',
    categoryIds: ['meal-prep-ideas', 'everyday-meals'],
    primaryCategoryLabel: 'Meal Prep Ideas',
    cookingTime: '35 minutes',
    serves: '1 box / 1 person',
    nutritionProfiles: [NUTRITION_BUTTON_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Why this box works',
        contentType: 'nutrition',
        items: [
          'Chapati and mushroom curry together provide carbohydrate and protein in a portable format',
          'Button mushroom curry with sufficient gravy soaks into the chapati beautifully without making it soggy if packed correctly',
          'This box is one of the most popular everyday meal formats in Indian homes and travels well',
          'The curry portion gives enough moisture for the chapati without needing extra side dishes',
          'Chapati keeps well for 4–6 hours when wrapped and stored properly',
          'This is a familiar, comforting box that suits all ages and meal occasions',
        ],
      },
      {
        id: 'ingredients',
        title: 'Box Contents',
        contentType: 'ingredients',
        items: [
          '2–3 chapatis, wrapped or in one layer',
          '1 portion Button Mushroom Chapati Gravy',
          '1 small portion cut salad (cucumber, tomato, onion)',
          '1–2 pieces pickle',
          'Lemon wedge',
        ],
      },
      {
        id: 'process',
        title: 'Box Preparation',
        contentType: 'steps',
        items: [
          'Prepare Button Mushroom Chapati Gravy.',
          'Make fresh chapatis.',
          'Wrap chapatis in a cloth or foil to keep them soft.',
          'Allow the curry to cool slightly before boxing.',
          'Pack curry in the main box compartment.',
          'Arrange wrapped chapatis beside or on top.',
          'Add fresh cut salad in a separate section.',
          'Add pickle and lemon wedge.',
          'Close and pack for transport.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Mushroom Chapati Curry Box is the most standard tiffin format in Indian everyday life. Almost every household knows this box — chapati and sabzi — and it works because it is balanced, filling, and familiar.',
          'The key to a good chapati box is keeping the chapati and curry in separate sections until eating. If the curry sits on the chapati for too long, the chapati absorbs the gravy and becomes heavy.',
          'The Button Mushroom Chapati Gravy should have enough body to be a dipping curry, not too thick or too watery. A slightly thick, saucy consistency is ideal for box packing.',
          'Fresh cut salad in a corner of the box adds freshness and crunch that the chapati and curry do not provide.',
          'This box is scalable for catering — 50, 100, or 500 boxes can be prepared from the same recipe with batch cooking.',
        ],
      },
    ],
  },
  {
    id: 'mushroom-millet-curd-box',
    title: 'Mushroom Millet Curd Box',
    categoryIds: ['meal-prep-ideas', 'healthy-plates'],
    primaryCategoryLabel: 'Meal Prep Ideas',
    cookingTime: '25 minutes',
    serves: '1 box / 1 person',
    nutritionProfiles: [NUTRITION_BUTTON_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Why this box works',
        contentType: 'nutrition',
        items: [
          'Foxtail millet is a low-GI grain that is filling without creating energy spikes, making it suitable for a work lunch',
          'Button mushroom sautéed with mild spices pairs naturally with millet and curd',
          'Thick curd provides probiotics and a cooling element that makes the box feel light and refreshing',
          'This box suits people managing diet, diabetes-friendly meals, or those simply looking for a healthier lunch alternative',
          'Millet keeps well for 4–6 hours in a box and does not become sticky or heavy',
          'The box is naturally lower in calories than a rice-curry equivalent without feeling unsatisfying',
        ],
      },
      {
        id: 'ingredients',
        title: 'Box Contents',
        contentType: 'ingredients',
        items: [
          '1 cup cooked foxtail millet or kodo millet',
          '1 portion sautéed Button Mushrooms with mild seasoning',
          '½ cup thick curd with seasoning',
          '½ cucumber, sliced',
          '2 tbsp roasted peanuts',
          '1–2 pieces pickle',
          'Fresh coriander',
        ],
      },
      {
        id: 'process',
        title: 'Box Preparation',
        contentType: 'steps',
        items: [
          'Cook millet and cool to room temperature.',
          'Sauté button mushrooms with cumin, curry leaves, pepper, and salt.',
          'Season curd with cumin powder, pepper, and salt.',
          'Pack millet in the main box area.',
          'Place sautéed mushrooms beside the millet.',
          'Add sliced cucumber.',
          'Pack seasoned curd in a separate small container.',
          'Add peanuts, pickle, and coriander.',
          'Refrigerate if preparing the night before.',
          'Best consumed within 6–8 hours.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Mushroom Millet Curd Box is one of our health-forward meal prep options. It is designed for people who want a functional, filling lunch that does not leave them feeling heavy in the afternoon.',
          'Millet and curd are a naturally compatible combination. Millet is slightly earthy and nutty, and curd smooths that out with its cool, creamy quality.',
          'The mushrooms are sautéed simply — no heavy masala. Cumin and curry leaves give enough flavour without overwhelming the lightness of the millet and curd.',
          'We season the curd separately. Plain cold curd on a box can feel like an afterthought. Seasoning it turns it into a proper side that the eater can mix into the millet.',
          'This box format is also good for catering in wellness events, corporate health lunches, or meal subscription services.',
        ],
      },
    ],
  },
  {
    id: 'microgreen-paneer-roll-box',
    title: 'Microgreen Paneer Roll Box',
    categoryIds: ['meal-prep-ideas', 'quick-snacks'],
    primaryCategoryLabel: 'Meal Prep Ideas',
    cookingTime: '30 minutes',
    serves: '1 box / 1 person',
    cards: [
      {
        id: 'goodness',
        title: 'Why this box works',
        contentType: 'nutrition',
        items: [
          'Paneer rolls with fresh microgreens inside travel well because the roll structure keeps the filling contained',
          'Sunflower microgreens inside the roll add crunch and freshness that holds even after 2–3 hours in the box',
          'The roll format is finger food-friendly, making it suitable for children\'s tiffin, events, or office snack boxes',
          'This is one of the most appealing meal prep formats visually — the roll, when cut, shows colourful layers inside',
          'Paneer provides protein; microgreens provide fresh vitamins; chapati provides carbohydrate in one compact package',
          'Rolls can be cut in half before boxing, making them easier to eat without utensils',
        ],
      },
      {
        id: 'ingredients',
        title: 'Box Contents',
        contentType: 'ingredients',
        items: [
          '2 Sunflower Microgreen Paneer Rolls (see recipe)',
          'Green chutney sachet or small container',
          '1 small portion cut fresh vegetables',
          '2 tbsp roasted seeds or peanuts',
          'Lemon wedge',
          'Chaat masala, optional',
        ],
      },
      {
        id: 'process',
        title: 'Box Preparation',
        contentType: 'steps',
        items: [
          'Prepare paneer tikka filling and cool slightly.',
          'Make fresh chapatis.',
          'Assemble the rolls while the paneer is still warm.',
          'Do not add too much chutney inside the roll if the box is for a long journey — it can make the chapati soggy.',
          'Wrap each roll in foil or parchment paper.',
          'Cut in half if preferred.',
          'Place the wrapped rolls in the box.',
          'Pack chutney separately.',
          'Add fresh vegetables, seeds, and lemon.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Microgreen Paneer Roll Box is a premium version of the everyday tiffin box. The rolls look attractive, eat well as finger food, and the microgreens inside keep them feeling fresh.',
          'We wrap each roll in foil or parchment before boxing. This keeps the chapati from drying out and also keeps the roll\'s structure intact.',
          'For long-distance delivery, we recommend packing the chutney separately. If chutney sits inside the roll for more than an hour, the chapati absorbs moisture and becomes soft at the seams.',
          'Cut rolls show the colourful cross-section inside — green from microgreens, golden from paneer, yellow from the chutney layer. This makes them good for presentation boxes, catering menus, and event packages.',
          'This box suits corporate catering, wellness meal delivery, and restaurant takeaway menus equally.',
        ],
      },
    ],
  },
  {
    id: 'mushroom-egg-fitness-box',
    title: 'Mushroom Egg Fitness Box',
    categoryIds: ['meal-prep-ideas', 'healthy-plates'],
    primaryCategoryLabel: 'Meal Prep Ideas',
    cookingTime: '25 minutes',
    serves: '1 box / 1 person',
    nutritionProfiles: [NUTRITION_BUTTON_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Why this box works',
        contentType: 'nutrition',
        items: [
          'Button mushroom and egg together provide a high-protein, moderate-calorie meal suitable for active people',
          'This box is designed for people with fitness goals who want a lunch that supports recovery without being heavy',
          'Whole eggs provide all essential amino acids alongside healthy fat from the yolk',
          'Button mushroom protein adds to the egg protein without duplicating the fat content',
          'A millet or brown rice base gives slow-releasing carbohydrates to sustain energy',
          'The box is deliberately simple in seasoning so the nutritional value is not lost in heavy cooking',
        ],
      },
      {
        id: 'ingredients',
        title: 'Box Contents',
        contentType: 'ingredients',
        items: [
          '1 portion Button Mushroom Egg Bhurji',
          '1 cup cooked millet or brown rice',
          '½ cucumber and 1 small tomato, sliced',
          '2 tbsp roasted peanuts or seeds',
          '1 tbsp lemon juice',
          'Pinch of black pepper',
          'Fresh coriander',
        ],
      },
      {
        id: 'process',
        title: 'Box Preparation',
        contentType: 'steps',
        items: [
          'Prepare Button Mushroom Egg Bhurji.',
          'Cook millet or brown rice.',
          'Cool both to room temperature before boxing.',
          'Pack bhurji in the main compartment.',
          'Add cooked millet or rice.',
          'Add sliced cucumber and tomato.',
          'Add roasted peanuts or seeds.',
          'Pack lemon separately or squeeze over before closing.',
          'Add fresh coriander garnish.',
          'Box and refrigerate if not eating within 2 hours.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Mushroom Egg Fitness Box is built for people who take what they eat seriously but also need it to be convenient. The Button Mushroom Egg Bhurji is the centrepiece — high protein, quick to make, and satisfying.',
          'We let the bhurji cool before boxing. Hot bhurji in a closed box creates steam that makes the grain below it clumpy.',
          'The grain base gives the box its staying power. Millet keeps blood sugar steadier than white rice. Brown rice gives a familiar texture with more fibre than polished rice.',
          'Roasted seeds or peanuts on the side give extra healthy fat and crunch. They should be kept separate from the warm bhurji until eating.',
          'This box format can be used for gym meal prep, sports nutrition menus, and workplace health initiatives.',
        ],
      },
    ],
  },
  {
    id: 'mushroom-coconut-curry-rice-box',
    title: 'Mushroom Coconut Curry Rice Box',
    categoryIds: ['meal-prep-ideas', 'everyday-meals'],
    primaryCategoryLabel: 'Meal Prep Ideas',
    cookingTime: '35 minutes',
    serves: '1 box / 1 person',
    nutritionProfiles: [NUTRITION_OYSTER_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Why this box works',
        contentType: 'nutrition',
        items: [
          'Oyster mushroom coconut curry is a rich-tasting curry that pairs naturally with plain rice in a box',
          'Coconut milk gives the curry a smooth body that does not separate or look unappetising after cooling',
          'This box suits people who want something more special than a standard curry-rice lunch',
          'Oyster mushroom protein in a coconut gravy is filling and satisfying without being heavy',
          'The curry holds its flavour well after cooling, making it suitable for packing 2–3 hours before eating',
          'A small fresh salad or papad on the side balances the richness of the coconut curry',
        ],
      },
      {
        id: 'ingredients',
        title: 'Box Contents',
        contentType: 'ingredients',
        items: [
          '1 cup cooked rice',
          '1 portion Oyster Mushroom Coconut Curry for Rice',
          '½ cucumber, sliced',
          'Papad or roasted seeds, optional',
          '1–2 pieces pickle',
          'Fresh coriander',
        ],
      },
      {
        id: 'process',
        title: 'Box Preparation',
        contentType: 'steps',
        items: [
          'Prepare Oyster Mushroom Coconut Curry.',
          'Cook plain rice.',
          'Cool both to room temperature.',
          'Pack rice in one section of the box.',
          'Ladle the coconut curry into the box, alongside the rice.',
          'Add sliced cucumber.',
          'Add pickle on the side.',
          'Close and refrigerate if not eating immediately.',
          'Curry can be gently reheated in a separate pan if preferred hot.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Mushroom Coconut Curry Rice Box feels more special than an everyday rice box. The coconut curry has a smooth, mild richness that makes it a restaurant-quality meal in a lunch box format.',
          'Coconut curry holds very well in a box. Unlike some water-based curries that separate or become watery, coconut curry maintains its body and remains creamy after cooling.',
          'We pack the rice and curry in the same box but in separate sections. At eating time, the person can mix them or eat them side by side.',
          'A small pickle adds the sharpness needed to cut through the richness of the coconut curry.',
          'This box is well-suited to events, corporate catering, and premium meal delivery services because it looks generous and tastes satisfying.',
        ],
      },
    ],
  },
  {
    id: 'mushroom-dal-rice-box',
    title: 'Mushroom Dal Rice Box',
    categoryIds: ['meal-prep-ideas', 'everyday-meals'],
    primaryCategoryLabel: 'Meal Prep Ideas',
    cookingTime: '35 minutes',
    serves: '1 box / 1 person',
    cards: [
      {
        id: 'goodness',
        title: 'Why this box works',
        contentType: 'nutrition',
        items: [
          'Dal and rice is one of the most balanced and complete Indian meals, providing protein and carbohydrate together',
          'Adding milky mushroom to the dal brings additional protein, fibre, and a satisfying meaty texture',
          'This box is the most comforting and filling option in the meal prep range',
          'Dal holds well for 4–6 hours in a closed box without separating or becoming unpleasant',
          'The familiar dal-rice format makes this box suitable for all age groups and dietary preferences',
          'A small papad or ghee portion makes the box feel complete and traditional',
        ],
      },
      {
        id: 'ingredients',
        title: 'Box Contents',
        contentType: 'ingredients',
        items: [
          '1 cup cooked plain rice',
          '1 portion Milky Mushroom Dal Curry',
          'Pickle or papad',
          '½ tsp ghee, optional',
          'Sliced onion and green chilli, optional',
          'Fresh coriander',
          'Lemon wedge',
        ],
      },
      {
        id: 'process',
        title: 'Box Preparation',
        contentType: 'steps',
        items: [
          'Prepare Milky Mushroom Dal Curry.',
          'Cook plain rice.',
          'Cool both slightly before boxing.',
          'Pack rice in the main box.',
          'Ladle dal curry over or beside the rice.',
          'Add ghee on the rice if including.',
          'Add pickle, papad, salad, and lemon.',
          'Close and store safely.',
          'Best consumed within 6–8 hours.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Mushroom Dal Rice Box is our most wholesome and comforting meal prep option. Dal rice is India\'s most familiar complete meal, and adding milky mushroom elevates it from a simple everyday dish to something more satisfying.',
          'The dal should be slightly thick for a box — not the thin pouring consistency of restaurant dal. Thick dal stays in place in the box and does not leak.',
          'Ghee on the rice is a small touch that makes a big difference. Even a small amount of ghee makes the rice smell warm and inviting when the box is opened.',
          'This box works for hospital meal services, school tiffin programs, elderly care catering, and everyday corporate lunch boxes because of its universal appeal.',
          'For bulk catering orders, Milky Mushroom Dal Curry batch-cooks efficiently and can be prepared the morning of service.',
        ],
      },
    ],
  },
  {
    id: 'mushroom-lemon-rice-box',
    title: 'Mushroom Lemon Rice Box',
    categoryIds: ['meal-prep-ideas', 'everyday-meals'],
    primaryCategoryLabel: 'Meal Prep Ideas',
    cookingTime: '25 minutes',
    serves: '1 box / 1 person',
    nutritionProfiles: [NUTRITION_OYSTER_MUSHROOM_USDA],
    cards: [
      {
        id: 'goodness',
        title: 'Why this box works',
        contentType: 'nutrition',
        items: [
          'Lemon rice is a South Indian travel classic — it holds well, tastes bright, and does not need reheating',
          'Oyster mushroom in the lemon rice adds protein and earthy depth without changing the character of the dish',
          'Lemon and turmeric in the rice are natural preservatives that help the box stay fresh longer',
          'This box is suitable for long journeys, school tiffin, and workday lunches where reheating may not be possible',
          'Roasted peanuts keep their crunch well in a rice box, providing texture contrast',
          'The entire box can be prepared in under 30 minutes, making it one of the fastest meal prep options',
        ],
      },
      {
        id: 'ingredients',
        title: 'Box Contents',
        contentType: 'ingredients',
        items: [
          '1 serving Oyster Mushroom Lemon Rice',
          '2 tbsp extra roasted peanuts',
          '½ cucumber, sliced',
          'Pickle or mango thokku',
          'Papad, optional',
          'Lemon wedge',
        ],
      },
      {
        id: 'process',
        title: 'Box Preparation',
        contentType: 'steps',
        items: [
          'Prepare Oyster Mushroom Lemon Rice.',
          'Cool fully to room temperature.',
          'Pack in the box — do not close while hot.',
          'Add extra roasted peanuts on top.',
          'Add cucumber and pickle.',
          'Add papad if including.',
          'Pack lemon wedge on the side.',
          'Close and pack.',
          'This box is best consumed at room temperature.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Mushroom Lemon Rice Box is one of the most travel-friendly boxes in the collection. Lemon rice does not need to be eaten hot. In fact, many people prefer it at room temperature because the lemon flavour is more vivid when it is not very hot.',
          'The Oyster Mushroom Lemon Rice recipe already includes roasted peanuts. For the box, we add a few extra peanuts on top, because they provide a crunch that becomes the most satisfying textural element of the box.',
          'Lemon rice should be fully cooled before boxing. Rice boxed while hot creates condensation inside the lid, and that moisture can make the peanuts soggy and the rice clump together.',
          'Pickle or mango thokku on the side is the traditional accompaniment. Their sharpness cuts through the lemon rice and makes the box feel complete.',
          'This is one of the best batch-prep rice options — a large quantity can be made and portioned into many boxes efficiently.',
        ],
      },
    ],
  },
  {
    id: 'mushroom-microgreen-fresh-harvest-box',
    title: 'Mushroom Microgreen Fresh Harvest Box',
    categoryIds: ['meal-prep-ideas', 'healthy-plates'],
    primaryCategoryLabel: 'Meal Prep Ideas',
    nutritionProfiles: [NUTRITION_BUTTON_MUSHROOM_USDA, NUTRITION_OYSTER_MUSHROOM_USDA],
    cookingTime: '30 minutes',
    serves: '1 box / 1 person',
    cards: [
      {
        id: 'goodness',
        title: 'Why this box works',
        contentType: 'nutrition',
        items: [
          'This box is built from what Prozekt-1 grows — mushrooms and microgreens — in a premium, presentation-quality format',
          'Mushroom provides protein and umami; microgreens provide fresh vitamins and visual colour',
          'The box is designed for customers who want farm-fresh produce in a ready-to-eat format',
          'Microgreens are added to the box separately and placed on top so they stay fresh until the box is opened',
          'This box is suitable for premium corporate catering, wellness meal delivery, and restaurant meal kits',
          'The visual quality of this box — colourful microgreens over warm mushrooms — makes it stand out in a catering spread',
        ],
      },
      {
        id: 'ingredients',
        title: 'Box Contents',
        contentType: 'ingredients',
        items: [
          '1 serving Prozekt-1 Fresh Harvest Plate (mushroom components)',
          '1 cup fresh mixed microgreens, packed separately in a small pouch',
          '1 cup cooked millet or brown rice',
          '½ cucumber, sliced',
          '2 tbsp roasted seeds or peanuts',
          'Lemon dressing in a small sealed container',
          'Green chutney or yogurt dip, optional',
        ],
      },
      {
        id: 'process',
        title: 'Box Preparation',
        contentType: 'steps',
        items: [
          'Prepare the mushroom components from the Fresh Harvest Plate recipe.',
          'Cool the cooked mushrooms and grain.',
          'Pack grain in the main box compartment.',
          'Place cooked mushroom pieces.',
          'Pack fresh microgreens in a separate small sealed pouch or corner of the box.',
          'Add sliced cucumber.',
          'Pack lemon dressing in a small sealed container.',
          'Add seeds or peanuts.',
          'Include a note suggesting the customer add microgreens and dressing just before eating.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Mushroom Microgreen Fresh Harvest Box is our premium meal prep format. It is the box version of the Prozekt-1 Fresh Harvest Plate and is designed for delivery, premium catering, and corporate wellness programs.',
          'The key decision in this box is keeping the microgreens separate until eating. Microgreens that sit in a warm, closed box for more than 30–45 minutes begin to wilt. By packing them separately in a small sealed pouch, we ensure they are still fresh and vibrant when the customer opens the box.',
          'The lemon dressing also goes separately. If added to the box before sealing, the dressing will slowly soften the greens and make the grain taste acidic. Packed separately, the customer controls when and how much to add.',
          'For catering, these boxes should include a simple instruction card: "Open the microgreen pouch, pour the dressing, and toss gently before eating."',
          'This is Prozekt-1\'s highest-quality meal format — fresh produce, clean cooking, and presented with care.',
        ],
      },
    ],
  },
  {
    id: 'mushroom-sambar-rice-box',
    title: 'Mushroom Sambar Rice Box',
    categoryIds: ['meal-prep-ideas', 'everyday-meals'],
    primaryCategoryLabel: 'Meal Prep Ideas',
    cookingTime: '40 minutes',
    serves: '1 box / 1 person',
    cards: [
      {
        id: 'goodness',
        title: 'Why this box works',
        contentType: 'nutrition',
        items: [
          'Sambar rice is one of South India\'s most beloved comfort meal formats, now made with milky mushroom',
          'Mushroom sambar provides dal protein alongside mushroom protein and tamarind-based digestive benefits',
          'The sambar can be mixed into the rice in the box or poured over at eating time, depending on preference',
          'Tamarind and pepper in sambar are traditionally considered digestive and warming',
          'This box suits all age groups and is comforting for people far from home who want familiar food',
          'The dish travels well because sambar rice holds its texture even at room temperature',
        ],
      },
      {
        id: 'ingredients',
        title: 'Box Contents',
        contentType: 'ingredients',
        items: [
          '1 cup cooked plain rice',
          '1 portion Milky Mushroom Sambar-Style Curry',
          '1 tsp ghee, optional',
          'Papad',
          '1–2 pieces pickle',
          'Sliced onion or small cut salad',
          'Fresh coriander',
        ],
      },
      {
        id: 'process',
        title: 'Box Preparation',
        contentType: 'steps',
        items: [
          'Prepare Milky Mushroom Sambar-Style Curry.',
          'Cook plain rice.',
          'Cool both slightly.',
          'Pack rice in the box with ghee if including.',
          'Ladle sambar over or beside the rice.',
          'Add papad, pickle, and salad.',
          'Garnish with coriander.',
          'Close and store.',
          'Best consumed within 6 hours.',
        ],
      },
      {
        id: 'how-we-make-it',
        title: 'How We Make It',
        contentType: 'narrative',
        narrative: [
          'Mushroom Sambar Rice Box is a South Indian comfort classic made with milky mushroom sambar. It is the most familiar and universally liked box format among South Indian customers.',
          'For a sambar rice box, the sambar consistency matters more than in a table-service version. Box sambar should be slightly thicker so it does not leak and make the box messy. We adjust the consistency during cooking.',
          'Rice and sambar are packed together in the box. The person eating can mix them at the table or in the box itself. Either way, the dish is complete.',
          'Papad is non-negotiable in a proper sambar rice box. It gives the box its crunch and makes the meal feel genuinely traditional.',
          'This is the box format most likely to be requested for school, hospital, temple, or event catering in South India.',
        ],
      },
    ],
  },
]
